"""
Admin for weekly KPI snapshots.

Read-only trend table: one row per ISO week with the headline KPIs pulled from
the persisted ``metrics`` JSON, plus a CSV export of the full flattened payload
so the numbers can be charted in a spreadsheet.
"""
import csv

from django.contrib import admin
from django.http import HttpResponse
from django.utils import timezone

from crush_lu.models import WeeklyMetricsSnapshot


def _flatten(metrics, prefix=""):
    """Flatten the nested metrics dict to ``{"section.metric": value}``."""
    flat = {}
    for key, value in (metrics or {}).items():
        path = f"{prefix}{key}"
        if isinstance(value, dict):
            flat.update(_flatten(value, prefix=f"{path}."))
        else:
            flat[path] = value
    return flat


class WeeklyMetricsSnapshotAdmin(admin.ModelAdmin):
    list_display = (
        "week_start",
        "week_end",
        "signups",
        "verified",
        "wau",
        "new_premium",
        "events_held",
        "computed_at",
    )
    ordering = ("-week_start",)
    date_hierarchy = "week_start"
    readonly_fields = ("week_start", "week_end", "metrics", "computed_at")
    actions = ("export_snapshots_csv",)

    def has_add_permission(self, request):
        # Snapshots are generated by the send_weekly_kpis command, not by hand.
        return False

    # ── Headline columns (read from the metrics JSON) ────────────────
    @admin.display(description="Signups")
    def signups(self, obj):
        return obj.metrics.get("acquisition", {}).get("new_signups", "—")

    @admin.display(description="Verified ★")
    def verified(self, obj):
        return obj.metrics.get("acquisition", {}).get("profiles_verified", "—")

    @admin.display(description="WAU")
    def wau(self, obj):
        return obj.metrics.get("engagement", {}).get("wau", "—")

    @admin.display(description="New premium")
    def new_premium(self, obj):
        return obj.metrics.get("revenue", {}).get("new_premium", "—")

    @admin.display(description="Events")
    def events_held(self, obj):
        return obj.metrics.get("matching_events", {}).get("events_held", "—")

    # ── CSV export (full flattened payload) ──────────────────────────
    @admin.action(description="Export selected weeks to CSV")
    def export_snapshots_csv(self, request, queryset):
        queryset = queryset.order_by("week_start")
        # Union of all metric keys across the selected weeks, in stable order.
        columns = []
        seen = set()
        for snap in queryset:
            for key in _flatten(snap.metrics):
                if key not in seen:
                    seen.add(key)
                    columns.append(key)

        response = HttpResponse(content_type="text/csv")
        stamp = timezone.now().strftime("%Y%m%d_%H%M%S")
        response["Content-Disposition"] = (
            f'attachment; filename="weekly_kpis_{stamp}.csv"'
        )
        writer = csv.writer(response)
        writer.writerow(["week_start", "week_end", *columns])
        for snap in queryset:
            flat = _flatten(snap.metrics)
            writer.writerow(
                [snap.week_start, snap.week_end, *[flat.get(c, "") for c in columns]]
            )
        return response
