# Generated by Django 5.1 on 2025-06-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Title for the homepage hero section', max_length=200)),
                ('hero_subtitle', models.TextField(help_text='Subtitle for the homepage hero section')),
                ('hero_background_image', models.ImageField(help_text='Background image for the homepage hero section', upload_to='homepage/')),
            ],
            options={
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='VdlBlogPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Post Category',
                'verbose_name_plural': 'Blog Post Categories',
            },
        ),
        migrations.CreateModel(
            name='VdlProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producers/logos/')),
                ('producer_photo', models.ImageField(blank=True, help_text='Photo of the producer', null=True, upload_to='producers/photos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_featured_on_homepage', models.BooleanField(default=False, help_text='Feature this producer on the homepage?')),
            ],
        ),
        migrations.CreateModel(
            name='VdlAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='shipping', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='VdlBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='A short summary for list views.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='vinsdelux.vdlblogpostcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VdlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Red Wine', 'Red Wine'), ('White Wine', 'White Wine'), ('Rosé', 'Rosé'), ('Sparkling Wine', 'Sparkling Wine'), ('Dessert Wine', 'Dessert Wine')], max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vinsdelux.vdlcategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='VdlCoffret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.TextField(help_text='Brief overview for product listings.')),
                ('full_description', models.TextField(blank=True, help_text='Detailed description for product page.', null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the product available for purchase?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage or special sections?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for a single, one-time purchase of this coffret.', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock for this coffret')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='vinsdelux.vdlcategory')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='vinsdelux.vdlproducer')),
            ],
            options={
                'verbose_name': 'Coffret',
                'verbose_name_plural': 'Coffrets',
            },
        ),
        migrations.CreateModel(
            name='VdlOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('is_gift', models.BooleanField(default=False)),
                ('gift_message', models.TextField(blank=True, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or internal notes', null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='vinsdelux.vdladdress')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='vinsdelux.vdladdress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VdlOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Price of the item when the order was placed', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('personalization_details', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('vdlcoffret', 'vdladoptionplan')}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vinsdelux.vdlorder')),
            ],
        ),
        migrations.CreateModel(
            name='VdlAdoptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.TextField(help_text='Brief overview for product listings.')),
                ('full_description', models.TextField(blank=True, help_text='Detailed description for product page.', null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the product available for purchase?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage or special sections?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the entire adoption package', max_digits=10)),
                ('duration_months', models.IntegerField(help_text='Duration of the adoption in months')),
                ('coffrets_per_year', models.IntegerField(help_text='Number of seasonal coffrets included per year')),
                ('includes_visit', models.BooleanField(default=False, help_text='Does this plan include a vineyard visit?')),
                ('visit_details', models.TextField(blank=True, help_text='Details about the vineyard visit', null=True)),
                ('includes_medallion', models.BooleanField(default=False, help_text='Does this plan include a personalized medallion?')),
                ('includes_club_membership', models.BooleanField(default=False, help_text='Does this plan include Club Cuvée Privée membership?')),
                ('avant_premiere_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for the Avant-Première gift option', max_digits=10, null=True)),
                ('welcome_kit_description', models.TextField(blank=True, help_text="Description of what's included in the welcome kit", null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='vinsdelux.vdlcategory')),
                ('associated_coffret', models.ForeignKey(help_text='The base coffret that this adoption plan sells.', on_delete=django.db.models.deletion.PROTECT, related_name='adoption_plans', to='vinsdelux.vdlcoffret')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='vinsdelux.vdlproducer')),
            ],
            options={
                'verbose_name': 'Adoption Plan',
                'verbose_name_plural': 'Adoption Plans',
            },
        ),
        migrations.CreateModel(
            name='VdlProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the specific product instance.')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Description for SEO and accessibility', max_length=100)),
                ('is_feature', models.BooleanField(default=False, help_text='Set as the primary display image for the product.')),
                ('content_type', models.ForeignKey(help_text='The type of product this image is for.', limit_choices_to={'model__in': ('vdlcoffret', 'vdladoptionplan')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='VdlUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_users', to='vinsdelux.vdladdress')),
                ('default_shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_users', to='vinsdelux.vdladdress')),
            ],
        ),
    ]
