# Generated by Django 5.1 on 2025-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdladoptionplan',
            name='coffrets_per_year',
            field=models.IntegerField(default=1, help_text='Number of seasonal coffrets included per year'),
        ),
        migrations.AlterField(
            model_name='vdladoptionplan',
            name='duration_months',
            field=models.IntegerField(default=12, help_text='Duration of the adoption in months'),
        ),
    ]
