# Generated by Django 5.1 on 2025-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdladoptiontier',
            name='first_price_label',
            field=models.CharField(blank=True, help_text="Label for the first price (e.g., 'PAR COFFRET')", max_length=50),
        ),
        migrations.AddField(
            model_name='vdladoptiontier',
            name='second_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second price point for display', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vdladoptiontier',
            name='second_price_label',
            field=models.CharField(blank=True, help_text="Label for the second price (e.g., 'PAR AN')", max_length=50),
        ),
        migrations.AddField(
            model_name='vdladoptiontier',
            name='subtitle',
            field=models.CharField(blank=True, help_text="e.g., 'Château Gigognan' or 'Domaine Guillaume Baduel'", max_length=150, null=True),
        ),
    ]
