# Generated by Django 5.1 on 2025-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0002_vdladoptiontier_first_price_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdlproducer',
            name='is_featured_on_homepage',
            field=models.BooleanField(default=False, help_text='Feature this producer on the homepage?'),
        ),
    ]
