# Generated by Django 5.1 on 2025-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0003_vdlproducer_is_featured_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdlproducer',
            name='producer_photo',
            field=models.ImageField(blank=True, help_text='Photo of the producer', null=True, upload_to='producers/photos/'),
        ),
        migrations.AlterField(
            model_name='vdlproducer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='producers/logos/'),
        ),
    ]
