# Generated by Django 5.1 on 2025-06-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0003_remove_vdladoptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdlproductimage',
            name='is_feature',
        ),
    ]
