# Generated by Django 5.1 on 2025-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0004_vdlproducer_producer_photo_alter_vdlproducer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Title for the homepage hero section', max_length=200)),
                ('hero_subtitle', models.TextField(help_text='Subtitle for the homepage hero section')),
                ('hero_background_image', models.ImageField(help_text='Background image for the homepage hero section', upload_to='homepage/')),
            ],
            options={
                'verbose_name_plural': 'Homepage Content',
            },
        ),
    ]
