# Generated by Django 5.1 on 2025-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0004_remove_vdlproductimage_is_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdlproducer',
            name='elevation',
            field=models.CharField(blank=True, help_text="Vineyard elevation (e.g., '150m')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='map_x_position',
            field=models.IntegerField(default=50, help_text='X position on vineyard map (0-100%)'),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='map_y_position',
            field=models.IntegerField(default=50, help_text='Y position on vineyard map (0-100%)'),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='soil_type',
            field=models.CharField(blank=True, help_text="Predominant soil type (e.g., 'Clay-limestone')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='sun_exposure',
            field=models.CharField(blank=True, help_text="Primary sun exposure (e.g., 'South-facing')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='vineyard_features',
            field=models.JSONField(blank=True, default=list, help_text="List of vineyard features (e.g., ['Organic certification', 'Historic estate', 'Award-winning'])"),
        ),
        migrations.AddField(
            model_name='vdlproducer',
            name='vineyard_size',
            field=models.CharField(blank=True, help_text="Total vineyard size (e.g., '25 hectares')", max_length=50, null=True),
        ),
    ]
