# Generated by Django 5.1 on 2025-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0005_homepagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdlcategory',
            name='name',
            field=models.CharField(choices=[('Red Wine', 'Red Wine'), ('White Wine', 'White Wine'), ('Rosé', 'Rosé'), ('Sparkling Wine', 'Sparkling Wine'), ('Dessert Wine', 'Dessert Wine')], max_length=100),
        ),
    ]
