# Generated by Django 5.1 on 2025-08-07 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0006_add_adoption_plan_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VdlPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plot name (e.g., 'Hillside Premier')", max_length=200)),
                ('plot_identifier', models.CharField(help_text="Unique plot identifier (e.g., 'PLT-001')", max_length=50, unique=True)),
                ('coordinates', models.JSONField(default=dict, help_text="GeoJSON coordinates for plot location. Format: {'type': 'Point', 'coordinates': [longitude, latitude]}")),
                ('plot_size', models.CharField(help_text="Plot size (e.g., '0.25 hectares', '2,500 sq meters')", max_length=50)),
                ('elevation', models.CharField(blank=True, help_text="Plot elevation (e.g., '450m', '1,480 feet')", max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, help_text="Primary soil composition (e.g., 'Clay-limestone', 'Sandy loam')", max_length=100, null=True)),
                ('sun_exposure', models.CharField(blank=True, help_text="Primary sun exposure (e.g., 'South-facing', 'East-facing slopes')", max_length=50, null=True)),
                ('microclimate_notes', models.TextField(blank=True, help_text="Additional notes about the plot's microclimate", null=True)),
                ('grape_varieties', models.JSONField(default=list, help_text="List of grape varieties grown in this plot (e.g., ['Chardonnay', 'Pinot Noir'])")),
                ('vine_age', models.IntegerField(blank=True, help_text='Average age of vines in years', null=True)),
                ('harvest_year', models.IntegerField(blank=True, help_text='Expected harvest year for adoption plans', null=True)),
                ('wine_profile', models.TextField(blank=True, help_text='Expected wine characteristics from this plot', null=True)),
                ('expected_yield', models.CharField(blank=True, help_text="Expected yield (e.g., '300 bottles', '25 cases')", max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable'), ('adopted', 'Adopted')], default='available', help_text='Current availability status of the plot', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base adoption price for this plot', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Is this a premium plot with special characteristics?')),
                ('adoption_plans', models.ManyToManyField(blank=True, help_text='Adoption plans available for this plot', related_name='plots', to='vinsdelux.vdladoptionplan')),
                ('producer', models.ForeignKey(help_text='The producer/vineyard this plot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='vinsdelux.vdlproducer')),
            ],
            options={
                'verbose_name': 'Vineyard Plot',
                'verbose_name_plural': 'Vineyard Plots',
                'ordering': ['producer', 'plot_identifier'],
            },
        ),
        migrations.CreateModel(
            name='VdlPlotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this reservation expires if not converted to adoption')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Has this reservation been confirmed as an adoption?')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes or special requests', null=True)),
                ('session_data', models.JSONField(default=dict, help_text='Session data from the selection process')),
                ('adoption_plan', models.ForeignKey(blank=True, help_text='Associated adoption plan if reservation proceeds to adoption', null=True, on_delete=django.db.models.deletion.CASCADE, to='vinsdelux.vdladoptionplan')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vinsdelux.vdlplot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plot Reservation',
                'verbose_name_plural': 'Plot Reservations',
                'ordering': ['-reserved_at'],
                'unique_together': {('plot', 'user')},
            },
        ),
    ]
