# Generated by Django 5.1 on 2025-05-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0006_alter_vdlcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdlproduct',
            name='bottles_included',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='duration_months',
            field=models.IntegerField(default=12, help_text='Duration of the adoption in months'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='experience_description',
            field=models.TextField(blank=True, help_text='What does the adopter get?'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='first_price_label',
            field=models.CharField(blank=True, help_text="Label for the first price (e.g., 'PAR COFFRET')", max_length=50),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='is_adoption_product',
            field=models.BooleanField(default=False, help_text='Is this product available for adoption?'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='personalization_options',
            field=models.TextField(blank=True, help_text="e.g., 'Name on vine label, personalized certificate'"),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='second_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second price point for display', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='second_price_label',
            field=models.CharField(blank=True, help_text="Label for the second price (e.g., 'PAR AN')", max_length=50),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='subtitle',
            field=models.CharField(blank=True, help_text="e.g., 'Château Gigognan' or 'Domaine Guillaume Baduel'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='vine_location_name',
            field=models.CharField(blank=True, help_text="e.g., 'Parcel Les Champs'", max_length=100),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='visit_included',
            field=models.BooleanField(default=False, help_text='Is a vineyard visit part of this tier?'),
        ),
        migrations.DeleteModel(
            name='VdlAdoptionTier',
        ),
    ]
