# Generated by Django 5.1 on 2025-05-25 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0007_vdlproduct_bottles_included_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdlproduct',
            name='bottles_included',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='experience_description',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='first_price_label',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='is_adoption_product',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='personalization_options',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='second_price',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='second_price_label',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='vine_location_name',
        ),
        migrations.RemoveField(
            model_name='vdlproduct',
            name='visit_included',
        ),
        migrations.AlterField(
            model_name='vdlorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vinsdelux.vdlproduct'),
        ),
        migrations.CreateModel(
            name='VdlAdoptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the adoption package', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=220, unique=True)),
                ('duration_months', models.IntegerField(default=12, help_text='Duration of the adoption in months')),
                ('coffrets_per_year', models.IntegerField(default=4, help_text='Number of seasonal coffrets included per year')),
                ('bottles_per_coffret', models.IntegerField(default=2, help_text='Number of bottles included in each seasonal coffret (e.g., 1 personalized + 1 surprise)')),
                ('includes_visit', models.BooleanField(default=False, help_text='Does this package include a vineyard visit?')),
                ('visit_details', models.TextField(blank=True, help_text='Details about the vineyard visit')),
                ('includes_medallion', models.BooleanField(default=False, help_text='Does this package include a personalized medallion?')),
                ('includes_club_membership', models.BooleanField(default=False, help_text='Does this package include Club Cuvée Privée membership?')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the entire adoption package', max_digits=10)),
                ('avant_premiere_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for the Avant-Première gift option', max_digits=10, null=True)),
                ('short_description', models.TextField(help_text='Brief overview of the adoption package')),
                ('full_description', models.TextField(blank=True, help_text='Detailed description of the adoption experience', null=True)),
                ('welcome_kit_description', models.TextField(blank=True, help_text="Description of what's included in the welcome kit")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The wine product included in this package', on_delete=django.db.models.deletion.CASCADE, related_name='adoption_packages', to='vinsdelux.vdlproduct')),
            ],
        ),
        migrations.AddField(
            model_name='vdlorderitem',
            name='adoption_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vinsdelux.vdladoptionpackage'),
        ),
        migrations.CreateModel(
            name='VdlUserAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('personalization_name', models.CharField(blank=True, help_text='Name for personalization (e.g., on medallion or bottle)', max_length=100)),
                ('coffrets_sent', models.PositiveIntegerField(default=0, help_text='Number of seasonal coffrets sent so far')),
                ('visit_redeemed', models.BooleanField(default=False, help_text='Has the vineyard visit been redeemed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoption_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_adoptions', to='vinsdelux.vdladoptionpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
