# Generated by Django 5.1.4 on 2026-01-02 23:26

import crush_lu.storage
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0007_vdlplot_vdlplotreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_background_image',
            field=models.ImageField(help_text='Background image for the homepage hero section', upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('shared', 'homepage'), **{})),
        ),
        migrations.AlterField(
            model_name='vdladoptionplanimage',
            name='image',
            field=models.ImageField(help_text='Image for the adoption plan', upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'adoption_plans'), **{})),
        ),
        migrations.AlterField(
            model_name='vdlblogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'blog'), **{})),
        ),
        migrations.AlterField(
            model_name='vdlcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'categories'), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproducer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'producers/logos'), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproducer',
            name='producer_photo',
            field=models.ImageField(blank=True, help_text='Photo of the producer', null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'producers/photos'), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproductimage',
            name='image',
            field=models.ImageField(upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('vinsdelux', 'products/gallery'), **{})),
        ),
    ]
