# Generated by Django 5.1.15 on 2026-01-30 13:29

import azureproject.storage_shared
import functools
import vinsdelux.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0008_update_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_background_image',
            field=models.ImageField(help_text='Background image for the homepage hero section', storage=azureproject.storage_shared.get_shared_media_storage, upload_to=functools.partial(azureproject.storage_shared._shared_upload_path, *('homepage',), **{})),
        ),
        migrations.AlterField(
            model_name='vdladoptionplanimage',
            name='image',
            field=models.ImageField(help_text='Image for the adoption plan', storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('adoption_plans',), **{})),
        ),
        migrations.AlterField(
            model_name='vdlblogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('blog',), **{})),
        ),
        migrations.AlterField(
            model_name='vdlcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('categories',), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproducer',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('producers/logos',), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproducer',
            name='producer_photo',
            field=models.ImageField(blank=True, help_text='Photo of the producer', null=True, storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('producers/photos',), **{})),
        ),
        migrations.AlterField(
            model_name='vdlproductimage',
            name='image',
            field=models.ImageField(storage=vinsdelux.storage.get_vinsdelux_media_storage, upload_to=functools.partial(vinsdelux.storage._vinsdelux_upload_path, *('products/gallery',), **{})),
        ),
    ]
