# Generated by Django 5.1 on 2025-05-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0008_remove_vdlproduct_bottles_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdladoptionpackage',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_packages', to='vinsdelux.vdlproducer'),
        ),
    ]
