# Generated by Django 5.1 on 2025-05-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsdelux', '0009_vdladoptionpackage_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdlorderitem',
            name='adoption_package',
        ),
        migrations.RemoveField(
            model_name='vdluseradoption',
            name='adoption_package',
        ),
        migrations.RemoveField(
            model_name='vdluseradoption',
            name='user',
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='adoption_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the entire adoption package', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='avant_premiere_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the Avant-Première gift option', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='bottles_per_coffret',
            field=models.IntegerField(blank=True, help_text='Number of bottles included in each seasonal coffret (e.g., 1 personalized + 1 surprise)', null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='coffrets_per_year',
            field=models.IntegerField(blank=True, help_text='Number of seasonal coffrets included per year', null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Duration of the adoption in months', null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='includes_club_membership',
            field=models.BooleanField(default=False, help_text='Does this package include Club Cuvée Privée membership?'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='includes_medallion',
            field=models.BooleanField(default=False, help_text='Does this package include a personalized medallion?'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='includes_visit',
            field=models.BooleanField(default=False, help_text='Does this package include a vineyard visit?'),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='product_type',
            field=models.CharField(choices=[('coffret', 'Coffret'), ('adoption', 'Adoption Plan')], default='coffret', max_length=20),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='visit_details',
            field=models.TextField(blank=True, help_text='Details about the vineyard visit', null=True),
        ),
        migrations.AddField(
            model_name='vdlproduct',
            name='welcome_kit_description',
            field=models.TextField(blank=True, help_text="Description of what's included in the welcome kit", null=True),
        ),
        migrations.AlterField(
            model_name='vdlorderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vinsdelux.vdlproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vdlproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per coffret', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vdlproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Stock for standalone coffrets', null=True),
        ),
        migrations.DeleteModel(
            name='VdlAdoptionPackage',
        ),
        migrations.DeleteModel(
            name='VdlUserAdoption',
        ),
    ]
