# Generated by Django 6.0.6 on 2026-07-09 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpireState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.BigIntegerField(default=0, verbose_name="crushes")),
                (
                    "total_earned",
                    models.BigIntegerField(
                        default=0, verbose_name="total crushes earned"
                    ),
                ),
                ("hearts", models.IntegerField(default=0, verbose_name="hearts")),
                ("flags", models.IntegerField(default=0, verbose_name="red flags")),
                ("generators", models.JSONField(blank=True, default=dict)),
                ("upgrades", models.JSONField(blank=True, default=list)),
                ("safety_upgrades", models.JSONField(blank=True, default=list)),
                ("streak", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("debuff_until", models.DateTimeField(blank=True, null=True)),
                ("scam_savvy_earned_at", models.DateTimeField(blank=True, null=True)),
                ("last_tick", models.DateTimeField(default=django.utils.timezone.now)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empire_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empire save",
                "verbose_name_plural": "Empire saves",
                "ordering": ["-total_earned"],
                "indexes": [
                    models.Index(fields=["-total_earned"], name="empire_total_earned")
                ],
            },
        ),
    ]
