# Generated by Django 6.0.6 on 2026-07-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_empire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empirestate",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="empirestate",
            name="nopes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="empirestate",
            name="swipes",
            field=models.IntegerField(default=0),
        ),
    ]
