# Generated by Django 6.0.6 on 2026-07-09 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_empire", "0002_empirestate_likes_empirestate_nopes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=8)),
                ("display_name", models.CharField(max_length=40)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "is_scam",
                    models.BooleanField(
                        default=False,
                        help_text="The answer key. Never sent to the player before they answer.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Relative draw frequency within its kind."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empire profile",
                "verbose_name_plural": "Empire profiles",
                "ordering": ["is_scam", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["is_scam", "is_active"], name="empire_kind_active"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200, null=True)),
                ("text_de", models.CharField(max_length=200, null=True)),
                ("text_fr", models.CharField(max_length=200, null=True)),
                ("is_red_flag", models.BooleanField(default=False)),
                (
                    "flag_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "unverifiable_job",
                                "High-status job that can't be checked",
                            ),
                            (
                                "never_video_calls",
                                "Always has a reason not to video call",
                            ),
                            (
                                "off_platform",
                                "Wants to move to WhatsApp/Telegram immediately",
                            ),
                            ("money_request", "Asks for money, gift cards or crypto"),
                            ("love_bombing", "Declares deep feelings far too fast"),
                            ("urgency", "Manufactured emergency, needs an answer now"),
                            ("crypto", "Unsolicited investment advice"),
                            ("inconsistency", "Story contradicts itself"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "explanation",
                    models.CharField(
                        blank=True,
                        help_text="Shown after the player answers. This is the teaching.",
                        max_length=300,
                    ),
                ),
                (
                    "explanation_en",
                    models.CharField(
                        blank=True,
                        help_text="Shown after the player answers. This is the teaching.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "explanation_de",
                    models.CharField(
                        blank=True,
                        help_text="Shown after the player answers. This is the teaching.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "explanation_fr",
                    models.CharField(
                        blank=True,
                        help_text="Shown after the player answers. This is the teaching.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="crush_empire.gameprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bio segment",
                "verbose_name_plural": "Bio segments",
                "ordering": ["profile", "order"],
            },
        ),
        migrations.CreateModel(
            name="CardChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("like", "Like"),
                            ("nope", "Nope"),
                            ("report", "Report"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "Correct"),
                            ("missed", "Missed a scam"),
                            ("catfished", "Fell for a scam"),
                            ("false_report", "Reported a genuine profile"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reward_points", models.IntegerField(default=0)),
                ("reward_flags", models.IntegerField(default=0)),
                ("streak_after", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empire_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crush_empire.gameprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card challenge",
                "verbose_name_plural": "Card challenges",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "resolved_at"], name="empire_open_challenge"
                    )
                ],
            },
        ),
    ]
