# Generated by Django 6.0.6 on 2026-07-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_empire", "0003_gameprofile_biosegment_cardchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardchallenge",
            name="tapped_segments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cardchallenge",
            name="tier",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="gameprofile",
            name="tier2_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Can be dealt as a timed spot-the-red-flag puzzle. Needs at least three segments, so a flag has innocent lines to hide among. Genuine profiles must be eligible too — if only scams got the modal, the modal would give the answer away.",
            ),
        ),
        migrations.AlterField(
            model_name="cardchallenge",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("like", "Like"),
                    ("nope", "Nope"),
                    ("report", "Report"),
                    ("clear", "Cleared as genuine"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="cardchallenge",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Correct"),
                    ("partial", "Spotted some flags, missed others"),
                    ("missed", "Missed a scam"),
                    ("catfished", "Fell for a scam"),
                    ("false_report", "Reported a genuine profile"),
                    ("timeout", "Ran out of time"),
                    ("neutral", "Neutral"),
                ],
                max_length=16,
            ),
        ),
    ]
