# Generated by Django 6.0.7 on 2026-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crush_empire",
            "0004_cardchallenge_tapped_segments_cardchallenge_tier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="avatar_seed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deterministic portrait seed (usually the name). Change it to re-roll the face, then run manage.py generate_empire_avatars and commit the SVG. Blank = emoji-only card.",
                max_length=60,
            ),
        ),
    ]
