"""
Django settings for azureproject project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.178.184', 'crush.lu', 'www.crush.lu', 'delegation.crush.lu', 'powerup.local']

if 'CODESPACE_NAME' in os.environ:
    CSRF_TRUSTED_ORIGINS = [f'https://{os.getenv("CODESPACE_NAME")}-8000.{os.getenv("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")}']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',  # SEO: Dynamic sitemap generation
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.microsoft',
    'entreprinder',  # Includes merged: matching, finops, vibe_coding
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'vinsdelux',
    'crush_lu',
    'crush_delegation',
]

# SITE_ID must NOT be set - CurrentSiteMiddleware determines site dynamically per request
# Setting SITE_ID would force all domains to use the same Site object

MIDDLEWARE = [
    'azureproject.middleware.HealthCheckMiddleware',  # MUST be first - bypasses all other middleware for /healthz/
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',  # MUST be before SafeCurrentSiteMiddleware
    'azureproject.middleware.SafeCurrentSiteMiddleware',  # Safe site detection (auto-creates missing Sites)
    'azureproject.middleware.DomainURLRoutingMiddleware',  # Multi-domain routing
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Changed from cache to db for PWA persistence
ROOT_URLCONF = 'azureproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Ensure this line is present
                'crush_lu.context_processors.crush_user_context',  # Crush.lu user context
            ],
            # 'builtins': [ # Simplify builtins to only include allauth account tags
            #     'allauth.account.templatetags.account',
            # ],
        },
    },
]



WSGI_APPLICATION = 'azureproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# To use sqllite as the database engine,
#   uncomment the following block and comment out the Postgres section below

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Configure Postgres database for local development
#   Set these environment variables in the .env file for this project.
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.environ.get('DBNAME'),
#        'HOST': os.environ.get('DBHOST'),
#        'USER': os.environ.get('DBUSER'),
#        'PASSWORD': os.environ.get('DBPASS'),
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# In settings.py

# These settings optimize the login experience
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_AUTO_SIGNUP = True


# Session Configuration for PWA
SESSION_COOKIE_AGE = 1209600  # 14 days (2 weeks) - longer session for PWA
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on each request
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JavaScript access
SESSION_COOKIE_SECURE = False  # Set to True in production (HTTPS only)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection while allowing navigation
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session alive after browser close (critical for PWA)
SESSION_REMEMBER_ME = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# AllAuth settings
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Changed from mandatory
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True

LOGIN_REDIRECT_URL = '/profile/'

SOCIALACCOUNT_LOGIN_ON_GET = True

# Don't send email verification for social account signups (email already verified by provider)
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Social account provider settings
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],  # Only basic permissions (no app review needed)
        'AUTH_PARAMS': {'auth_type': 'rerequest'},  # Smoother UX - only re-prompt for declined permissions
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'picture',
            # Note: birthday, gender, location require Facebook App Review
            # See: https://developers.facebook.com/docs/facebook-login/permissions
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v24.0',
    },
    'microsoft': {
        # 'common' allows any Microsoft account (personal + work/school from any org)
        # Use 'organizations' to restrict to work/school accounts only
        # Use specific tenant ID to restrict to single organization
        'TENANT': 'common',
        'SCOPE': ['User.Read', 'profile', 'email', 'openid'],
    },
}


# Use CustomSignupForm for Entreprinder (will be overridden by adapters for other domains)
ACCOUNT_FORMS = {'signup': 'entreprinder.forms.CustomSignupForm'}

# Specify where to redirect after successful sign-up
ACCOUNT_SIGNUP_REDIRECT_URL = '/profile/'  # Redirect to profile page after signup

# Allauth adapters - Multi-domain aware
SOCIALACCOUNT_ADAPTER = 'azureproject.adapters.MultiDomainSocialAccountAdapter'
ACCOUNT_ADAPTER = 'azureproject.adapters.MultiDomainAccountAdapter'

# Email backend Configuration (using SMTP)
# NOTE: For domain-specific email configuration (crush.lu, vinsdelux.com, etc.),
# use the send_domain_email() function from azureproject.email_utils
# The send_domain_email() automatically uses console backend in DEBUG mode
# This default configuration is used for powerup.lu and as fallback
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.power-up.lu')  # SMTP server address
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))          # SMTP port (465 for SSL)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')          # Your SMTP username (e.g., info@power-up.lu)
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Your SMTP password or App Password
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true' # Use SSL since port is 465
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true' # Use TLS if port was 587

# Default email address for outgoing mail
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@powerup.lu')

# Domain-specific email configurations
# Crush.lu uses Microsoft Graph API (SMTP disabled by M365)
#   Set CRUSH_GRAPH_TENANT_ID, CRUSH_GRAPH_CLIENT_ID, CRUSH_GRAPH_CLIENT_SECRET
# VinsDelux can use VINSDELUX_EMAIL_* variables for custom configuration
# See azureproject/email_utils.py for implementation

CORS_ALLOWED_ORIGINS = [
]



ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

#CACHES = {
#        "default": {  
#            "BACKEND": "django_redis.cache.RedisCache",
#            "LOCATION": os.environ.get('CACHELOCATION'),
#            "OPTIONS": {
#                "CLIENT_CLASS": "django_redis.client.DefaultClient",
#        },
#    }
#}

# Internationalization

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'en'

# Luxembourg timezone (CET/CEST - UTC+1/UTC+2 with automatic DST handling)
TIME_ZONE = 'Europe/Luxembourg'

USE_I18N = True

# Use localization
USE_L10N = True

LANGUAGES = [
    ('en', _('English')),
    ('de', _('German')),
    ('fr', _('French')),
]

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Azure Blob Storage Settings (Conditional for Development)
if os.getenv('AZURE_ACCOUNT_NAME'):
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
    AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
    AZURE_CONTAINER_NAME = os.getenv('AZURE_CONTAINER_NAME')
    MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER_NAME}/'
    print("Using Azure Blob Storage for media files.")
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    # Ensure media directory exists
    if not os.path.exists(MEDIA_ROOT):
        os.makedirs(MEDIA_ROOT)
        if os.environ.get('RUN_MAIN'):  # Only print in main process
            print(f"Created media directory at: {MEDIA_ROOT}")
    elif os.environ.get('RUN_MAIN'):  # Only print in main process
        print(f"Media directory already exists at: {MEDIA_ROOT}")

    if os.environ.get('RUN_MAIN'):  # Only print in main process
        print("Using local file system for media files.")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Cookie Settings (required for JavaScript AJAX requests)
# Allow JavaScript to read the CSRF cookie for fetch/XMLHttpRequest
CSRF_COOKIE_HTTPONLY = False
