"""
Event check-in API endpoint.

Handles QR code scans from coaches at event entrances. The QR code contains
a signed URL with the registration ID and token. When scanned, this endpoint
verifies the token and marks the registration as attended.
"""

import logging

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.signing import BadSignature, Signer
from django.db import transaction
from django.http import JsonResponse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .decorators import coach_required
from .models import EventRegistration

logger = logging.getLogger(__name__)


@csrf_exempt
@require_POST
def event_checkin_api(request, registration_id, token):
    """
    Check in an attendee via signed QR code token.

    The token is generated by Django's Signer and encodes
    "{registration_id}:{event_id}". This endpoint:

    1. Verifies the signed token
    2. Validates registration exists and is confirmed
    3. Checks the event is within the check-in window (default: 12 hours)
    4. Marks registration as attended with checked_in_at timestamp
    5. Returns JSON with attendee name and success status
    """
    # Verify token
    signer = Signer()
    try:
        unsigned = signer.unsign(token)
    except BadSignature:
        logger.warning("Invalid check-in token for registration %s", registration_id)
        return JsonResponse(
            {"success": False, "error": "Invalid or expired check-in token."},
            status=400,
        )

    # Parse token payload
    try:
        token_reg_id, token_event_id = unsigned.split(":")
        token_reg_id = int(token_reg_id)
        token_event_id = int(token_event_id)
    except (ValueError, AttributeError):
        return JsonResponse(
            {"success": False, "error": "Malformed check-in token."},
            status=400,
        )

    # Verify token matches URL
    if token_reg_id != registration_id:
        return JsonResponse(
            {"success": False, "error": "Token does not match registration."},
            status=400,
        )

    # Fetch registration
    try:
        registration = EventRegistration.objects.select_related(
            "event", "user", "user__crushprofile"
        ).get(id=registration_id)
    except EventRegistration.DoesNotExist:
        return JsonResponse(
            {"success": False, "error": "Registration not found."},
            status=404,
        )

    # Verify event ID matches
    if registration.event_id != token_event_id:
        return JsonResponse(
            {"success": False, "error": "Token does not match event."},
            status=400,
        )

    # Check if already attended
    if registration.status == "attended":
        display_name = _get_display_name(registration)
        response_data = {
            "success": True,
            "already_checked_in": True,
            "registration_id": registration.id,
            "attendee_name": display_name,
            "checked_in_at": (
                registration.checked_in_at.isoformat()
                if registration.checked_in_at
                else None
            ),
            "message": f"{display_name} was already checked in.",
            "profile": _get_profile_data(registration),
        }
        table_info = _get_existing_table_assignment(registration)
        if table_info:
            response_data.update(table_info)
        return JsonResponse(response_data)

    # Verify status is confirmed
    if registration.status != "confirmed":
        return JsonResponse(
            {
                "success": False,
                "error": f"Registration status is '{registration.get_status_display()}'. Only confirmed registrations can be checked in.",
            },
            status=400,
        )

    # Check event is within check-in window
    checkin_window_hours = getattr(settings, "EVENT_CHECKIN_WINDOW_HOURS", 12)
    now = timezone.now()
    event_start = registration.event.date_time
    from datetime import timedelta

    window_start = event_start - timedelta(hours=checkin_window_hours)
    window_end = event_start + timedelta(hours=checkin_window_hours)

    if not (window_start <= now <= window_end):
        return JsonResponse(
            {
                "success": False,
                "error": f"Check-in is only available within {checkin_window_hours} hours of the event.",
            },
            status=400,
        )

    # Mark as attended (with lock to prevent duplicate concurrent check-ins)
    table_assignment = None
    with transaction.atomic():
        registration = (
            EventRegistration.objects.select_for_update()
            .select_related("event", "user")
            .get(id=registration_id)
        )
        if registration.status == "attended":
            display_name = _get_display_name(registration)
            response_data = {
                "success": True,
                "already_checked_in": True,
                "registration_id": registration.id,
                "attendee_name": display_name,
                "checked_in_at": (
                    registration.checked_in_at.isoformat()
                    if registration.checked_in_at
                    else None
                ),
                "message": f"{display_name} was already checked in.",
                "profile": _get_profile_data(registration),
            }
            table_info = _get_existing_table_assignment(registration)
            if table_info:
                response_data.update(table_info)
            return JsonResponse(response_data)
        registration.status = "attended"
        registration.checked_in_at = now
        registration.save(update_fields=["status", "checked_in_at", "updated_at"])

        # Quiz table assignment (if this is a quiz night event)
        try:
            quiz_event = getattr(registration.event, "quiz", None)
            if quiz_event and quiz_event.num_tables:
                from .services.quiz_rotation import assign_table_on_checkin

                table_assignment = assign_table_on_checkin(
                    quiz_event, registration.user
                )
        except Exception:
            logger.exception(
                "Quiz table assignment failed for registration %s",
                registration.id,
            )

    display_name = _get_display_name(registration)

    logger.info(
        "Checked in registration %s (user %s) for event %s",
        registration.id,
        registration.user_id,
        registration.event_id,
    )

    response_data = {
        "success": True,
        "already_checked_in": False,
        "registration_id": registration.id,
        "attendee_name": display_name,
        "checked_in_at": now.isoformat(),
        "message": f"{display_name} has been checked in!",
        "profile": _get_profile_data(registration),
    }
    if table_assignment:
        response_data["table_number"] = table_assignment["table_number"]
        response_data["role"] = table_assignment["role"]

    _broadcast_checkin(registration.event_id, response_data)

    # Notify quiz participants about the new tablemate
    if table_assignment:
        _broadcast_quiz_table_update(registration.event, table_assignment)

    return JsonResponse(response_data)


@coach_required
@require_POST
def coach_mark_verified(request, event_id, registration_id):
    """Verify an attendee in person at an event (Option 2 / premium Option 3).

    A coach running the event can flip an unverified attendee to ``verified``.
    For ordinary walk-ins any active coach may do this (method ``coach_event``).
    For a premium member (one with an ``assigned_coach``) only that assigned
    coach may verify them, and the method is recorded as ``premium_coach``.
    """
    from .models import ProfileSubmission

    coach = request.coach
    now = timezone.now()

    with transaction.atomic():
        # Lock only the registration row — crushprofile is the nullable side of
        # an outer join, which PostgreSQL refuses to lock under FOR UPDATE.
        registration = (
            EventRegistration.objects.select_for_update(of=("self",))
            .select_related("user", "event")
            .filter(id=registration_id, event_id=event_id)
            .first()
        )
        if registration is None:
            return JsonResponse(
                {"success": False, "error": str(_("Registration not found."))},
                status=404,
            )
        if registration.status not in ("confirmed", "attended"):
            return JsonResponse(
                {
                    "success": False,
                    "error": str(
                        _("Only confirmed or checked-in attendees can be verified.")
                    ),
                },
                status=400,
            )

        try:
            profile = registration.user.crushprofile
        except Exception:
            return JsonResponse(
                {"success": False, "error": str(_("Attendee has no profile."))},
                status=404,
            )

        # Premium members may only be verified by their own assigned coach.
        if profile.assigned_coach_id:
            if profile.assigned_coach_id != coach.id:
                return JsonResponse(
                    {
                        "success": False,
                        "error": str(
                            _("This premium member is verified by their own coach.")
                        ),
                    },
                    status=403,
                )
            method = "premium_coach"
        else:
            method = "coach_event"

        if profile.verification_status == "verified":
            return JsonResponse(
                {
                    "success": True,
                    "already_verified": True,
                    "registration_id": registration.id,
                    "attendee_name": _get_display_name(registration),
                    "verification_method": profile.verification_method,
                    "message": str(_("Already verified.")),
                }
            )

        profile.is_approved = True
        profile.approved_at = now
        profile.verification_status = "verified"
        profile.verification_method = method
        profile.save(
            update_fields=[
                "is_approved",
                "approved_at",
                "verification_status",
                "verification_method",
            ]
        )

        submission = (
            ProfileSubmission.objects.filter(profile=profile, status="pending")
            .order_by("-submitted_at")
            .first()
        )
        if submission:
            submission.status = "approved"
            submission.reviewed_at = now
            submission.review_call_completed = True
            if not submission.coach_id:
                submission.coach = coach
            submission.coach_notes = (
                (submission.coach_notes + "\n" if submission.coach_notes else "")
                + "Verified in person at event by coach"
            ).strip()
            submission.save(
                update_fields=[
                    "status",
                    "reviewed_at",
                    "coach_notes",
                    "review_call_completed",
                    "coach",
                ]
            )

    logger.info(
        "Coach %s verified registration %s (user %s) at event %s via %s",
        coach,
        registration.id,
        registration.user_id,
        event_id,
        method,
    )

    response_data = {
        "success": True,
        "already_verified": False,
        "registration_id": registration.id,
        "attendee_name": _get_display_name(registration),
        "verification_method": method,
        "message": str(_("%(name)s is now verified."))
        % {"name": _get_display_name(registration)},
        "profile": _get_profile_data(registration),
    }
    _broadcast_checkin(registration.event_id, response_data)
    return JsonResponse(response_data)


def _get_display_name(registration):
    """Get privacy-aware display name for attendee."""
    try:
        return registration.user.crushprofile.display_name
    except Exception:
        return _("Attendee")


def _get_profile_data(registration):
    """Build privacy-aware profile card data for check-in toast."""
    from .models import ProfileSubmission

    try:
        profile = registration.user.crushprofile
    except Exception:
        return {}
    data = {
        "display_name": profile.display_name,
        "gender": profile.gender or "",
        "age_display": profile.age_display,
        "is_approved": profile.is_approved,
        "user_id": registration.user_id,
        "location": profile.location or "",
        "interests": profile.interests or "",
    }
    if profile.photo_1:
        data["photo_url"] = reverse(
            "crush_lu:serve_profile_photo",
            kwargs={"user_id": registration.user_id, "photo_field": "photo_1"},
        )

    # Include coach info for unverified profiles
    if not profile.is_approved:
        latest_submission = (
            ProfileSubmission.objects.filter(profile=profile)
            .select_related("coach__user")
            .order_by("-submitted_at")
            .first()
        )
        if latest_submission:
            data["submission_status"] = latest_submission.get_status_display()
            if latest_submission.coach:
                data["coach_name"] = (
                    f"{latest_submission.coach.user.first_name} {latest_submission.coach.user.last_name}".strip()
                )

    return data


def _broadcast_checkin(event_id, response_data):
    """Broadcast check-in update to WebSocket group for live coach updates."""
    channel_layer = get_channel_layer()
    if channel_layer:
        async_to_sync(channel_layer.group_send)(
            f"checkin_{event_id}",
            {"type": "checkin.update", "data": response_data},
        )


def _broadcast_quiz_table_update(event, table_assignment):
    """Notify quiz participants at a table that a new person has joined."""
    from .models.quiz import QuizTable

    channel_layer = get_channel_layer()
    if not channel_layer:
        return
    try:
        quiz_event = getattr(event, "quiz", None)
        if not quiz_event:
            return
        table_number = table_assignment.get("table_number")
        if not table_number:
            return
        # Look up the QuizTable PK — the consumer subscribes using table PK, not table_number
        quiz_table = QuizTable.objects.filter(
            quiz=quiz_event, table_number=table_number
        ).first()
        if not quiz_table:
            return
        # Broadcast to the specific table group so only affected participants refresh
        async_to_sync(channel_layer.group_send)(
            f"quiz_{quiz_event.id}_table_{quiz_table.id}",
            {
                "type": "quiz.table_update",
                "data": {"table_number": table_number},
            },
        )
        # Also broadcast to display-specific group so the projector page updates
        async_to_sync(channel_layer.group_send)(
            f"quiz_{quiz_event.id}_display",
            {
                "type": "quiz.table_update",
                "data": {"table_number": table_number},
            },
        )
    except Exception:
        logger.exception("Failed to broadcast quiz table update for event %s", event.id)


def _get_existing_table_assignment(registration):
    """Look up existing quiz table assignment for a registration.

    Returns dict with table_number and role, or None.
    """
    try:
        quiz_event = getattr(registration.event, "quiz", None)
        if not quiz_event:
            return None
        from .models.quiz import QuizRotationSchedule, QuizTableMembership

        membership = (
            QuizTableMembership.objects.filter(
                table__quiz=quiz_event, user=registration.user
            )
            .select_related("table")
            .first()
        )
        if not membership:
            return None
        rotation = QuizRotationSchedule.objects.filter(
            quiz=quiz_event, round_number=0, user=registration.user
        ).first()
        return {
            "table_number": membership.table.table_number,
            "role": rotation.role if rotation else "",
        }
    except Exception:
        return None
