# Generated by Django 5.1 on 2025-10-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finops_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costrecord',
            name='record_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
