# Generated by Django 5.1.4 on 2025-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finops_hub', '0004_add_blob_change_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costexport',
            name='blob_etag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costexport',
            name='blob_last_modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
