# Generated by Django 6.0.7 on 2026-07-17 17:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crush_lu", "0183_cachestation_manual_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLobbyConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "acknowledged_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_lobby_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLobbyParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opaque_handle",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "eligibility_source",
                    models.CharField(
                        choices=[
                            ("checkin", "Check-in"),
                            ("onboarding_completed", "Onboarding completed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_participations",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "event_registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_lobby_participation",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_lobby_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "joined_at"], name="lobby_event_joined_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="event_lobby_unique_participant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventMeetSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mutual_revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meet_signals",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meet_signals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meet_signals_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "sender"], name="lobby_signal_sender_idx"
                    ),
                    models.Index(
                        fields=["event", "recipient"], name="lobby_signal_recipient_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "sender", "recipient"),
                        name="event_lobby_unique_signal",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")), _negated=True
                        ),
                        name="event_lobby_signal_no_self",
                    ),
                ],
            },
        ),
    ]
