# Generated by Django 6.0.7 on 2026-07-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_event_lobby", "0001_initial"),
        ("crush_lu", "0183_cachestation_manual_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRecapNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_notification_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reminder_notification_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recap_notice",
                        to="crush_event_lobby.eventlobbyparticipation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmedEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removal_pending", "Removal pending"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_from_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_encounters",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "user_high",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_encounters_as_high",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_low",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_encounters_as_low",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_low", "user_high"),
                        name="event_lobby_unique_encounter_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("user_low__lt", models.F("user_high"))),
                        name="event_lobby_encounter_canonical_pair",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventMeetingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meeting_confirmations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meeting_confirmations",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "other_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_meeting_confirmations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "confirmer"], name="lobby_confirm_sender_idx"
                    ),
                    models.Index(
                        fields=["event", "other_user"], name="lobby_confirm_recv_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "confirmer", "other_user"),
                        name="event_lobby_unique_confirmation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confirmer", models.F("other_user")), _negated=True
                        ),
                        name="event_lobby_confirmation_no_self",
                    ),
                ],
            },
        ),
    ]
