# Generated by Django 6.0.7 on 2026-07-17 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_event_lobby", "0003_confirmedencounter_opaque_handle"),
        ("crush_lu", "0183_cachestation_manual_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmedEncounterRemovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("safety", "I feel unsafe or uncomfortable"),
                            ("privacy", "Privacy concern"),
                            ("mistaken_identity", "We did not actually meet"),
                            (
                                "no_longer_visible",
                                "I no longer want this person visible",
                            ),
                            ("other", "Another reason"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Removal approved"),
                            ("kept_hidden", "Resolved and kept hidden"),
                            ("restored", "Visibility explicitly restored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, max_length=1000)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removal_requests",
                        to="crush_event_lobby.confirmedencounter",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_encounter_removal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_encounter_removals",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "reviewed_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_reviewed_encounter_removals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("encounter",),
                        name="event_lobby_one_pending_removal",
                    )
                ],
            },
        ),
    ]
