# Generated by Django 6.0.7 on 2026-08-16 12:58

import django.db.models.deletion
import functools
import power_up.storage
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="The rolled noir persona. The delivery key.",
                        max_length=32,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("settled", "Settled"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "menu categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                (
                    "qr_token",
                    models.CharField(db_index=True, max_length=22, unique=True),
                ),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "service_open",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch — off means no ordering anywhere.",
                    ),
                ),
                (
                    "guest_window_minutes",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Reserved for the window mechanic (not yet enforced).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=power_up.storage.get_powerup_media_storage,
                        upload_to=functools.partial(
                            power_up.storage._powerup_upload_path, "atmos/menu"
                        ),
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, help_text="The 86-button."),
                ),
                ("contains_alcohol", models.BooleanField(default=False)),
                ("allergens", models.CharField(blank=True, default="", max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="atmos.menucategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("short_code", models.CharField(db_index=True, max_length=8)),
                ("alias_snapshot", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("accepted", "Accepted"),
                            ("preparing", "Preparing"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="placed",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                ("vignette", models.TextField(blank=True, default="")),
                (
                    "vignette_source",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="atmos.guest",
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="atmos.tab",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="atmos.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_snapshot", models.CharField(max_length=160)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("note", models.CharField(blank=True, default="", max_length=160)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="atmos.menuitem"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="atmos.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guest",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="atmos.tab",
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="atmos.table",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="atmos.venue",
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="atmos.venue",
            ),
        ),
        migrations.AddField(
            model_name="menucategory",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="atmos.venue",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="atmos.venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("venue", "label"), name="uniq_table_label_per_venue"
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("table",),
                name="uniq_open_tab_per_table",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["venue", "status", "placed_at"],
                name="atmos_order_venue_i_95bea7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("venue", "alias"),
                name="uniq_active_alias_per_venue",
            ),
        ),
    ]
