# Generated by Django 6.0.7 on 2026-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atmos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="short_code",
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
