# Generated by Django 6.0.7 on 2026-08-16 22:38

import re

from django.db import migrations, models

# Matches the trailing "-<digits>" order_number suffix that views.py's
# `f"T{table.label[:3].upper()}-{order_number:02d}"` always produces.
_SHORT_CODE_SUFFIX_RE = re.compile(r"-(\d+)$")


def _backfill(apps, schema_editor):
    """Both new fields default to a value that's wrong for any row that
    already existed before this migration — backfill them from what's
    actually on disk rather than leaving pre-existing demo/seed orders with
    a false `contains_alcohol_snapshot=False` or a `next_order_number` that
    would immediately collide with orders already placed.
    """
    OrderItem = apps.get_model("atmos", "OrderItem")
    for item in OrderItem.objects.select_related("menu_item").filter(
        contains_alcohol_snapshot=False, menu_item__contains_alcohol=True
    ):
        item.contains_alcohol_snapshot = True
        item.save(update_fields=["contains_alcohol_snapshot"])

    Venue = apps.get_model("atmos", "Venue")
    Order = apps.get_model("atmos", "Order")
    # Deliberately NOT Order.objects.values("venue").annotate(Count("id"))
    # + 1 — that undercounts the moment any order has ever been deleted
    # (OrderAdmin permits deletion), producing a next_order_number that
    # collides with a still-existing order's short_code the moment the
    # next one is placed after this migration runs: the exact bug this
    # field exists to prevent, reintroduced at the schema-upgrade boundary
    # meant to fix it. Parse the highest order_number actually embedded in
    # each venue's surviving short_codes instead — that value only ever
    # reflects orders that still exist, so a deletion can't corrupt it.
    max_numbers = {}
    for venue_id, short_code in Order.objects.values_list("venue_id", "short_code"):
        match = _SHORT_CODE_SUFFIX_RE.search(short_code or "")
        if not match:
            continue
        number = int(match.group(1))
        if number > max_numbers.get(venue_id, 0):
            max_numbers[venue_id] = number

    for venue in Venue.objects.all():
        next_number = max_numbers.get(venue.id, 0) + 1
        if venue.next_order_number != next_number:
            venue.next_order_number = next_number
            venue.save(update_fields=["next_order_number"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atmos", "0002_alter_order_short_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="contains_alcohol_snapshot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="next_order_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(_backfill, _noop_reverse),
    ]
