# Generated by Django 6.0.7 on 2026-08-16 22:38

from django.db import migrations, models
from django.db.models import Count


def _backfill(apps, schema_editor):
    """Both new fields default to a value that's wrong for any row that
    already existed before this migration — backfill them from what's
    actually on disk rather than leaving pre-existing demo/seed orders with
    a false `contains_alcohol_snapshot=False` or a `next_order_number` that
    would immediately collide with orders already placed.
    """
    OrderItem = apps.get_model("atmos", "OrderItem")
    for item in OrderItem.objects.select_related("menu_item").filter(
        contains_alcohol_snapshot=False, menu_item__contains_alcohol=True
    ):
        item.contains_alcohol_snapshot = True
        item.save(update_fields=["contains_alcohol_snapshot"])

    Venue = apps.get_model("atmos", "Venue")
    Order = apps.get_model("atmos", "Order")
    counts = {
        row["venue"]: row["n"]
        for row in Order.objects.values("venue").annotate(n=Count("id"))
    }
    for venue in Venue.objects.all():
        next_number = counts.get(venue.id, 0) + 1
        if venue.next_order_number != next_number:
            venue.next_order_number = next_number
            venue.save(update_fields=["next_order_number"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("atmos", "0002_alter_order_short_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="contains_alcohol_snapshot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="next_order_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(_backfill, _noop_reverse),
    ]
