import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class PaymentTransaction(models.Model):
    """
    Tracks payment transactions initiated via payment providers (SumUp).
    Links payment checkouts to EventRegistration or PremiumMembership models.
    """

    class Provider(models.TextChoices):
        SUMUP = "sumup", _("SumUp")
        # Crush Credit is a payment *method*, not a payment provider — no money
        # moves and no checkout exists at anybody's API. It lives here because
        # this field is what every reader uses to decide how a payment was
        # made, and because keeping credit payments out of the SumUp value is
        # what stops `sumup_checkout_status` and the reconciliation sweep
        # hunting for a checkout that was never opened. A CREDIT row carries an
        # empty `sumup_checkout_id` for the same reason.
        CREDIT = "credit", _("Crush Credit")

    class Status(models.TextChoices):
        PENDING = "pending", _("Pending")
        PAID = "paid", _("Paid")
        FAILED = "failed", _("Failed")
        CANCELLED = "cancelled", _("Cancelled")
        REFUNDED = "refunded", _("Refunded")

    class Purpose(models.TextChoices):
        EVENT_REGISTRATION = "event_registration", _("Event Registration")
        PREMIUM_MEMBERSHIP = "premium_membership", _("Premium Membership")
        DONATION = "donation", _("Donation / Support")

    transaction_reference = models.CharField(
        max_length=64,
        unique=True,
        default=uuid.uuid4,
        help_text=_("Unique internal reference ID for this payment transaction"),
    )
    provider = models.CharField(
        max_length=20,
        choices=Provider.choices,
        default=Provider.SUMUP,
    )
    sumup_checkout_id = models.CharField(
        max_length=100,
        blank=True,
        db_index=True,
        help_text=_("Checkout ID generated by SumUp API"),
    )
    sumup_customer_id = models.CharField(
        max_length=100,
        blank=True,
        help_text=_("Customer ID generated by SumUp API for tokenization"),
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text=_("Payment amount in specified currency"),
    )
    currency = models.CharField(
        max_length=3,
        default="EUR",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )
    purpose = models.CharField(
        max_length=30,
        choices=Purpose.choices,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        # A captured payment is a financial record. Do not let a hard User
        # delete erase it; profile-only deletion/anonymisation is the supported
        # member flow.
        on_delete=models.PROTECT,
        related_name="payment_transactions",
        null=True,
        blank=True,
    )
    event_registration = models.ForeignKey(
        "crush_lu.EventRegistration",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="payment_transactions",
    )
    premium_membership = models.ForeignKey(
        "crush_lu.PremiumMembership",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="payment_transactions",
    )
    raw_response = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Raw JSON response / webhook payload from payment provider"),
    )
    failure_reason = models.TextField(
        blank=True,
        default="",
        help_text=_(
            "Why this payment did not complete, in words. The provider's own "
            "wording where it gives one."
        ),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _("Payment Transaction")
        verbose_name_plural = _("Payment Transactions")

    def __str__(self):
        return f"{self.provider.upper()} {self.transaction_reference} - {self.amount} {self.currency} ({self.get_status_display()})"
