# Generated by Django 6.0.8 on 2026-09-14 19:49

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArboristBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Booking Reference",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="Street Address"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                (
                    "city_or_commune",
                    models.CharField(max_length=100, verbose_name="City / Commune"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("obstbaumpflege", "Fruit Tree Care (Obstbaumpflege)"),
                            ("baumpflege", "Tree Care & Pruning (Baumpflege)"),
                            (
                                "baumkontrolle",
                                "Tree Inspection according to FLL (Baumkontrolle)",
                            ),
                            ("faellung", "Tree Felling / Removal (Baumfällung)"),
                            (
                                "oekologie",
                                "Ecological Measures (Ökologische Maßnahmen)",
                            ),
                            (
                                "notdienst",
                                "Emergency & Storm Damage (Notdienst & Sturmschaden)",
                            ),
                            ("beratung", "General Consultation (Beratung)"),
                        ],
                        default="baumpflege",
                        max_length=30,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "number_of_trees",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 1-2 trees, orchard, group of mature trees",
                        max_length=50,
                        verbose_name="Number of Trees",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Details regarding tree species, height, condition, or access situation.",
                        verbose_name="Project Description / Details",
                    ),
                ),
                (
                    "is_rush",
                    models.BooleanField(
                        default=False,
                        help_text="Urgent intervention needed within 24-48 hours.",
                        verbose_name="Rush Order (Emergency 24-48h)",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Preferred Date"
                    ),
                ),
                (
                    "preferred_time_slot",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible / Any time"),
                            ("morning", "Morning (08:00 - 12:00)"),
                            ("afternoon", "Afternoon (12:00 - 17:00)"),
                        ],
                        default="flexible",
                        max_length=20,
                        verbose_name="Preferred Time Slot",
                    ),
                ),
                (
                    "zone",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Zone 1 - Local (50 €)"),
                            (2, "Zone 2 - Wider Luxembourg (100 €)"),
                        ],
                        default=1,
                        verbose_name="Distance Zone",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Distance from Altrier (km)",
                    ),
                ),
                (
                    "prepayment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        max_digits=6,
                        verbose_name="Prepayment Amount (€)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Prepayment Pending"),
                            ("paid", "Prepayment Paid"),
                            ("credited", "Credited to Final Invoice"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Internal Admin Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Arborist Booking",
                "verbose_name_plural": "Arborist Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
