# Generated by Django 6.0.8 on 2026-09-21 17:10

import arborist.models_leads
import arborist.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arborist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArboristLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Postal code"
                    ),
                ),
                (
                    "service",
                    models.CharField(blank=True, max_length=30, verbose_name="Service"),
                ),
                (
                    "message",
                    models.TextField(max_length=5000, verbose_name="Your Message"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Urgent situation"),
                ),
                ("language", models.CharField(default="en", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New enquiry"),
                            ("review", "Under review"),
                            ("waiting", "Waiting for customer"),
                            ("qualified", "Qualified"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "next_action",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Next action"
                    ),
                ),
                (
                    "follow_up_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Follow up at",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Internal review notes"),
                ),
                (
                    "photo_notes",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Missing photos / access notes",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="website", max_length=30, verbose_name="Source"
                    ),
                ),
                ("first_attribution", models.JSONField(blank=True, default=dict)),
                ("last_attribution", models.JSONField(blank=True, default=dict)),
                (
                    "staff_delivery",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed — retry available"),
                            ("skipped", "No email supplied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "customer_delivery",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed — retry available"),
                            ("skipped", "No email supplied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "notification_attempted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arborist_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Arborist enquiry",
                "verbose_name_plural": "Arborist enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="arboristbooking",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="arborist.arboristlead",
                verbose_name="Enquiry",
            ),
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="arborist.arboristlead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("upload_id", models.UUIDField(editable=False, unique=True)),
                (
                    "tree_label",
                    models.CharField(
                        default="1", max_length=50, verbose_name="Tree label"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("root", "Trunk–ground junction"),
                            ("whole", "Whole tree and surroundings"),
                            ("leaf", "Leaves and twig"),
                            ("symptom", "Visible symptoms"),
                        ],
                        max_length=10,
                        verbose_name="Photo category",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=arborist.storage.private_storage,
                        upload_to=arborist.models_leads.lead_photo_path,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="arborist.arboristlead",
                    ),
                ),
            ],
        ),
    ]
