# Generated by Django 5.1.15 on 2026-01-30 10:29
# State-only migration: Remove models from power_up state without dropping tables

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_up', '0002_ensure_finops_tables_exist'),
    ]

    # Use SeparateDatabaseAndState to remove models from migration state
    # without dropping the actual tables (they're managed by finops app now)
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CostAggregation',
                ),
                migrations.RemoveField(
                    model_name='costrecord',
                    name='cost_export',
                ),
                migrations.DeleteModel(
                    name='CostExport',
                ),
                migrations.DeleteModel(
                    name='CostRecord',
                ),
            ],
            # No database operations - tables remain for finops app
            database_operations=[],
        ),
    ]
