# Generated by Django 5.1.15 on 2026-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_up', '0002_ensure_finops_tables_exist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostAggregation',
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='cost_export',
        ),
        migrations.DeleteModel(
            name='CostExport',
        ),
        migrations.DeleteModel(
            name='CostRecord',
        ),
    ]
