# Generated by Django 5.1.15 on 2026-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="includes_crit_sit",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="includes_engage",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="quota_period",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="ticket_quota",
        ),
        migrations.AddField(
            model_name="plan",
            name="crit_sit_management",
            field=models.BooleanField(
                default=False, verbose_name="Critical Situation Management"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_authorized_contacts",
            field=models.PositiveIntegerField(
                default=2, help_text="Maximum number of authorized contacts allowed"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_tenants",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum number of tenants allowed on this plan"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="products_covered",
            field=models.TextField(
                default="",
                help_text="Products covered by this plan (e.g. Azure, M365, D365, On-prem)",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="severity_levels",
            field=models.CharField(
                default="B, C",
                help_text="Supported severity levels (e.g. 'B, C' or 'A, B, C')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="support_channels",
            field=models.CharField(
                default="Email",
                help_text="Available support channels (e.g. 'Email' or 'Dedicated phone number or Email')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="support_hours",
            field=models.CharField(
                default="8x5",
                help_text="Support availability (e.g. '8x5' or '24x7x365')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="support_provider",
            field=models.CharField(default="Microsoft Premier Support", max_length=100),
        ),
        migrations.AddField(
            model_name="plan",
            name="support_requests_per_year",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Support requests per trailing 12-month period (0 = Pay As You Go)",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                ],
                default="bronze",
                max_length=20,
            ),
        ),
    ]
