# Generated by Django 5.1.15 on 2026-02-11 18:46

from django.db import migrations

PLANS = [
    {
        "name": "Bronze",
        "plan_type": "bronze",
        "description": "Essential support for small environments with pay-as-you-go requests.",
        "support_provider": "Microsoft Premier Support",
        "products_covered": "Azure, M365",
        "severity_levels": "B, C",
        "support_hours": "8x5",
        "support_channels": "Email",
        "max_tenants": 1,
        "max_authorized_contacts": 2,
        "support_requests_per_year": 0,
        "crit_sit_management": False,
    },
    {
        "name": "Silver",
        "plan_type": "silver",
        "description": "24/7 support with critical situation management for growing businesses.",
        "support_provider": "Microsoft Premier Support",
        "products_covered": "Azure, M365, D365, On-prem",
        "severity_levels": "A, B, C",
        "support_hours": "24x7x365",
        "support_channels": "Dedicated phone number or Email",
        "max_tenants": 2,
        "max_authorized_contacts": 6,
        "support_requests_per_year": 12,
        "crit_sit_management": True,
    },
    {
        "name": "Gold",
        "plan_type": "gold",
        "description": "Comprehensive support for multi-tenant environments with high request volume.",
        "support_provider": "Microsoft Premier Support",
        "products_covered": "Azure, M365, D365, On-prem",
        "severity_levels": "A, B, C",
        "support_hours": "24x7x365",
        "support_channels": "Dedicated phone number or Email",
        "max_tenants": 6,
        "max_authorized_contacts": 12,
        "support_requests_per_year": 36,
        "crit_sit_management": True,
    },
    {
        "name": "Platinum",
        "plan_type": "platinum",
        "description": "Enterprise-grade support with maximum coverage and dedicated resources.",
        "support_provider": "Microsoft Premier Support",
        "products_covered": "Azure, M365, D365, On-prem",
        "severity_levels": "A, B, C",
        "support_hours": "24x7x365",
        "support_channels": "Dedicated phone number or Email",
        "max_tenants": 100,
        "max_authorized_contacts": 100,
        "support_requests_per_year": 100,
        "crit_sit_management": True,
    },
]


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("crm", "Plan")
    for plan_data in PLANS:
        Plan.objects.update_or_create(
            plan_type=plan_data["plan_type"],
            defaults=plan_data,
        )


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("crm", "Plan")
    Plan.objects.filter(plan_type__in=["bronze", "silver", "gold", "platinum"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_schneider_support_tiers"),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]
