# Generated by Django 5.1.15 on 2026-02-11

import uuid
from datetime import date

from django.db import migrations

# ---------------------------------------------------------------------------
# Deterministic UUIDs so FK references are stable and migration is idempotent
# ---------------------------------------------------------------------------

# Customer Groups
GRP_ARCELOR = uuid.UUID("a0000001-0000-0000-0000-000000000001")
GRP_FERRERO = uuid.UUID("a0000001-0000-0000-0000-000000000002")
GRP_SES = uuid.UUID("a0000001-0000-0000-0000-000000000003")
GRP_CACTUS = uuid.UUID("a0000001-0000-0000-0000-000000000004")
GRP_POST = uuid.UUID("a0000001-0000-0000-0000-000000000005")
GRP_CLEARSTREAM = uuid.UUID("a0000001-0000-0000-0000-000000000006")
GRP_GOODYEAR = uuid.UUID("a0000001-0000-0000-0000-000000000007")
GRP_ENCEVO = uuid.UUID("a0000001-0000-0000-0000-000000000008")

# Entities
ENT_ARCELOR_LU = uuid.UUID("b0000001-0000-0000-0000-000000000001")
ENT_ARCELOR_BE = uuid.UUID("b0000001-0000-0000-0000-000000000002")
ENT_FERRERO_LU = uuid.UUID("b0000001-0000-0000-0000-000000000003")
ENT_FERRERO_DE = uuid.UUID("b0000001-0000-0000-0000-000000000004")
ENT_SES_LU = uuid.UUID("b0000001-0000-0000-0000-000000000005")
ENT_CACTUS_LU = uuid.UUID("b0000001-0000-0000-0000-000000000006")
ENT_POST_LU = uuid.UUID("b0000001-0000-0000-0000-000000000007")
ENT_POST_TELE = uuid.UUID("b0000001-0000-0000-0000-000000000008")
ENT_CLEARSTREAM = uuid.UUID("b0000001-0000-0000-0000-000000000009")
ENT_GOODYEAR_LU = uuid.UUID("b0000001-0000-0000-0000-000000000010")
ENT_ENCEVO_LU = uuid.UUID("b0000001-0000-0000-0000-000000000011")
ENT_ENOVOS = uuid.UUID("b0000001-0000-0000-0000-000000000012")

# Tenants
TEN_ARCELOR_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000001")
TEN_ARCELOR_DEV = uuid.UUID("c0000001-0000-0000-0000-000000000002")
TEN_ARCELOR_BE = uuid.UUID("c0000001-0000-0000-0000-000000000003")
TEN_FERRERO_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000004")
TEN_FERRERO_DE = uuid.UUID("c0000001-0000-0000-0000-000000000005")
TEN_SES_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000006")
TEN_SES_SAND = uuid.UUID("c0000001-0000-0000-0000-000000000007")
TEN_CACTUS_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000008")
TEN_POST_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000009")
TEN_POST_TELE = uuid.UUID("c0000001-0000-0000-0000-000000000010")
TEN_CLEARSTREAM = uuid.UUID("c0000001-0000-0000-0000-000000000011")
TEN_GOODYEAR = uuid.UUID("c0000001-0000-0000-0000-000000000012")
TEN_ENCEVO_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000013")
TEN_ENOVOS_PROD = uuid.UUID("c0000001-0000-0000-0000-000000000014")

# Authorized Contacts
CON_MARC = uuid.UUID("d0000001-0000-0000-0000-000000000001")
CON_SOPHIE = uuid.UUID("d0000001-0000-0000-0000-000000000002")
CON_THOMAS = uuid.UUID("d0000001-0000-0000-0000-000000000003")
CON_ANNA = uuid.UUID("d0000001-0000-0000-0000-000000000004")
CON_LUC = uuid.UUID("d0000001-0000-0000-0000-000000000005")
CON_JULIE = uuid.UUID("d0000001-0000-0000-0000-000000000006")
CON_PIERRE = uuid.UUID("d0000001-0000-0000-0000-000000000007")
CON_SARAH = uuid.UUID("d0000001-0000-0000-0000-000000000008")
CON_GEORGES = uuid.UUID("d0000001-0000-0000-0000-000000000009")
CON_EMMA = uuid.UUID("d0000001-0000-0000-0000-000000000010")
CON_NICOLAS = uuid.UUID("d0000001-0000-0000-0000-000000000011")
CON_CLAIRE = uuid.UUID("d0000001-0000-0000-0000-000000000012")
CON_FRANK = uuid.UUID("d0000001-0000-0000-0000-000000000013")
CON_MARTINE = uuid.UUID("d0000001-0000-0000-0000-000000000014")
CON_PAUL = uuid.UUID("d0000001-0000-0000-0000-000000000015")
CON_ELENA = uuid.UUID("d0000001-0000-0000-0000-000000000016")
CON_ROMAIN = uuid.UUID("d0000001-0000-0000-0000-000000000017")
CON_CHRISTINE = uuid.UUID("d0000001-0000-0000-0000-000000000018")

# Account Managers
AM_SCHNEIDER_A = uuid.UUID("e0000001-0000-0000-0000-000000000001")
AM_SCHNEIDER_B = uuid.UUID("e0000001-0000-0000-0000-000000000002")
AM_SCHNEIDER_C = uuid.UUID("e0000001-0000-0000-0000-000000000003")

# Contracts
CTR_ARCELOR = uuid.UUID("f0000001-0000-0000-0000-000000000001")
CTR_FERRERO = uuid.UUID("f0000001-0000-0000-0000-000000000002")
CTR_SES = uuid.UUID("f0000001-0000-0000-0000-000000000003")
CTR_CACTUS = uuid.UUID("f0000001-0000-0000-0000-000000000004")
CTR_POST = uuid.UUID("f0000001-0000-0000-0000-000000000005")
CTR_CLEARSTREAM = uuid.UUID("f0000001-0000-0000-0000-000000000006")
CTR_GOODYEAR = uuid.UUID("f0000001-0000-0000-0000-000000000007")
CTR_ENCEVO = uuid.UUID("f0000001-0000-0000-0000-000000000008")


def seed_data(apps, schema_editor):
    CustomerGroup = apps.get_model("crm", "CustomerGroup")
    Entity = apps.get_model("crm", "Entity")
    Tenant = apps.get_model("crm", "Tenant")
    AuthorizedContact = apps.get_model("crm", "AuthorizedContact")
    ContactTenantPermission = apps.get_model("crm", "ContactTenantPermission")
    UserRole = apps.get_model("crm", "UserRole")
    Plan = apps.get_model("crm", "Plan")
    Contract = apps.get_model("crm", "Contract")
    AccountManager = apps.get_model("crm", "AccountManager")
    GroupAccountManager = apps.get_model("crm", "GroupAccountManager")

    # -----------------------------------------------------------------------
    # Customer Groups (8 real Luxembourg companies)
    # -----------------------------------------------------------------------
    groups = {
        "arcelor": CustomerGroup.objects.update_or_create(
            id=GRP_ARCELOR,
            defaults={
                "name": "ArcelorMittal Luxembourg",
                "description": "Global steel and mining company headquartered in Luxembourg City. Multiple entities across EU.",
                "is_active": True,
            },
        )[0],
        "ferrero": CustomerGroup.objects.update_or_create(
            id=GRP_FERRERO,
            defaults={
                "name": "Ferrero International",
                "description": "Italian-Luxembourgish multinational. Registered office in Luxembourg.",
                "is_active": True,
            },
        )[0],
        "ses": CustomerGroup.objects.update_or_create(
            id=GRP_SES,
            defaults={
                "name": "SES S.A.",
                "description": "Satellite telecommunications operator based in Betzdorf, Luxembourg.",
                "is_active": True,
            },
        )[0],
        "cactus": CustomerGroup.objects.update_or_create(
            id=GRP_CACTUS,
            defaults={
                "name": "Cactus S.A.",
                "description": "Luxembourg's largest supermarket chain. Single-entity domestic operation.",
                "is_active": True,
            },
        )[0],
        "post": CustomerGroup.objects.update_or_create(
            id=GRP_POST,
            defaults={
                "name": "POST Luxembourg",
                "description": "National postal and telecom operator. Includes POST Telecom subsidiary.",
                "is_active": True,
            },
        )[0],
        "clearstream": CustomerGroup.objects.update_or_create(
            id=GRP_CLEARSTREAM,
            defaults={
                "name": "Clearstream International",
                "description": "International central securities depository. Deutsche Boerse subsidiary in Luxembourg.",
                "is_active": True,
            },
        )[0],
        "goodyear": CustomerGroup.objects.update_or_create(
            id=GRP_GOODYEAR,
            defaults={
                "name": "Goodyear Luxembourg",
                "description": "Goodyear's European innovation center in Colmar-Berg.",
                "is_active": True,
            },
        )[0],
        "encevo": CustomerGroup.objects.update_or_create(
            id=GRP_ENCEVO,
            defaults={
                "name": "Encevo Group",
                "description": "Energy group (Enovos/Creos). Major utility provider in Luxembourg and Greater Region.",
                "is_active": True,
            },
        )[0],
    }

    # -----------------------------------------------------------------------
    # Entities (12 — some groups have multiple legal entities)
    # -----------------------------------------------------------------------
    entities = {
        "arcelor_lu": Entity.objects.update_or_create(
            id=ENT_ARCELOR_LU,
            defaults={
                "group": groups["arcelor"],
                "name": "ArcelorMittal Luxembourg S.A.",
                "description": "Main Luxembourg operating entity",
                "is_active": True,
            },
        )[0],
        "arcelor_be": Entity.objects.update_or_create(
            id=ENT_ARCELOR_BE,
            defaults={
                "group": groups["arcelor"],
                "name": "ArcelorMittal Belgium",
                "description": "Belgian subsidiary managed under Luxembourg group",
                "is_active": True,
            },
        )[0],
        "ferrero_lu": Entity.objects.update_or_create(
            id=ENT_FERRERO_LU,
            defaults={
                "group": groups["ferrero"],
                "name": "Ferrero International S.A.",
                "description": "Luxembourg headquarters entity",
                "is_active": True,
            },
        )[0],
        "ferrero_de": Entity.objects.update_or_create(
            id=ENT_FERRERO_DE,
            defaults={
                "group": groups["ferrero"],
                "name": "Ferrero Deutschland GmbH",
                "description": "German operations managed under Luxembourg group",
                "is_active": True,
            },
        )[0],
        "ses_lu": Entity.objects.update_or_create(
            id=ENT_SES_LU,
            defaults={
                "group": groups["ses"],
                "name": "SES S.A.",
                "description": "Betzdorf headquarters",
                "is_active": True,
            },
        )[0],
        "cactus_lu": Entity.objects.update_or_create(
            id=ENT_CACTUS_LU,
            defaults={
                "group": groups["cactus"],
                "name": "Cactus S.A.",
                "description": "Sole entity — domestic retail",
                "is_active": True,
            },
        )[0],
        "post_lu": Entity.objects.update_or_create(
            id=ENT_POST_LU,
            defaults={
                "group": groups["post"],
                "name": "POST Luxembourg",
                "description": "Postal services & digital",
                "is_active": True,
            },
        )[0],
        "post_tele": Entity.objects.update_or_create(
            id=ENT_POST_TELE,
            defaults={
                "group": groups["post"],
                "name": "POST Telecom S.A.",
                "description": "Telecom subsidiary",
                "is_active": True,
            },
        )[0],
        "clearstream": Entity.objects.update_or_create(
            id=ENT_CLEARSTREAM,
            defaults={
                "group": groups["clearstream"],
                "name": "Clearstream International S.A.",
                "description": "Central securities depository",
                "is_active": True,
            },
        )[0],
        "goodyear_lu": Entity.objects.update_or_create(
            id=ENT_GOODYEAR_LU,
            defaults={
                "group": groups["goodyear"],
                "name": "Goodyear Innovation Center Luxembourg",
                "description": "European R&D center in Colmar-Berg",
                "is_active": True,
            },
        )[0],
        "encevo_lu": Entity.objects.update_or_create(
            id=ENT_ENCEVO_LU,
            defaults={
                "group": groups["encevo"],
                "name": "Encevo S.A.",
                "description": "Parent holding company",
                "is_active": True,
            },
        )[0],
        "enovos": Entity.objects.update_or_create(
            id=ENT_ENOVOS,
            defaults={
                "group": groups["encevo"],
                "name": "Enovos Luxembourg S.A.",
                "description": "Energy supply subsidiary",
                "is_active": True,
            },
        )[0],
    }

    # -----------------------------------------------------------------------
    # Tenants (14 Azure/Entra tenants)
    # -----------------------------------------------------------------------
    tenants = {
        "arcelor_prod": Tenant.objects.update_or_create(
            id=TEN_ARCELOR_PROD,
            defaults={
                "entity": entities["arcelor_lu"],
                "tenant_id_azure": "1a2b3c4d-0001-0001-0001-000000000001",
                "company_name": "ArcelorMittal Luxembourg",
                "environment_type": "production",
                "primary_domain": "arcelormittal.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "arcelor_dev": Tenant.objects.update_or_create(
            id=TEN_ARCELOR_DEV,
            defaults={
                "entity": entities["arcelor_lu"],
                "tenant_id_azure": "1a2b3c4d-0001-0001-0001-000000000002",
                "company_name": "ArcelorMittal Luxembourg (Dev)",
                "environment_type": "development",
                "primary_domain": "arcelormittaldev.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "arcelor_be": Tenant.objects.update_or_create(
            id=TEN_ARCELOR_BE,
            defaults={
                "entity": entities["arcelor_be"],
                "tenant_id_azure": "1a2b3c4d-0001-0001-0001-000000000003",
                "company_name": "ArcelorMittal Belgium",
                "environment_type": "production",
                "primary_domain": "arcelormittalbe.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "ferrero_prod": Tenant.objects.update_or_create(
            id=TEN_FERRERO_PROD,
            defaults={
                "entity": entities["ferrero_lu"],
                "tenant_id_azure": "2a2b3c4d-0002-0002-0002-000000000001",
                "company_name": "Ferrero International",
                "environment_type": "production",
                "primary_domain": "ferrero.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "ferrero_de": Tenant.objects.update_or_create(
            id=TEN_FERRERO_DE,
            defaults={
                "entity": entities["ferrero_de"],
                "tenant_id_azure": "2a2b3c4d-0002-0002-0002-000000000002",
                "company_name": "Ferrero Deutschland",
                "environment_type": "production",
                "primary_domain": "ferrerode.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "ses_prod": Tenant.objects.update_or_create(
            id=TEN_SES_PROD,
            defaults={
                "entity": entities["ses_lu"],
                "tenant_id_azure": "3a2b3c4d-0003-0003-0003-000000000001",
                "company_name": "SES S.A.",
                "environment_type": "production",
                "primary_domain": "ses.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "ses_sand": Tenant.objects.update_or_create(
            id=TEN_SES_SAND,
            defaults={
                "entity": entities["ses_lu"],
                "tenant_id_azure": "3a2b3c4d-0003-0003-0003-000000000002",
                "company_name": "SES S.A. (Sandbox)",
                "environment_type": "sandbox",
                "primary_domain": "sessandbox.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "cactus_prod": Tenant.objects.update_or_create(
            id=TEN_CACTUS_PROD,
            defaults={
                "entity": entities["cactus_lu"],
                "tenant_id_azure": "4a2b3c4d-0004-0004-0004-000000000001",
                "company_name": "Cactus S.A.",
                "environment_type": "production",
                "primary_domain": "cactus.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "post_prod": Tenant.objects.update_or_create(
            id=TEN_POST_PROD,
            defaults={
                "entity": entities["post_lu"],
                "tenant_id_azure": "5a2b3c4d-0005-0005-0005-000000000001",
                "company_name": "POST Luxembourg",
                "environment_type": "production",
                "primary_domain": "post.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "post_tele": Tenant.objects.update_or_create(
            id=TEN_POST_TELE,
            defaults={
                "entity": entities["post_tele"],
                "tenant_id_azure": "5a2b3c4d-0005-0005-0005-000000000002",
                "company_name": "POST Telecom",
                "environment_type": "production",
                "primary_domain": "posttelecom.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "clearstream": Tenant.objects.update_or_create(
            id=TEN_CLEARSTREAM,
            defaults={
                "entity": entities["clearstream"],
                "tenant_id_azure": "6a2b3c4d-0006-0006-0006-000000000001",
                "company_name": "Clearstream International",
                "environment_type": "production",
                "primary_domain": "clearstream.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "goodyear": Tenant.objects.update_or_create(
            id=TEN_GOODYEAR,
            defaults={
                "entity": entities["goodyear_lu"],
                "tenant_id_azure": "7a2b3c4d-0007-0007-0007-000000000001",
                "company_name": "Goodyear Innovation Center",
                "environment_type": "production",
                "primary_domain": "goodyear.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "encevo_prod": Tenant.objects.update_or_create(
            id=TEN_ENCEVO_PROD,
            defaults={
                "entity": entities["encevo_lu"],
                "tenant_id_azure": "8a2b3c4d-0008-0008-0008-000000000001",
                "company_name": "Encevo S.A.",
                "environment_type": "production",
                "primary_domain": "encevo.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
        "enovos_prod": Tenant.objects.update_or_create(
            id=TEN_ENOVOS_PROD,
            defaults={
                "entity": entities["enovos"],
                "tenant_id_azure": "8a2b3c4d-0008-0008-0008-000000000002",
                "company_name": "Enovos Luxembourg",
                "environment_type": "production",
                "primary_domain": "enovos.onmicrosoft.com",
                "is_active": True,
            },
        )[0],
    }

    # -----------------------------------------------------------------------
    # Authorized Contacts (18 — typical Luxembourg names)
    # -----------------------------------------------------------------------
    contacts_data = [
        # ArcelorMittal (Platinum — up to 100 contacts, we add 4)
        (
            CON_MARC,
            GRP_ARCELOR,
            "Marc Weber",
            "m.weber@arcelormittal.com",
            "+352 621 100 001",
            "aad-marc-0001",
        ),
        (
            CON_SOPHIE,
            GRP_ARCELOR,
            "Sophie Muller",
            "s.muller@arcelormittal.com",
            "+352 621 100 002",
            "aad-sophie-0002",
        ),
        (
            CON_THOMAS,
            GRP_ARCELOR,
            "Thomas Schmit",
            "t.schmit@arcelormittal.com",
            "+352 621 100 003",
            "aad-thomas-0003",
        ),
        (
            CON_ANNA,
            GRP_ARCELOR,
            "Anna Kieffer",
            "a.kieffer@arcelormittal.com",
            "+352 621 100 004",
            "aad-anna-0004",
        ),
        # Ferrero (Gold — up to 12 contacts, we add 3)
        (
            CON_LUC,
            GRP_FERRERO,
            "Luc Thill",
            "l.thill@ferrero.com",
            "+352 621 200 001",
            "aad-luc-0005",
        ),
        (
            CON_JULIE,
            GRP_FERRERO,
            "Julie Reding",
            "j.reding@ferrero.com",
            "+352 621 200 002",
            "aad-julie-0006",
        ),
        (
            CON_PIERRE,
            GRP_FERRERO,
            "Pierre Meyers",
            "p.meyers@ferrero.com",
            "+352 621 200 003",
            "aad-pierre-0007",
        ),
        # SES (Gold — up to 12 contacts, we add 3)
        (
            CON_SARAH,
            GRP_SES,
            "Sarah Hoffmann",
            "s.hoffmann@ses.com",
            "+352 621 300 001",
            "aad-sarah-0008",
        ),
        (
            CON_GEORGES,
            GRP_SES,
            "Georges Faber",
            "g.faber@ses.com",
            "+352 621 300 002",
            "aad-georges-0009",
        ),
        (
            CON_EMMA,
            GRP_SES,
            "Emma Schiltz",
            "e.schiltz@ses.com",
            "+352 621 300 003",
            "aad-emma-0010",
        ),
        # Cactus (Bronze — up to 2 contacts)
        (
            CON_NICOLAS,
            GRP_CACTUS,
            "Nicolas Reuter",
            "n.reuter@cactus.lu",
            "+352 621 400 001",
            "aad-nicolas-0011",
        ),
        (
            CON_CLAIRE,
            GRP_CACTUS,
            "Claire Becker",
            "c.becker@cactus.lu",
            "+352 621 400 002",
            "aad-claire-0012",
        ),
        # POST (Silver — up to 6 contacts, we add 2)
        (
            CON_FRANK,
            GRP_POST,
            "Frank Lentz",
            "f.lentz@post.lu",
            "+352 621 500 001",
            "aad-frank-0013",
        ),
        (
            CON_MARTINE,
            GRP_POST,
            "Martine Simon",
            "m.simon@post.lu",
            "+352 621 500 002",
            "aad-martine-0014",
        ),
        # Clearstream (Platinum — we add 2)
        (
            CON_PAUL,
            GRP_CLEARSTREAM,
            "Paul Kremer",
            "p.kremer@clearstream.com",
            "+352 621 600 001",
            "aad-paul-0015",
        ),
        (
            CON_ELENA,
            GRP_CLEARSTREAM,
            "Elena Bras",
            "e.bras@clearstream.com",
            "+352 621 600 002",
            "aad-elena-0016",
        ),
        # Goodyear (Silver — up to 6 contacts, we add 1)
        (
            CON_ROMAIN,
            GRP_GOODYEAR,
            "Romain Lopes",
            "r.lopes@goodyear.com",
            "+352 621 700 001",
            "aad-romain-0017",
        ),
        # Encevo (Silver — up to 6, we add 1)
        (
            CON_CHRISTINE,
            GRP_ENCEVO,
            "Christine Majerus",
            "c.majerus@encevo.lu",
            "+352 621 800 001",
            "aad-christine-0018",
        ),
    ]

    contacts = {}
    for cid, gid, name, email, phone, entra_id in contacts_data:
        obj, _ = AuthorizedContact.objects.update_or_create(
            id=cid,
            defaults={
                "group_id": gid,
                "display_name": name,
                "email": email,
                "phone": phone,
                "entra_object_id": entra_id,
                "is_active": True,
            },
        )
        contacts[cid] = obj

    # -----------------------------------------------------------------------
    # Contact ↔ Tenant Permissions
    # -----------------------------------------------------------------------
    permissions = [
        # ArcelorMittal — Marc & Sophie have full access to all 3 tenants
        (CON_MARC, TEN_ARCELOR_PROD, True, True),
        (CON_MARC, TEN_ARCELOR_DEV, True, True),
        (CON_MARC, TEN_ARCELOR_BE, True, True),
        (CON_SOPHIE, TEN_ARCELOR_PROD, True, True),
        (CON_SOPHIE, TEN_ARCELOR_DEV, True, True),
        (CON_SOPHIE, TEN_ARCELOR_BE, True, True),
        # Thomas — prod only
        (CON_THOMAS, TEN_ARCELOR_PROD, True, True),
        # Anna — view only on prod
        (CON_ANNA, TEN_ARCELOR_PROD, False, True),
        # Ferrero — Luc full, Julie & Pierre prod only
        (CON_LUC, TEN_FERRERO_PROD, True, True),
        (CON_LUC, TEN_FERRERO_DE, True, True),
        (CON_JULIE, TEN_FERRERO_PROD, True, True),
        (CON_PIERRE, TEN_FERRERO_PROD, True, True),
        # SES — all 3 contacts on both tenants
        (CON_SARAH, TEN_SES_PROD, True, True),
        (CON_SARAH, TEN_SES_SAND, True, True),
        (CON_GEORGES, TEN_SES_PROD, True, True),
        (CON_GEORGES, TEN_SES_SAND, True, True),
        (CON_EMMA, TEN_SES_PROD, False, True),
        # Cactus — both contacts on single tenant
        (CON_NICOLAS, TEN_CACTUS_PROD, True, True),
        (CON_CLAIRE, TEN_CACTUS_PROD, True, True),
        # POST — Frank on both, Martine on telecom only
        (CON_FRANK, TEN_POST_PROD, True, True),
        (CON_FRANK, TEN_POST_TELE, True, True),
        (CON_MARTINE, TEN_POST_TELE, True, True),
        # Clearstream
        (CON_PAUL, TEN_CLEARSTREAM, True, True),
        (CON_ELENA, TEN_CLEARSTREAM, True, True),
        # Goodyear
        (CON_ROMAIN, TEN_GOODYEAR, True, True),
        # Encevo — Christine on both tenants
        (CON_CHRISTINE, TEN_ENCEVO_PROD, True, True),
        (CON_CHRISTINE, TEN_ENOVOS_PROD, True, True),
    ]

    for contact_id, tenant_id, can_create, can_view in permissions:
        ContactTenantPermission.objects.update_or_create(
            contact_id=contact_id,
            tenant_id=tenant_id,
            defaults={
                "can_create_tickets": can_create,
                "can_view_tickets": can_view,
            },
        )

    # -----------------------------------------------------------------------
    # User Roles
    # -----------------------------------------------------------------------
    roles = [
        # ArcelorMittal
        (CON_MARC, GRP_ARCELOR, "admin"),
        (CON_SOPHIE, GRP_ARCELOR, "manager"),
        (CON_THOMAS, GRP_ARCELOR, "user"),
        (CON_ANNA, GRP_ARCELOR, "viewer"),
        # Ferrero
        (CON_LUC, GRP_FERRERO, "admin"),
        (CON_JULIE, GRP_FERRERO, "user"),
        (CON_PIERRE, GRP_FERRERO, "user"),
        # SES
        (CON_SARAH, GRP_SES, "admin"),
        (CON_GEORGES, GRP_SES, "user"),
        (CON_EMMA, GRP_SES, "viewer"),
        # Cactus
        (CON_NICOLAS, GRP_CACTUS, "admin"),
        (CON_CLAIRE, GRP_CACTUS, "user"),
        # POST
        (CON_FRANK, GRP_POST, "admin"),
        (CON_MARTINE, GRP_POST, "user"),
        # Clearstream
        (CON_PAUL, GRP_CLEARSTREAM, "admin"),
        (CON_ELENA, GRP_CLEARSTREAM, "manager"),
        # Goodyear
        (CON_ROMAIN, GRP_GOODYEAR, "admin"),
        # Encevo
        (CON_CHRISTINE, GRP_ENCEVO, "admin"),
    ]

    for contact_id, group_id, role in roles:
        UserRole.objects.update_or_create(
            contact_id=contact_id,
            group_id=group_id,
            defaults={"role": role},
        )

    # -----------------------------------------------------------------------
    # Contracts — link groups to plans (plans seeded in 0003)
    # -----------------------------------------------------------------------
    plan_by_type = {p.plan_type: p for p in Plan.objects.all()}

    contracts_data = [
        # ArcelorMittal — Platinum, active, auto-renewal
        (
            CTR_ARCELOR,
            GRP_ARCELOR,
            "platinum",
            "SCH-2025-PLT-001",
            date(2025, 4, 1),
            date(2026, 3, 31),
            True,
            "active",
        ),
        # Ferrero — Gold, active
        (
            CTR_FERRERO,
            GRP_FERRERO,
            "gold",
            "SCH-2025-GLD-002",
            date(2025, 6, 1),
            date(2026, 5, 31),
            True,
            "active",
        ),
        # SES — Gold, active
        (
            CTR_SES,
            GRP_SES,
            "gold",
            "SCH-2025-GLD-003",
            date(2025, 1, 15),
            date(2026, 1, 14),
            True,
            "active",
        ),
        # Cactus — Bronze, active
        (
            CTR_CACTUS,
            GRP_CACTUS,
            "bronze",
            "SCH-2025-BRZ-004",
            date(2025, 9, 1),
            date(2026, 8, 31),
            False,
            "active",
        ),
        # POST — Silver, active
        (
            CTR_POST,
            GRP_POST,
            "silver",
            "SCH-2025-SLV-005",
            date(2025, 3, 1),
            date(2026, 2, 28),
            True,
            "active",
        ),
        # Clearstream — Platinum, active
        (
            CTR_CLEARSTREAM,
            GRP_CLEARSTREAM,
            "platinum",
            "SCH-2025-PLT-006",
            date(2025, 7, 1),
            date(2026, 6, 30),
            True,
            "active",
        ),
        # Goodyear — Silver, active
        (
            CTR_GOODYEAR,
            GRP_GOODYEAR,
            "silver",
            "SCH-2025-SLV-007",
            date(2025, 5, 1),
            date(2026, 4, 30),
            False,
            "active",
        ),
        # Encevo — Silver, active
        (
            CTR_ENCEVO,
            GRP_ENCEVO,
            "silver",
            "SCH-2025-SLV-008",
            date(2025, 8, 1),
            date(2026, 7, 31),
            True,
            "active",
        ),
    ]

    for (
        ctr_id,
        grp_id,
        plan_type,
        number,
        start,
        end,
        renewal,
        status,
    ) in contracts_data:
        Contract.objects.update_or_create(
            id=ctr_id,
            defaults={
                "group_id": grp_id,
                "plan": plan_by_type[plan_type],
                "contract_number": number,
                "start_date": start,
                "end_date": end,
                "auto_renewal": renewal,
                "status": status,
            },
        )

    # -----------------------------------------------------------------------
    # Account Managers (3 Schneider IT Management staff)
    # -----------------------------------------------------------------------
    managers = {
        "alex": AccountManager.objects.update_or_create(
            id=AM_SCHNEIDER_A,
            defaults={
                "employee_id": "SCH-AM-001",
                "email": "a.schneider@schneider-itm.lu",
                "display_name": "Alexander Schneider",
                "phone_dedicated": "+352 26 00 10 01",
                "is_active": True,
            },
        )[0],
        "maria": AccountManager.objects.update_or_create(
            id=AM_SCHNEIDER_B,
            defaults={
                "employee_id": "SCH-AM-002",
                "email": "m.koch@schneider-itm.lu",
                "display_name": "Maria Koch",
                "phone_dedicated": "+352 26 00 10 02",
                "is_active": True,
            },
        )[0],
        "jan": AccountManager.objects.update_or_create(
            id=AM_SCHNEIDER_C,
            defaults={
                "employee_id": "SCH-AM-003",
                "email": "j.wagner@schneider-itm.lu",
                "display_name": "Jan Wagner",
                "phone_dedicated": "+352 26 00 10 03",
                "is_active": True,
            },
        )[0],
    }

    # -----------------------------------------------------------------------
    # Group ↔ Account Manager assignments
    # Alexander handles Platinum clients (primary) + Gold backup
    # Maria handles Gold (primary) + Silver
    # Jan handles Silver (primary) + Bronze
    # -----------------------------------------------------------------------
    assignments = [
        # Alexander — primary for Platinum clients
        (GRP_ARCELOR, AM_SCHNEIDER_A, True),
        (GRP_CLEARSTREAM, AM_SCHNEIDER_A, True),
        # Alexander — backup for Gold
        (GRP_FERRERO, AM_SCHNEIDER_A, False),
        (GRP_SES, AM_SCHNEIDER_A, False),
        # Maria — primary for Gold clients
        (GRP_FERRERO, AM_SCHNEIDER_B, True),
        (GRP_SES, AM_SCHNEIDER_B, True),
        # Maria — backup for Silver
        (GRP_POST, AM_SCHNEIDER_B, False),
        # Jan — primary for Silver clients
        (GRP_POST, AM_SCHNEIDER_C, True),
        (GRP_GOODYEAR, AM_SCHNEIDER_C, True),
        (GRP_ENCEVO, AM_SCHNEIDER_C, True),
        # Jan — primary for Bronze
        (GRP_CACTUS, AM_SCHNEIDER_C, True),
    ]

    for group_id, manager_id, is_primary in assignments:
        GroupAccountManager.objects.update_or_create(
            group_id=group_id,
            account_manager_id=manager_id,
            defaults={"is_primary": is_primary},
        )


def remove_data(apps, schema_editor):
    """Remove all seeded sample data in reverse order."""
    GroupAccountManager = apps.get_model("crm", "GroupAccountManager")
    AccountManager = apps.get_model("crm", "AccountManager")
    Contract = apps.get_model("crm", "Contract")
    UserRole = apps.get_model("crm", "UserRole")
    ContactTenantPermission = apps.get_model("crm", "ContactTenantPermission")
    AuthorizedContact = apps.get_model("crm", "AuthorizedContact")
    Tenant = apps.get_model("crm", "Tenant")
    Entity = apps.get_model("crm", "Entity")
    CustomerGroup = apps.get_model("crm", "CustomerGroup")

    all_group_ids = [
        GRP_ARCELOR,
        GRP_FERRERO,
        GRP_SES,
        GRP_CACTUS,
        GRP_POST,
        GRP_CLEARSTREAM,
        GRP_GOODYEAR,
        GRP_ENCEVO,
    ]
    all_manager_ids = [AM_SCHNEIDER_A, AM_SCHNEIDER_B, AM_SCHNEIDER_C]

    GroupAccountManager.objects.filter(group_id__in=all_group_ids).delete()
    AccountManager.objects.filter(id__in=all_manager_ids).delete()
    Contract.objects.filter(group_id__in=all_group_ids).delete()
    UserRole.objects.filter(group_id__in=all_group_ids).delete()
    ContactTenantPermission.objects.filter(contact__group_id__in=all_group_ids).delete()
    AuthorizedContact.objects.filter(group_id__in=all_group_ids).delete()
    Tenant.objects.filter(entity__group_id__in=all_group_ids).delete()
    Entity.objects.filter(group_id__in=all_group_ids).delete()
    CustomerGroup.objects.filter(id__in=all_group_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_seed_schneider_plans"),
    ]

    operations = [
        migrations.RunPython(seed_data, remove_data),
    ]
