# Generated by Django 5.1.15 on 2026-02-11 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_seed_sample_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceExpert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "phone_dedicated",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Dedicated Phone",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="assigned_expert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="crm.serviceexpert",
            ),
        ),
        migrations.CreateModel(
            name="GroupServiceExpert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary service expert for this group"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_expert_assignments",
                        to="crm.customergroup",
                    ),
                ),
                (
                    "service_expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="crm.serviceexpert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group ↔ Service Expert",
                "verbose_name_plural": "Group ↔ Service Expert Assignments",
                "unique_together": {("group", "service_expert")},
            },
        ),
    ]
