# Generated by Django 5.1.15 on 2026-02-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_serviceexpert_ticket_assigned_expert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizedcontact",
            name="business_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="authorizedcontact",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="authorizedcontact",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="authorizedcontact",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="authorizedcontact",
            name="mobile_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="authorizedcontact",
            name="teams_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("none", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("email_sent", "Email Sent"),
                    ("completed", "Completed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="gdap_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="GDAP approval link for this tenant",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="has_azure",
            field=models.BooleanField(
                default=False, help_text="Whether Azure RBAC setup is needed"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="implementation_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="microsoft_tenant_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. contoso.onmicrosoft.com",
                max_length=255,
            ),
        ),
    ]
