# Generated by Django 5.1.15 on 2026-02-11 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0009_authorizedcontact_business_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("email_generated", "Email Generated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German"), ("fr", "French")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(help_text="Recipient name", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(help_text="Recipient email", max_length=254),
                ),
                (
                    "meeting_slots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of selected slot datetimes (ISO format)",
                    ),
                ),
                ("include_gdap", models.BooleanField(default=True)),
                ("include_rbac", models.BooleanField(default=True)),
                ("include_conditional_access", models.BooleanField(default=False)),
                ("additional_notes", models.TextField(blank=True, default="")),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sender_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sender_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "sender_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to="crm.customergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("html_content", models.TextField(help_text="Generated HTML email")),
                (
                    "plain_content",
                    models.TextField(help_text="Generated plain text email"),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        blank=True, help_text="When .eml was downloaded", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="onboarding.onboardingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Email",
                "ordering": ["-created_at"],
            },
        ),
    ]
