# Generated by Django 5.1.15 on 2026-02-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_authorizedcontact_business_phone_and_more"),
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Service expert who sends the onboarding email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_sessions",
                to="crm.serviceexpert",
            ),
        ),
    ]
