# Generated by Django 5.1.15 on 2026-02-11 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_authorizedcontact_business_phone_and_more"),
        ("onboarding", "0002_onboardingsession_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Authorized contact who receives the onboarding email (typically Admin role)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_sessions",
                to="crm.authorizedcontact",
            ),
        ),
        migrations.AddField(
            model_name="onboardingsession",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenants included in this onboarding (GDAP, RBAC, etc.)",
                related_name="onboarding_sessions",
                to="crm.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingsession",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="onboardingsession",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
