# Generated by Django 5.1 on 2025-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='linkedin_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
