# Generated by Django 5.1 on 2025-01-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0002_entrepreneurprofile_linkedin_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='profile_picture',
        ),
    ]
