# Generated by Django 5.1.4 on 2025-12-14 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0003_remove_entrepreneurprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lux Pixel War', max_length=100)),
                ('width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('anonymous_cooldown_seconds', models.IntegerField(default=30, help_text='Cooldown for anonymous users (seconds)')),
                ('registered_cooldown_seconds', models.IntegerField(default=12, help_text='Cooldown for registered users (seconds)')),
                ('registered_pixels_per_minute', models.IntegerField(default=5, help_text='Max pixels per minute for registered users')),
                ('anonymous_pixels_per_minute', models.IntegerField(default=2, help_text='Max pixels per minute for anonymous users')),
            ],
            options={
                'verbose_name_plural': 'Pixel Canvases',
                'db_table': 'vibe_coding_pixelcanvas',
            },
        ),
        migrations.CreateModel(
            name='CostAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('dimension_type', models.CharField(choices=[('overall', 'Overall'), ('subscription', 'By Subscription'), ('service', 'By Service'), ('resource_group', 'By Resource Group'), ('region', 'By Region'), ('resource', 'By Resource')], db_index=True, max_length=50)),
                ('dimension_value', models.CharField(db_index=True, max_length=300)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('usage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('top_services', models.JSONField(blank=True, default=list)),
                ('top_resources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finops_hub_costaggregation',
                'ordering': ['-period_start', 'dimension_type', 'dimension_value'],
                'indexes': [models.Index(fields=['aggregation_type', 'period_start'], name='finops_hub__aggrega_5d9e9e_idx'), models.Index(fields=['dimension_type', 'dimension_value', 'period_start'], name='finops_hub__dimensi_8db775_idx')],
                'unique_together': {('aggregation_type', 'dimension_type', 'dimension_value', 'period_start', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CostExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('subscription_name', models.CharField(db_index=True, max_length=200)),
                ('subscription_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('billing_period_start', models.DateField(db_index=True)),
                ('billing_period_end', models.DateField()),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('import_started_at', models.DateTimeField(auto_now_add=True)),
                ('import_completed_at', models.DateTimeField(blank=True, null=True)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('needs_subscription_id', models.BooleanField(db_index=True, default=False)),
                ('blob_last_modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('blob_etag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'finops_hub_costexport',
                'ordering': ['-billing_period_start', '-import_started_at'],
                'indexes': [models.Index(fields=['subscription_name', 'billing_period_start'], name='finops_hub__subscri_0dbb11_idx'), models.Index(fields=['import_status', 'import_completed_at'], name='finops_hub__import__9d31f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PixelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='entreprinder.pixelcanvas')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vibe_coding_pixelhistory',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=12)),
                ('billing_currency', models.CharField(db_index=True, max_length=10)),
                ('effective_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('list_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('billing_period_start', models.DateField(db_index=True)),
                ('billing_period_end', models.DateField()),
                ('charge_period_start', models.DateTimeField(db_index=True)),
                ('charge_period_end', models.DateTimeField()),
                ('billing_account_id', models.CharField(db_index=True, max_length=200)),
                ('billing_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_account_id', models.CharField(db_index=True, max_length=200)),
                ('sub_account_name', models.CharField(db_index=True, max_length=200)),
                ('resource_id', models.TextField(db_index=True)),
                ('resource_name', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('resource_group_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('service_name', models.CharField(db_index=True, max_length=200)),
                ('service_category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('provider_name', models.CharField(default='Microsoft', max_length=100)),
                ('region_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_description', models.TextField(blank=True, null=True)),
                ('sku_meter_category', models.CharField(blank=True, max_length=200, null=True)),
                ('sku_meter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('charge_category', models.CharField(db_index=True, max_length=50)),
                ('charge_description', models.TextField(blank=True, null=True)),
                ('charge_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('consumed_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('consumed_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pricing_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('extended_data', models.JSONField(blank=True, default=dict)),
                ('record_hash', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='entreprinder.costexport')),
            ],
            options={
                'db_table': 'finops_hub_costrecord',
                'ordering': ['-charge_period_start'],
                'indexes': [models.Index(fields=['billing_period_start', 'sub_account_name'], name='finops_hub__billing_8853b3_idx'), models.Index(fields=['service_name', 'billing_period_start'], name='finops_hub__service_809822_idx'), models.Index(fields=['resource_group_name', 'billing_period_start'], name='finops_hub__resourc_1be05a_idx'), models.Index(fields=['charge_period_start', 'billed_cost'], name='finops_hub__charge__23fb00_idx'), models.Index(fields=['resource_name', 'service_name'], name='finops_hub__resourc_3481d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_received', to='entreprinder.entrepreneurprofile')),
                ('disliker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_given', to='entreprinder.entrepreneurprofile')),
            ],
            options={
                'db_table': 'matching_dislike',
                'unique_together': {('disliker', 'disliked')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='entreprinder.entrepreneurprofile')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='entreprinder.entrepreneurprofile')),
            ],
            options={
                'db_table': 'matching_like',
                'indexes': [models.Index(fields=['liker', 'liked'], name='matching_li_liker_i_5a549e_idx')],
                'unique_together': {('liker', 'liked')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first', to='entreprinder.entrepreneurprofile')),
                ('entrepreneur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second', to='entreprinder.entrepreneurprofile')),
            ],
            options={
                'db_table': 'matching_match',
                'unique_together': {('entrepreneur1', 'entrepreneur2')},
            },
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('placed_at', models.DateTimeField(auto_now=True)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='entreprinder.pixelcanvas')),
            ],
            options={
                'db_table': 'vibe_coding_pixel',
                'ordering': ['y', 'x'],
                'unique_together': {('canvas', 'x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='UserPixelCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_placed', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pixels_placed_last_minute', models.IntegerField(default=0)),
                ('last_minute_reset', models.DateTimeField(auto_now_add=True, null=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprinder.pixelcanvas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vibe_coding_userpixelcooldown',
                'indexes': [models.Index(fields=['canvas', 'last_placed'], name='vibe_coding_canvas__742cb8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'canvas'), name='entreprinder_unique_user_canvas'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'canvas'), name='entreprinder_unique_session_canvas')],
            },
        ),
        migrations.CreateModel(
            name='UserPixelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pixels_placed', models.IntegerField(default=0)),
                ('last_pixel_placed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprinder.pixelcanvas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vibe_coding_userpixelstats',
                'unique_together': {('user', 'canvas')},
            },
        ),
    ]
