# Generated by Django 5.1.15 on 2026-01-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprinder",
            "0004_pixelcanvas_costaggregation_costexport_pixelhistory_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CostAggregation",
        ),
        migrations.RemoveField(
            model_name="costrecord",
            name="cost_export",
        ),
        migrations.DeleteModel(
            name="CostExport",
        ),
        migrations.DeleteModel(
            name="CostRecord",
        ),
    ]
