# Generated by Django 6.0.4 on 2026-04-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprinder", "0006_create_site_objects"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dislike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dislike",
            name="disliked",
        ),
        migrations.RemoveField(
            model_name="dislike",
            name="disliker",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="like",
            name="matching_li_liker_i_5a549e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="match",
            name="entrepreneur1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="entrepreneur2",
        ),
        migrations.DeleteModel(
            name="Dislike",
        ),
        migrations.RemoveField(
            model_name="like",
            name="liked",
        ),
        migrations.RemoveField(
            model_name="like",
            name="liker",
        ),
        migrations.DeleteModel(
            name="Match",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
