# Generated by Django 5.1 on 2025-08-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpixelcooldown',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pixelcanvas',
            name='cooldown_seconds',
        ),
        migrations.AddField(
            model_name='pixelcanvas',
            name='anonymous_cooldown_seconds',
            field=models.IntegerField(default=30, help_text='Cooldown for anonymous users (seconds)'),
        ),
        migrations.AddField(
            model_name='pixelcanvas',
            name='anonymous_pixels_per_minute',
            field=models.IntegerField(default=2, help_text='Max pixels per minute for anonymous users'),
        ),
        migrations.AddField(
            model_name='pixelcanvas',
            name='registered_cooldown_seconds',
            field=models.IntegerField(default=12, help_text='Cooldown for registered users (seconds)'),
        ),
        migrations.AddField(
            model_name='pixelcanvas',
            name='registered_pixels_per_minute',
            field=models.IntegerField(default=5, help_text='Max pixels per minute for registered users'),
        ),
        migrations.AddField(
            model_name='userpixelcooldown',
            name='last_minute_reset',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userpixelcooldown',
            name='pixels_placed_last_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpixelcooldown',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpixelcooldown',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userpixelcooldown',
            unique_together={('user', 'canvas', 'session_key')},
        ),
        migrations.CreateModel(
            name='UserPixelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pixels_placed', models.IntegerField(default=0)),
                ('last_pixel_placed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibe_coding.pixelcanvas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'canvas')},
            },
        ),
    ]
