# Generated by Django 5.1 on 2025-08-24 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_coding', '0002_alter_userpixelcooldown_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpixelcooldown',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userpixelcooldown',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='userpixelcooldown',
            index=models.Index(fields=['canvas', 'last_placed'], name='vibe_coding_canvas__742cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpixelcooldown',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'canvas'), name='unique_user_canvas'),
        ),
        migrations.AddConstraint(
            model_name='userpixelcooldown',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'canvas'), name='unique_session_canvas'),
        ),
    ]
