# Generated by Django 5.1 on 2024-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0003_alter_match_unique_together_and_more'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['liker', 'liked'], name='matching_li_liker_i_5a549e_idx'),
        ),
    ]
