#!/usr/bin/env python
"""
Script to generate translations for .po files.
Run with: python scripts/translate_po.py
"""

import re
from pathlib import Path

# German translations dictionary - comprehensive
DE_TRANSLATIONS = {
    # Navigation & Common UI
    "Home": "Startseite",
    "About": "Über uns",
    "Events": "Veranstaltungen",
    "Dashboard": "Dashboard",
    "Profile": "Profil",
    "Settings": "Einstellungen",
    "Login": "Anmelden",
    "Logout": "Abmelden",
    "Sign Up": "Registrieren",
    "Sign In": "Anmelden",
    "Sign Out": "Abmelden",
    "Register": "Registrieren",
    "Submit": "Absenden",
    "Cancel": "Abbrechen",
    "Save": "Speichern",
    "Edit": "Bearbeiten",
    "Delete": "Löschen",
    "Close": "Schließen",
    "Back": "Zurück",
    "Next": "Weiter",
    "Previous": "Zurück",
    "Search": "Suchen",
    "Filter": "Filtern",
    "Sort": "Sortieren",
    "View": "Ansehen",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Change": "Ändern",
    "Download": "Herunterladen",
    "Upload": "Hochladen",
    "Loading...": "Lädt...",
    "Loading": "Lädt",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Warning": "Warnung",
    "Info": "Info",
    "Yes": "Ja",
    "No": "Nein",
    "OK": "OK",
    "Confirm": "Bestätigen",
    "Continue": "Fortfahren",
    "Learn More": "Mehr erfahren",
    "Read More": "Mehr lesen",
    "See All": "Alle ansehen",
    "Show More": "Mehr anzeigen",
    "Show Less": "Weniger anzeigen",
    "Go": "Los",
    "Go Back": "Zurück",
    "Language": "Sprache",
    "View Details": "Details ansehen",
    "View All Events": "Alle Veranstaltungen ansehen",
    "View Event": "Veranstaltung ansehen",
    "View Upcoming Events": "Kommende Veranstaltungen ansehen",
    "Browse Events": "Veranstaltungen durchsuchen",

    # Authentication
    "Email": "E-Mail",
    "E-mail": "E-Mail",
    "Password": "Passwort",
    "Confirm Password": "Passwort bestätigen",
    "New Password": "Neues Passwort",
    "Enter new password": "Neues Passwort eingeben",
    "Confirm new password": "Neues Passwort bestätigen",
    "Password (again)": "Passwort (nochmal)",
    "Remember me": "Angemeldet bleiben",
    "Forgot Password?": "Passwort vergessen?",
    "Reset Password": "Passwort zurücksetzen",
    "Password Reset": "Passwort zurücksetzen",
    "Reset My Password": "Mein Passwort zurücksetzen",
    "Change Password": "Passwort ändern",
    "First Name": "Vorname",
    "Last Name": "Nachname",
    "Username": "Benutzername",
    "Phone": "Telefon",
    "Phone Number": "Telefonnummer",
    "Date of Birth": "Geburtsdatum",
    "Age": "Alter",
    "Gender": "Geschlecht",
    "Male": "Männlich",
    "Female": "Weiblich",
    "Other": "Andere",
    "Location": "Standort",
    "City": "Stadt",
    "Country": "Land",
    "Bio": "Bio",
    "About me": "Über mich",
    "Interests": "Interessen",
    "Sign in with LinkedIn": "Mit LinkedIn anmelden",
    "Sign in with Google": "Mit Google anmelden",
    "Sign in with Facebook": "Mit Facebook anmelden",
    "Already have an account?": "Haben Sie bereits ein Konto?",
    "Don't have an account?": "Haben Sie noch kein Konto?",
    "Login here": "Hier anmelden",
    "Third-Party Login Error": "Drittanbieter-Anmeldefehler",
    "Back to Login": "Zurück zur Anmeldung",
    "Create New Account": "Neues Konto erstellen",
    "Your password must be at least 8 characters.": "Ihr Passwort muss mindestens 8 Zeichen lang sein.",
    "Passwords do not match.": "Passwörter stimmen nicht überein.",

    # Profile & Account
    "My Profile": "Mein Profil",
    "Edit Profile": "Profil bearbeiten",
    "View Profile": "Profil ansehen",
    "Account Settings": "Kontoeinstellungen",
    "Privacy Settings": "Datenschutzeinstellungen",
    "Notifications": "Benachrichtigungen",
    "Email Preferences": "E-Mail-Einstellungen",
    "Connected Accounts": "Verknüpfte Konten",
    "Delete Account": "Konto löschen",
    "Profile Photo": "Profilbild",
    "Upload Photo": "Foto hochladen",
    "Remove Photo": "Foto entfernen",
    "Photos": "Fotos",
    "Profile Status": "Profilstatus",
    "Create Your Profile": "Erstellen Sie Ihr Profil",
    "Create Your Profile Now": "Jetzt Profil erstellen",
    "Required": "Erforderlich",
    "Verified": "Verifiziert",
    "Unverified": "Nicht verifiziert",
    "Primary": "Primär",
    "Make Primary": "Als primär festlegen",
    "Re-send Verification": "Verifizierung erneut senden",
    "Resend verification": "Verifizierung erneut senden",
    "Add E-mail": "E-Mail hinzufügen",

    # Events
    "Upcoming Events": "Kommende Veranstaltungen",
    "Past Events": "Vergangene Veranstaltungen",
    "My Events": "Meine Veranstaltungen",
    "Your Events": "Ihre Veranstaltungen",
    "Event Details": "Veranstaltungsdetails",
    "Register for Event": "Für Veranstaltung anmelden",
    "Cancel Registration": "Anmeldung stornieren",
    "Event Date": "Veranstaltungsdatum",
    "Event Time": "Veranstaltungszeit",
    "Event Location": "Veranstaltungsort",
    "Participants": "Teilnehmer",
    "Spots Available": "Verfügbare Plätze",
    "Full": "Ausgebucht",
    "Waitlist": "Warteliste",
    "Registered": "Angemeldet",
    "Confirmed": "Bestätigt",
    "Pending": "Ausstehend",
    "Cancelled": "Abgesagt",
    "Attended": "Teilgenommen",
    "Speed Dating": "Speed Dating",
    "Mixer": "Mixer",
    "Activity": "Aktivität",
    "Date": "Datum",
    "Time": "Uhrzeit",
    "Price": "Preis",
    "Free": "Kostenlos",
    "Registration": "Anmeldung",
    "Registration Fee": "Anmeldegebühr",
    "Register Now": "Jetzt anmelden",
    "Join Waitlist": "Auf Warteliste setzen",
    "Leave Waitlist": "Warteliste verlassen",
    "Join Events": "Veranstaltungen beitreten",

    # Connections
    "Connections": "Verbindungen",
    "My Connections": "Meine Verbindungen",
    "Connection Request": "Verbindungsanfrage",
    "Accept": "Annehmen",
    "Decline": "Ablehnen",
    "Connected": "Verbunden",
    "Message": "Nachricht",
    "Messages": "Nachrichten",
    "Send Message": "Nachricht senden",
    "New Message": "Neue Nachricht",
    "No messages yet": "Noch keine Nachrichten",
    "Connect": "Verbinden",
    "Make Connections": "Verbindungen knüpfen",

    # Voting
    "Vote": "Abstimmen",
    "Voting": "Abstimmung",
    "Results": "Ergebnisse",
    "Submit Vote": "Stimme abgeben",
    "Voting Results": "Abstimmungsergebnisse",
    "Winner": "Gewinner",

    # Coach/Admin
    "Coach Dashboard": "Coach Dashboard",
    "Review Profile": "Profil überprüfen",
    "Approve": "Genehmigen",
    "Reject": "Ablehnen",
    "Request Revision": "Überarbeitung anfordern",
    "Feedback": "Feedback",
    "Feedback:": "Feedback:",
    "Notes": "Notizen",
    "Status": "Status",
    "Status:": "Status:",
    "Approved": "Genehmigt",
    "Rejected": "Abgelehnt",
    "Under Review": "In Prüfung",
    "Site administration": "Website-Verwaltung",
    "Crush.lu Coach Panel": "Crush.lu Coach-Panel",
    "Recent actions": "Letzte Aktionen",
    "My actions": "Meine Aktionen",
    "None available": "Keine verfügbar",
    "Unknown content": "Unbekannter Inhalt",

    # Cookie Banner
    "Cookie Settings": "Cookie-Einstellungen",
    "Customize": "Anpassen",
    "Decline All": "Alle ablehnen",
    "Accept All": "Alle akzeptieren",
    "Cookie Preferences": "Cookie-Einstellungen",
    "Essential Cookies": "Notwendige Cookies",
    "Always Active": "Immer aktiv",
    "Analytics Cookies": "Analyse-Cookies",
    "Marketing Cookies": "Marketing-Cookies",
    "Save Preferences": "Einstellungen speichern",

    # Footer & Legal
    "Privacy Policy": "Datenschutzrichtlinie",
    "Terms of Service": "Nutzungsbedingungen",
    "Terms and Conditions": "Allgemeine Geschäftsbedingungen",
    "Contact": "Kontakt",
    "Contact Us": "Kontakt",
    "Help": "Hilfe",
    "FAQ": "FAQ",
    "Support": "Support",
    "About Us": "Über uns",
    "How It Works": "So funktioniert's",
    "All rights reserved": "Alle Rechte vorbehalten",

    # Forms & Validation
    "Optional": "Optional",
    "This field is required.": "Dieses Feld ist erforderlich.",
    "Please enter a valid email address.": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "Password is too short.": "Passwort ist zu kurz.",
    "Invalid input.": "Ungültige Eingabe.",
    "Must be 18+ to join": "Sie müssen 18+ sein, um beizutreten",
    "Date of birth cannot be in the future": "Geburtsdatum darf nicht in der Zukunft liegen",
    "You must be at least 18 years old to join Crush.lu": "Sie müssen mindestens 18 Jahre alt sein, um Crush.lu beizutreten",
    "Please enter a valid date of birth": "Bitte geben Sie ein gültiges Geburtsdatum ein",
    "Select your region...": "Wählen Sie Ihre Region...",
    "Your region in or near Luxembourg": "Ihre Region in oder nahe Luxemburg",
    "Required for coach screening and event coordination": "Erforderlich für Coach-Screening und Veranstaltungskoordination",

    # Time & Date
    "Today": "Heute",
    "Tomorrow": "Morgen",
    "Yesterday": "Gestern",
    "This week": "Diese Woche",
    "Next week": "Nächste Woche",
    "This month": "Diesen Monat",
    "Next month": "Nächsten Monat",

    # Dashboard & Notifications
    "Your Activity": "Ihre Aktivität",
    "How to install": "So installieren Sie",
    "Enable Notifications": "Benachrichtigungen aktivieren",
    "Disable": "Deaktivieren",
    "Send Test": "Test senden",
    "Checking notification status...": "Benachrichtigungsstatus wird überprüft...",
    "Push notifications not available": "Push-Benachrichtigungen nicht verfügbar",
    "Install App": "App installieren",
    "App installed!": "App installiert!",
    "Verify Now": "Jetzt verifizieren",
    "Phone verification required!": "Telefonverifizierung erforderlich!",
    "Please verify your phone number to access all features.": "Bitte verifizieren Sie Ihre Telefonnummer, um alle Funktionen nutzen zu können.",
    "Get notified about events, messages, and connections": "Erhalten Sie Benachrichtigungen über Veranstaltungen, Nachrichten und Verbindungen",
    "Ready to Meet New People?": "Bereit, neue Leute kennenzulernen?",
    "Check out our upcoming events and start making connections!": "Entdecken Sie unsere kommenden Veranstaltungen und knüpfen Sie Kontakte!",
    "You haven't registered for any events yet.": "Sie haben sich noch für keine Veranstaltungen angemeldet.",

    # Crush.lu Home Page
    "Meet New People.": "Neue Leute kennenlernen.",
    "Make Real Connections.": "Echte Verbindungen knüpfen.",
    "Get Started": "Loslegen",
    "Get Started Free": "Kostenlos starten",
    "Why Choose Crush.lu": "Warum Crush.lu wählen",
    "Privacy First": "Datenschutz an erster Stelle",
    "Real Events": "Echte Veranstaltungen",
    "Guided Support": "Geführte Unterstützung",
    "Get Coach Approval": "Coach-Genehmigung erhalten",
    "Ready to Meet Your Crush?": "Bereit, deinen Crush zu treffen?",
    "Learn More About Our Process": "Mehr über unseren Prozess erfahren",
    "No credit card required • Free to join • Cancel anytime": "Keine Kreditkarte erforderlich • Kostenlos beitreten • Jederzeit kündigen",
    "Welcome to Crush.lu": "Willkommen bei Crush.lu",
    "Privacy-First Dating": "Datenschutz-zuerst Dating",
    "Find Your Crush": "Finde dein Crush",
    "Meet in Person": "Persönlich treffen",
    "Browse Other Events": "Andere Veranstaltungen ansehen",
    "Profile submitted": "Profil eingereicht",
    "Profile approved": "Profil genehmigt",
    "Your profile is under review": "Dein Profil wird überprüft",
    "We will contact you soon": "Wir werden uns bald bei dir melden",
    "Thank you for signing up": "Vielen Dank für deine Anmeldung",

    # Language Names
    "English": "Englisch",
    "German": "Deutsch",
    "French": "Französisch",

    # Admin
    "Django site admin": "Django Website-Verwaltung",
    "Django administration": "Django-Verwaltung",
    "Crush Delegation Management": "Crush Delegationsverwaltung",

    # OAuth/Social
    "Or": "Oder",
    "or": "oder",
    "Continue with": "Fortfahren mit",
    "Errors:": "Fehler:",
    "Error details:": "Fehlerdetails:",
    "This can happen if:": "Dies kann passieren, wenn:",
    "You cancelled the login on the provider's site": "Sie die Anmeldung auf der Anbieterseite abgebrochen haben",
    "Your email is already registered with a different login method": "Ihre E-Mail bereits mit einer anderen Anmeldemethode registriert ist",
    "There was a temporary connection issue": "Es ein vorübergehendes Verbindungsproblem gab",

    # Success/Error Messages
    "Email preferences updated successfully!": "E-Mail-Einstellungen erfolgreich aktualisiert!",
    "Profile updated successfully!": "Profil erfolgreich aktualisiert!",
    "Profile submitted for review!": "Profil zur Überprüfung eingereicht!",
    "Successfully registered for the event!": "Erfolgreich für die Veranstaltung angemeldet!",
    "Your registration has been cancelled.": "Ihre Anmeldung wurde storniert.",
    "Event is full. You have been added to the waitlist.": "Veranstaltung ist voll. Sie wurden auf die Warteliste gesetzt.",
    "You are already registered for this event.": "Sie sind bereits für diese Veranstaltung angemeldet.",
    "Registration is not available for this event.": "Anmeldung für diese Veranstaltung nicht verfügbar.",
    "You need to create a profile first.": "Sie müssen zuerst ein Profil erstellen.",
    "Your profile must be approved before editing.": "Ihr Profil muss genehmigt werden, bevor Sie es bearbeiten können.",
    "Your account has been successfully deleted.": "Ihr Konto wurde erfolgreich gelöscht.",
    "Incorrect password. Please try again.": "Falsches Passwort. Bitte versuchen Sie es erneut.",
    "Are you sure you want to sign out?": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "No events found": "Keine Veranstaltungen gefunden",
    "No results found": "Keine Ergebnisse gefunden",
    "Something went wrong": "Etwas ist schief gelaufen",
    "Please try again": "Bitte versuchen Sie es erneut",
    "Please try again later": "Bitte versuchen Sie es später erneut",

    # Canton Map
    "Select your region on the map": "Wählen Sie Ihre Region auf der Karte",
    "Luxembourg Canton Selection Map": "Luxemburg Kanton Auswahlkarte",
    "Border regions": "Grenzregionen",
    "Luxembourg cantons": "Luxemburger Kantone",
    "Belgium (Arlon area)": "Belgien (Raum Arlon)",
    "Germany (Trier/Saarland area)": "Deutschland (Raum Trier/Saarland)",
    "France (Thionville/Metz area)": "Frankreich (Raum Thionville/Metz)",

    # Email Related
    "Need a new verification email?": "Benötigen Sie eine neue Verifizierungs-E-Mail?",
    "Please verify your email address to access all features.": "Bitte verifizieren Sie Ihre E-Mail-Adresse, um alle Funktionen nutzen zu können.",
    "The following e-mail addresses are associated with your account:": "Die folgenden E-Mail-Adressen sind mit Ihrem Konto verknüpft:",
    "Do you really want to remove the selected email address?": "Möchten Sie die ausgewählte E-Mail-Adresse wirklich entfernen?",

    # VinsDelux
    "Products": "Produkte",
    "Wine Coffrets": "Wein-Coffrets",
    "Producers": "Produzenten",
    "Your Journey": "Ihre Reise",
    "Plot Selection": "Parzellenauswahl",
    "Select Your Vineyard Plot": "Wählen Sie Ihre Weinbergparzelle",
    "Personalize Your Wine": "Personalisieren Sie Ihren Wein",
    "Follow Production": "Produktion verfolgen",
    "Create Legacy": "Vermächtnis schaffen",
    "Cart": "Warenkorb",
    "Account": "Konto",
    "Available": "Verfügbar",
    "Reserved": "Reserviert",
    "Unavailable": "Nicht verfügbar",
    "Adopted": "Adoptiert",
    "Size": "Größe",
    "Elevation": "Höhe",
    "Soil Type": "Bodentyp",
    "Exposure": "Ausrichtung",
    "Sun Exposure": "Sonneneinstrahlung",
    "Grape Varieties": "Rebsorten",
    "Wine Character": "Weincharakter",
    "Special Features": "Besondere Merkmale",
    "Starting from": "Ab",
    "/year": "/Jahr",
    "per year": "pro Jahr",
    "Quality Rating": "Qualitätsbewertung",
    "Select This Plot": "Diese Parzelle auswählen",
    "Currently Unavailable": "Derzeit nicht verfügbar",
    "Add to Selection": "Zur Auswahl hinzufügen",
    "Your Selection": "Ihre Auswahl",
    "Selected Plots": "Ausgewählte Parzellen",
    "plots": "Parzellen",
    "plots selected": "Parzellen ausgewählt",
    "Plot Details": "Parzellendetails",
    "Click on a plot to begin your selection": "Klicken Sie auf eine Parzelle, um Ihre Auswahl zu beginnen",
    "Confirm Adoption": "Adoption bestätigen",
    "Confirm Selection & Continue": "Auswahl bestätigen & fortfahren",
    "Total Annual Cost": "Jährliche Gesamtkosten",
    "Your Selection Summary": "Zusammenfassung Ihrer Auswahl",
    "Confirm Your Vineyard Selection": "Bestätigen Sie Ihre Weinbergauswahl",
    "Choose Your Plan": "Wählen Sie Ihren Plan",
    "Personal Details": "Persönliche Daten",
    "Step": "Schritt",
    "Your Progress": "Ihr Fortschritt",
    "Bronze": "Bronze",
    "Silver": "Silber",
    "Gold": "Gold",
    "Premier": "Premium",
    "Browse Wine Coffrets": "Wein-Coffrets durchsuchen",
    "Meet Our Producers": "Unsere Produzenten kennenlernen",
    "Discover Vinsdelux": "Vinsdelux entdecken",
    "Explore Vineyards": "Weinberge erkunden",

    # Entreprinder
    "Collaborate": "Zusammenarbeiten",
    "Grow": "Wachsen",
    "Join Now": "Jetzt beitreten",
    "Find Entrepreneurs": "Unternehmer finden",
    "Why Choose Entreprinder?": "Warum Entreprinder wählen?",
    "Welcome to Entreprinder": "Willkommen bei Entreprinder",
    "Return Home": "Zur Startseite zurückkehren",
    "View Your Matches": "Ihre Matches ansehen",
    "No More Profiles Available": "Keine weiteren Profile verfügbar",

    # Progress/Status
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Loading activity...": "Aktivität wird geladen...",

    # Complete Signup
    "Complete Your Signup": "Registrierung abschließen",
    "Complete Signup": "Registrierung abschließen",
    "Company": "Unternehmen",
    "Guest": "Gast",
    "Member": "Mitglied",
    "Controls": "Steuerung",
    "Stats": "Statistiken",
    "Your Stats": "Ihre Statistiken",
}

# French translations dictionary - comprehensive
FR_TRANSLATIONS = {
    # Navigation & Common UI
    "Home": "Accueil",
    "About": "À propos",
    "Events": "Événements",
    "Dashboard": "Tableau de bord",
    "Profile": "Profil",
    "Settings": "Paramètres",
    "Login": "Connexion",
    "Logout": "Déconnexion",
    "Sign Up": "S'inscrire",
    "Sign In": "Se connecter",
    "Sign Out": "Se déconnecter",
    "Register": "S'inscrire",
    "Submit": "Envoyer",
    "Cancel": "Annuler",
    "Save": "Enregistrer",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Close": "Fermer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Sort": "Trier",
    "View": "Voir",
    "Add": "Ajouter",
    "Remove": "Supprimer",
    "Change": "Modifier",
    "Download": "Télécharger",
    "Upload": "Téléverser",
    "Loading...": "Chargement...",
    "Loading": "Chargement",
    "Error": "Erreur",
    "Success": "Succès",
    "Warning": "Avertissement",
    "Info": "Info",
    "Yes": "Oui",
    "No": "Non",
    "OK": "OK",
    "Confirm": "Confirmer",
    "Continue": "Continuer",
    "Learn More": "En savoir plus",
    "Read More": "Lire la suite",
    "See All": "Voir tout",
    "Show More": "Afficher plus",
    "Show Less": "Afficher moins",
    "Go": "Aller",
    "Go Back": "Retour",
    "Language": "Langue",
    "View Details": "Voir les détails",
    "View All Events": "Voir tous les événements",
    "View Event": "Voir l'événement",
    "View Upcoming Events": "Voir les événements à venir",
    "Browse Events": "Parcourir les événements",

    # Authentication
    "Email": "E-mail",
    "E-mail": "E-mail",
    "Password": "Mot de passe",
    "Confirm Password": "Confirmer le mot de passe",
    "New Password": "Nouveau mot de passe",
    "Enter new password": "Entrer le nouveau mot de passe",
    "Confirm new password": "Confirmer le nouveau mot de passe",
    "Password (again)": "Mot de passe (encore)",
    "Remember me": "Se souvenir de moi",
    "Forgot Password?": "Mot de passe oublié ?",
    "Reset Password": "Réinitialiser le mot de passe",
    "Password Reset": "Réinitialisation du mot de passe",
    "Reset My Password": "Réinitialiser mon mot de passe",
    "Change Password": "Changer le mot de passe",
    "First Name": "Prénom",
    "Last Name": "Nom",
    "Username": "Nom d'utilisateur",
    "Phone": "Téléphone",
    "Phone Number": "Numéro de téléphone",
    "Date of Birth": "Date de naissance",
    "Age": "Âge",
    "Gender": "Genre",
    "Male": "Homme",
    "Female": "Femme",
    "Other": "Autre",
    "Location": "Localisation",
    "City": "Ville",
    "Country": "Pays",
    "Bio": "Bio",
    "About me": "À propos de moi",
    "Interests": "Intérêts",
    "Sign in with LinkedIn": "Se connecter avec LinkedIn",
    "Sign in with Google": "Se connecter avec Google",
    "Sign in with Facebook": "Se connecter avec Facebook",
    "Already have an account?": "Vous avez déjà un compte ?",
    "Don't have an account?": "Vous n'avez pas de compte ?",
    "Login here": "Se connecter ici",
    "Third-Party Login Error": "Erreur de connexion tierce",
    "Back to Login": "Retour à la connexion",
    "Create New Account": "Créer un nouveau compte",
    "Your password must be at least 8 characters.": "Votre mot de passe doit contenir au moins 8 caractères.",
    "Passwords do not match.": "Les mots de passe ne correspondent pas.",

    # Profile & Account
    "My Profile": "Mon profil",
    "Edit Profile": "Modifier le profil",
    "View Profile": "Voir le profil",
    "Account Settings": "Paramètres du compte",
    "Privacy Settings": "Paramètres de confidentialité",
    "Notifications": "Notifications",
    "Email Preferences": "Préférences e-mail",
    "Connected Accounts": "Comptes connectés",
    "Delete Account": "Supprimer le compte",
    "Profile Photo": "Photo de profil",
    "Upload Photo": "Téléverser une photo",
    "Remove Photo": "Supprimer la photo",
    "Photos": "Photos",
    "Profile Status": "Statut du profil",
    "Create Your Profile": "Créez votre profil",
    "Create Your Profile Now": "Créer votre profil maintenant",
    "Required": "Requis",
    "Verified": "Vérifié",
    "Unverified": "Non vérifié",
    "Primary": "Principal",
    "Make Primary": "Définir comme principal",
    "Re-send Verification": "Renvoyer la vérification",
    "Resend verification": "Renvoyer la vérification",
    "Add E-mail": "Ajouter un e-mail",

    # Events
    "Upcoming Events": "Événements à venir",
    "Past Events": "Événements passés",
    "My Events": "Mes événements",
    "Your Events": "Vos événements",
    "Event Details": "Détails de l'événement",
    "Register for Event": "S'inscrire à l'événement",
    "Cancel Registration": "Annuler l'inscription",
    "Event Date": "Date de l'événement",
    "Event Time": "Heure de l'événement",
    "Event Location": "Lieu de l'événement",
    "Participants": "Participants",
    "Spots Available": "Places disponibles",
    "Full": "Complet",
    "Waitlist": "Liste d'attente",
    "Registered": "Inscrit",
    "Confirmed": "Confirmé",
    "Pending": "En attente",
    "Cancelled": "Annulé",
    "Attended": "Participé",
    "Speed Dating": "Speed Dating",
    "Mixer": "Soirée de rencontre",
    "Activity": "Activité",
    "Date": "Date",
    "Time": "Heure",
    "Price": "Prix",
    "Free": "Gratuit",
    "Registration": "Inscription",
    "Registration Fee": "Frais d'inscription",
    "Register Now": "S'inscrire maintenant",
    "Join Waitlist": "Rejoindre la liste d'attente",
    "Leave Waitlist": "Quitter la liste d'attente",
    "Join Events": "Rejoindre les événements",

    # Connections
    "Connections": "Connexions",
    "My Connections": "Mes connexions",
    "Connection Request": "Demande de connexion",
    "Accept": "Accepter",
    "Decline": "Refuser",
    "Connected": "Connecté",
    "Message": "Message",
    "Messages": "Messages",
    "Send Message": "Envoyer un message",
    "New Message": "Nouveau message",
    "No messages yet": "Pas encore de messages",
    "Connect": "Connecter",
    "Make Connections": "Créer des connexions",

    # Voting
    "Vote": "Voter",
    "Voting": "Vote",
    "Results": "Résultats",
    "Submit Vote": "Soumettre le vote",
    "Voting Results": "Résultats du vote",
    "Winner": "Gagnant",

    # Coach/Admin
    "Coach Dashboard": "Tableau de bord coach",
    "Review Profile": "Examiner le profil",
    "Approve": "Approuver",
    "Reject": "Rejeter",
    "Request Revision": "Demander une révision",
    "Feedback": "Commentaires",
    "Feedback:": "Commentaires :",
    "Notes": "Notes",
    "Status": "Statut",
    "Status:": "Statut :",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Under Review": "En cours d'examen",
    "Site administration": "Administration du site",
    "Crush.lu Coach Panel": "Panel Coach Crush.lu",
    "Recent actions": "Actions récentes",
    "My actions": "Mes actions",
    "None available": "Aucun disponible",
    "Unknown content": "Contenu inconnu",

    # Cookie Banner
    "Cookie Settings": "Paramètres des cookies",
    "Customize": "Personnaliser",
    "Decline All": "Tout refuser",
    "Accept All": "Tout accepter",
    "Cookie Preferences": "Préférences de cookies",
    "Essential Cookies": "Cookies essentiels",
    "Always Active": "Toujours actif",
    "Analytics Cookies": "Cookies analytiques",
    "Marketing Cookies": "Cookies marketing",
    "Save Preferences": "Enregistrer les préférences",

    # Footer & Legal
    "Privacy Policy": "Politique de confidentialité",
    "Terms of Service": "Conditions d'utilisation",
    "Terms and Conditions": "Conditions générales",
    "Contact": "Contact",
    "Contact Us": "Nous contacter",
    "Help": "Aide",
    "FAQ": "FAQ",
    "Support": "Assistance",
    "About Us": "À propos de nous",
    "How It Works": "Comment ça marche",
    "All rights reserved": "Tous droits réservés",

    # Forms & Validation
    "Optional": "Facultatif",
    "This field is required.": "Ce champ est obligatoire.",
    "Please enter a valid email address.": "Veuillez entrer une adresse e-mail valide.",
    "Password is too short.": "Le mot de passe est trop court.",
    "Invalid input.": "Entrée invalide.",
    "Must be 18+ to join": "Vous devez avoir 18 ans ou plus pour vous inscrire",
    "Date of birth cannot be in the future": "La date de naissance ne peut pas être dans le futur",
    "You must be at least 18 years old to join Crush.lu": "Vous devez avoir au moins 18 ans pour rejoindre Crush.lu",
    "Please enter a valid date of birth": "Veuillez entrer une date de naissance valide",
    "Select your region...": "Sélectionnez votre région...",
    "Your region in or near Luxembourg": "Votre région au Luxembourg ou à proximité",
    "Required for coach screening and event coordination": "Requis pour l'évaluation du coach et la coordination des événements",

    # Time & Date
    "Today": "Aujourd'hui",
    "Tomorrow": "Demain",
    "Yesterday": "Hier",
    "This week": "Cette semaine",
    "Next week": "Semaine prochaine",
    "This month": "Ce mois-ci",
    "Next month": "Mois prochain",

    # Dashboard & Notifications
    "Your Activity": "Votre activité",
    "How to install": "Comment installer",
    "Enable Notifications": "Activer les notifications",
    "Disable": "Désactiver",
    "Send Test": "Envoyer un test",
    "Checking notification status...": "Vérification du statut des notifications...",
    "Push notifications not available": "Notifications push non disponibles",
    "Install App": "Installer l'application",
    "App installed!": "Application installée !",
    "Verify Now": "Vérifier maintenant",
    "Phone verification required!": "Vérification téléphonique requise !",
    "Please verify your phone number to access all features.": "Veuillez vérifier votre numéro de téléphone pour accéder à toutes les fonctionnalités.",
    "Get notified about events, messages, and connections": "Soyez notifié des événements, messages et connexions",
    "Ready to Meet New People?": "Prêt à rencontrer de nouvelles personnes ?",
    "Check out our upcoming events and start making connections!": "Découvrez nos événements à venir et commencez à créer des connexions !",
    "You haven't registered for any events yet.": "Vous n'êtes encore inscrit à aucun événement.",

    # Crush.lu Home Page
    "Meet New People.": "Rencontrez de nouvelles personnes.",
    "Make Real Connections.": "Créez de vraies connexions.",
    "Get Started": "Commencer",
    "Get Started Free": "Commencer gratuitement",
    "Why Choose Crush.lu": "Pourquoi choisir Crush.lu",
    "Privacy First": "Confidentialité d'abord",
    "Real Events": "Vrais événements",
    "Guided Support": "Accompagnement guidé",
    "Get Coach Approval": "Obtenir l'approbation du coach",
    "Ready to Meet Your Crush?": "Prêt à rencontrer votre crush ?",
    "Learn More About Our Process": "En savoir plus sur notre processus",
    "No credit card required • Free to join • Cancel anytime": "Pas de carte de crédit requise • Inscription gratuite • Annulez à tout moment",
    "Welcome to Crush.lu": "Bienvenue sur Crush.lu",
    "Privacy-First Dating": "Rencontres respectueuses de la vie privée",
    "Find Your Crush": "Trouvez votre crush",
    "Meet in Person": "Rencontrez en personne",
    "Browse Other Events": "Voir d'autres événements",
    "Profile submitted": "Profil soumis",
    "Profile approved": "Profil approuvé",
    "Your profile is under review": "Votre profil est en cours d'examen",
    "We will contact you soon": "Nous vous contacterons bientôt",
    "Thank you for signing up": "Merci de vous être inscrit",

    # Language Names
    "English": "Anglais",
    "German": "Allemand",
    "French": "Français",

    # Admin
    "Django site admin": "Administration du site Django",
    "Django administration": "Administration Django",
    "Crush Delegation Management": "Gestion de la délégation Crush",

    # OAuth/Social
    "Or": "Ou",
    "or": "ou",
    "Continue with": "Continuer avec",
    "Errors:": "Erreurs :",
    "Error details:": "Détails de l'erreur :",
    "This can happen if:": "Cela peut arriver si :",
    "You cancelled the login on the provider's site": "Vous avez annulé la connexion sur le site du fournisseur",
    "Your email is already registered with a different login method": "Votre e-mail est déjà enregistré avec une autre méthode de connexion",
    "There was a temporary connection issue": "Il y a eu un problème de connexion temporaire",

    # Success/Error Messages
    "Email preferences updated successfully!": "Préférences e-mail mises à jour avec succès !",
    "Profile updated successfully!": "Profil mis à jour avec succès !",
    "Profile submitted for review!": "Profil soumis pour examen !",
    "Successfully registered for the event!": "Inscription à l'événement réussie !",
    "Your registration has been cancelled.": "Votre inscription a été annulée.",
    "Event is full. You have been added to the waitlist.": "L'événement est complet. Vous avez été ajouté à la liste d'attente.",
    "You are already registered for this event.": "Vous êtes déjà inscrit à cet événement.",
    "Registration is not available for this event.": "L'inscription n'est pas disponible pour cet événement.",
    "You need to create a profile first.": "Vous devez d'abord créer un profil.",
    "Your profile must be approved before editing.": "Votre profil doit être approuvé avant de pouvoir être modifié.",
    "Your account has been successfully deleted.": "Votre compte a été supprimé avec succès.",
    "Incorrect password. Please try again.": "Mot de passe incorrect. Veuillez réessayer.",
    "Are you sure you want to sign out?": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "No events found": "Aucun événement trouvé",
    "No results found": "Aucun résultat trouvé",
    "Something went wrong": "Une erreur s'est produite",
    "Please try again": "Veuillez réessayer",
    "Please try again later": "Veuillez réessayer plus tard",

    # Canton Map
    "Select your region on the map": "Sélectionnez votre région sur la carte",
    "Luxembourg Canton Selection Map": "Carte de sélection des cantons du Luxembourg",
    "Border regions": "Régions frontalières",
    "Luxembourg cantons": "Cantons du Luxembourg",
    "Belgium (Arlon area)": "Belgique (région d'Arlon)",
    "Germany (Trier/Saarland area)": "Allemagne (région de Trèves/Sarre)",
    "France (Thionville/Metz area)": "France (région de Thionville/Metz)",

    # Email Related
    "Need a new verification email?": "Besoin d'un nouvel e-mail de vérification ?",
    "Please verify your email address to access all features.": "Veuillez vérifier votre adresse e-mail pour accéder à toutes les fonctionnalités.",
    "The following e-mail addresses are associated with your account:": "Les adresses e-mail suivantes sont associées à votre compte :",
    "Do you really want to remove the selected email address?": "Voulez-vous vraiment supprimer l'adresse e-mail sélectionnée ?",

    # VinsDelux
    "Products": "Produits",
    "Wine Coffrets": "Coffrets de vin",
    "Producers": "Producteurs",
    "Your Journey": "Votre parcours",
    "Plot Selection": "Sélection de parcelle",
    "Select Your Vineyard Plot": "Sélectionnez votre parcelle de vignoble",
    "Personalize Your Wine": "Personnalisez votre vin",
    "Follow Production": "Suivre la production",
    "Create Legacy": "Créer un héritage",
    "Cart": "Panier",
    "Account": "Compte",
    "Available": "Disponible",
    "Reserved": "Réservé",
    "Unavailable": "Non disponible",
    "Adopted": "Adopté",
    "Size": "Taille",
    "Elevation": "Altitude",
    "Soil Type": "Type de sol",
    "Exposure": "Exposition",
    "Sun Exposure": "Exposition au soleil",
    "Grape Varieties": "Cépages",
    "Wine Character": "Caractère du vin",
    "Special Features": "Caractéristiques spéciales",
    "Starting from": "À partir de",
    "/year": "/an",
    "per year": "par an",
    "Quality Rating": "Note de qualité",
    "Select This Plot": "Sélectionner cette parcelle",
    "Currently Unavailable": "Actuellement non disponible",
    "Add to Selection": "Ajouter à la sélection",
    "Your Selection": "Votre sélection",
    "Selected Plots": "Parcelles sélectionnées",
    "plots": "parcelles",
    "plots selected": "parcelles sélectionnées",
    "Plot Details": "Détails de la parcelle",
    "Click on a plot to begin your selection": "Cliquez sur une parcelle pour commencer votre sélection",
    "Confirm Adoption": "Confirmer l'adoption",
    "Confirm Selection & Continue": "Confirmer la sélection et continuer",
    "Total Annual Cost": "Coût annuel total",
    "Your Selection Summary": "Résumé de votre sélection",
    "Confirm Your Vineyard Selection": "Confirmez votre sélection de vignoble",
    "Choose Your Plan": "Choisissez votre plan",
    "Personal Details": "Informations personnelles",
    "Step": "Étape",
    "Your Progress": "Votre progression",
    "Bronze": "Bronze",
    "Silver": "Argent",
    "Gold": "Or",
    "Premier": "Premium",
    "Browse Wine Coffrets": "Parcourir les coffrets de vin",
    "Meet Our Producers": "Rencontrez nos producteurs",
    "Discover Vinsdelux": "Découvrez Vinsdelux",
    "Explore Vineyards": "Explorer les vignobles",

    # Entreprinder
    "Collaborate": "Collaborer",
    "Grow": "Croître",
    "Join Now": "Rejoindre maintenant",
    "Find Entrepreneurs": "Trouver des entrepreneurs",
    "Why Choose Entreprinder?": "Pourquoi choisir Entreprinder ?",
    "Welcome to Entreprinder": "Bienvenue sur Entreprinder",
    "Return Home": "Retour à l'accueil",
    "View Your Matches": "Voir vos correspondances",
    "No More Profiles Available": "Plus de profils disponibles",

    # Progress/Status
    "Active": "Actif",
    "Inactive": "Inactif",
    "Loading activity...": "Chargement de l'activité...",

    # Complete Signup
    "Complete Your Signup": "Terminer votre inscription",
    "Complete Signup": "Terminer l'inscription",
    "Company": "Entreprise",
    "Guest": "Invité",
    "Member": "Membre",
    "Controls": "Contrôles",
    "Stats": "Statistiques",
    "Your Stats": "Vos statistiques",
}


def translate_po_file(po_path: Path, translations: dict) -> int:
    """
    Translate a .po file using the provided translations dictionary.
    Returns the number of strings translated.
    """
    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    translated_count = 0
    lines = content.split('\n')
    new_lines = []
    i = 0

    while i < len(lines):
        line = lines[i]

        # Check if this is a msgid line
        if line.startswith('msgid "') and not line.startswith('msgid ""'):
            # Extract the English string
            msgid_match = re.match(r'msgid "(.+)"', line)
            if msgid_match:
                english_text = msgid_match.group(1)

                # Check if next line is msgstr ""
                if i + 1 < len(lines):
                    next_line = lines[i + 1]
                    if next_line == 'msgstr ""':
                        # Check if we have a translation
                        if english_text in translations:
                            new_lines.append(line)
                            new_lines.append(f'msgstr "{translations[english_text]}"')
                            translated_count += 1
                            i += 2
                            continue

        new_lines.append(line)
        i += 1

    # Write the updated content
    with open(po_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_lines))

    return translated_count


def main():
    base_path = Path(__file__).parent.parent / 'locale'

    # Translate German
    de_path = base_path / 'de' / 'LC_MESSAGES' / 'django.po'
    if de_path.exists():
        count = translate_po_file(de_path, DE_TRANSLATIONS)
        print(f"German: Translated {count} strings")
    else:
        print(f"German .po file not found: {de_path}")

    # Translate French
    fr_path = base_path / 'fr' / 'LC_MESSAGES' / 'django.po'
    if fr_path.exists():
        count = translate_po_file(fr_path, FR_TRANSLATIONS)
        print(f"French: Translated {count} strings")
    else:
        print(f"French .po file not found: {fr_path}")

    print("\nDone! Now run: python manage.py compilemessages")


if __name__ == '__main__':
    main()
