# Generated by Django 5.1 on 2025-10-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('speed_dating', 'Speed Dating'), ('mixer', 'Social Mixer'), ('activity', 'Activity Meetup'), ('themed', 'Themed Event')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=99)),
                ('registration_deadline', models.DateTimeField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Event fee in EUR', max_digits=6)),
                ('is_published', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='CrushCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('specializations', models.CharField(blank=True, help_text='e.g., Young professionals, Students, 30+, etc.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_active_reviews', models.PositiveIntegerField(default=10, help_text='Maximum number of profiles this coach can review simultaneously')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('onboarding', 'Onboarding Session'), ('feedback', 'Profile Feedback'), ('guidance', 'Dating Guidance'), ('followup', 'Follow-up')], max_length=20)),
                ('notes', models.TextField(help_text='Session notes and key points discussed')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.crushcoach')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrushProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(help_text='City/Region in Luxembourg', max_length=100)),
                ('bio', models.TextField(help_text='Tell us about yourself!', max_length=500)),
                ('interests', models.TextField(help_text='Your hobbies and interests (comma-separated)', max_length=300)),
                ('looking_for', models.CharField(choices=[('friends', 'New Friends'), ('dating', 'Dating'), ('both', 'Both'), ('networking', 'Social Networking')], default='friends', max_length=20)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='crush_profiles/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='crush_profiles/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='crush_profiles/')),
                ('show_full_name', models.BooleanField(default=False, help_text='Show full name (if false, only first name is shown)')),
                ('show_exact_age', models.BooleanField(default=True, help_text='Show exact age (if false, show age range)')),
                ('blur_photos', models.BooleanField(default=False, help_text='Blur photos until mutual interest')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Needs Revision')], default='pending', max_length=20)),
                ('coach_notes', models.TextField(blank=True, help_text='Internal notes from coach')),
                ('feedback_to_user', models.TextField(blank=True, help_text='Feedback shown to user if revision needed')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crush_lu.crushcoach')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.crushprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=200)),
                ('special_requests', models.TextField(blank=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.meetupevent')),
            ],
            options={
                'ordering': ['registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
