# Generated by Django 5.1 on 2025-10-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('coach_reviewing', 'Coach Reviewing'), ('coach_approved', 'Coach Approved - Ready to Share'), ('shared', 'Contact Info Shared')], default='pending', max_length=20)),
                ('requester_note', models.TextField(blank=True, help_text='Optional note: What did you talk about? What interested you?', max_length=300)),
                ('coach_notes', models.TextField(blank=True, help_text="Coach's guidance for the introduction")),
                ('coach_introduction', models.TextField(blank=True, help_text='Personalized introduction message from coach')),
                ('requester_consents_to_share', models.BooleanField(default=False, help_text='Requester agrees to share contact info')),
                ('recipient_consents_to_share', models.BooleanField(default=False, help_text='Recipient agrees to share contact info')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('coach_approved_at', models.DateTimeField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_coach', models.ForeignKey(blank=True, help_text='Coach who will facilitate this connection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crush_lu.crushcoach')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.meetupevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('requester', 'recipient', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ConnectionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('is_coach_message', models.BooleanField(default=False, help_text='True if sent by the coach')),
                ('coach_approved', models.BooleanField(default=True, help_text='Coach can moderate messages if needed')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crush_lu.eventconnection')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
