# Generated by Django 5.1 on 2025-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0002_eventconnection_connectionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='crushprofile',
            name='completion_status',
            field=models.CharField(choices=[('step1', 'Step 1: Basic Info Saved'), ('step2', 'Step 2: About You Saved'), ('step3', 'Step 3: Photos Saved'), ('completed', 'Profile Completed'), ('submitted', 'Submitted for Review')], default='step1', help_text='Track which step user completed', max_length=20),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='needs_screening_call',
            field=models.BooleanField(default=False, help_text='True after Step 1 - user needs coach screening call'),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='screening_call_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='screening_call_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='screening_notes',
            field=models.TextField(blank=True, help_text='Notes from screening call'),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself!', max_length=500),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=2),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Your hobbies and interests (comma-separated)', max_length=300),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City/Region in Luxembourg', max_length=100),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('friends', 'New Friends'), ('dating', 'Dating'), ('both', 'Both'), ('networking', 'Social Networking')], default='friends', max_length=20),
        ),
    ]
