# Generated by Django 5.1 on 2025-10-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0003_crushprofile_completion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActivityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('speed_dating', 'Speed Dating'), ('presentation_round', '90 Second Presentation Round'), ('mystery_event', 'Mystery Event')], max_length=20)),
                ('activity_variant', models.CharField(blank=True, choices=[('random', 'Random Order'), ('alphabetic', 'Alphabetic Order'), ('hair_color', 'By Hair Color'), ('music', 'With Favorite Music'), ('questions', '5 Predefined Questions'), ('picture_story', 'Share Favorite Picture & Story'), ('none', 'No Variant')], help_text='Sub-option for the activity', max_length=20)),
                ('display_name', models.CharField(help_text="e.g., 'Speed Dating - Random Order'", max_length=200)),
                ('description', models.TextField(help_text='Explanation of what this activity entails')),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_options', to='crush_lu.meetupevent')),
            ],
            options={
                'ordering': ['activity_type', 'activity_variant'],
                'unique_together': {('event', 'activity_type', 'activity_variant')},
            },
        ),
        migrations.CreateModel(
            name='EventVotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_start_time', models.DateTimeField(help_text='Event start time + 15 minutes')),
                ('voting_end_time', models.DateTimeField(help_text='Voting start time + 30 minutes')),
                ('is_active', models.BooleanField(default=False)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_session', to='crush_lu.meetupevent')),
                ('winning_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_events', to='crush_lu.eventactivityoption')),
            ],
        ),
        migrations.CreateModel(
            name='EventActivityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_votes', to='crush_lu.meetupevent')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.eventactivityoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
