# Generated by Django 5.1 on 2025-10-07 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0004_eventactivityoption_eventvotingsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactivityoption',
            name='activity_type',
            field=models.CharField(choices=[('presentation_style', 'Presentation Style (Phase 2)'), ('speed_dating_twist', 'Speed Dating Twist (Phase 3)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventactivityoption',
            name='activity_variant',
            field=models.CharField(blank=True, choices=[('music', 'With Favorite Music'), ('questions', '5 Predefined Questions'), ('picture_story', 'Share Favorite Picture & Story'), ('spicy_questions', 'Spicy Questions First'), ('forbidden_word', 'Forbidden Word Challenge'), ('algorithm_extended', "Algorithm's Choice Extended Time")], help_text='Sub-option for the activity', max_length=20),
        ),
        migrations.CreateModel(
            name='PresentationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_order', models.PositiveIntegerField(help_text='Order in queue (1, 2, 3...)')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to Present'), ('presenting', 'Currently Presenting'), ('completed', 'Presentation Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_queue', to='crush_lu.meetupevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'presentation_order'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PresentationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1-5 stars')),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_ratings', to='crush_lu.meetupevent')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rated_at'],
                'unique_together': {('event', 'presenter', 'rater')},
            },
        ),
        migrations.CreateModel(
            name='SpeedDatingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Which speed dating round (1, 2, 3...)')),
                ('mutual_rating_score', models.FloatField(default=0, help_text='Combined rating score from Phase 2')),
                ('is_top_match', models.BooleanField(default=False, help_text="True if this is user's #1 rated match (gets extended time)")),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_dating_pairs', to='crush_lu.meetupevent')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_dating_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_dating_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'round_number'],
                'unique_together': {('event', 'user1', 'user2', 'round_number')},
            },
        ),
    ]
