# Generated by Django 5.1 on 2025-10-07 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0005_alter_eventactivityoption_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventactivityvote',
            unique_together={('event', 'user', 'selected_option')},
        ),
    ]
