# Generated by Django 5.1 on 2025-10-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0006_alter_eventactivityvote_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalActivityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('presentation_style', 'Presentation Style (Phase 2)'), ('speed_dating_twist', 'Speed Dating Twist (Phase 3)')], max_length=20)),
                ('activity_variant', models.CharField(help_text="Unique identifier (e.g., 'music', 'spicy_questions')", max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text="Inactive options won't appear in voting")),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in voting UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Activity Option',
                'verbose_name_plural': 'Global Activity Options',
                'ordering': ['activity_type', 'sort_order', 'display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='eventvotingsession',
            name='winning_option',
        ),
        migrations.AddField(
            model_name='eventvotingsession',
            name='winning_presentation_style',
            field=models.ForeignKey(blank=True, limit_choices_to={'activity_type': 'presentation_style'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_presentation_events', to='crush_lu.globalactivityoption'),
        ),
        migrations.AddField(
            model_name='eventvotingsession',
            name='winning_speed_dating_twist',
            field=models.ForeignKey(blank=True, limit_choices_to={'activity_type': 'speed_dating_twist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_speed_dating_events', to='crush_lu.globalactivityoption'),
        ),
        migrations.AlterField(
            model_name='eventactivityvote',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.globalactivityoption'),
        ),
    ]
