# Generated by Django 5.1 on 2025-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0008_profilesubmission_review_call_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crushprofile',
            name='completion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('step1', 'Step 1: Basic Info Saved'), ('step2', 'Step 2: About You Saved'), ('step3', 'Step 3: Photos Saved'), ('completed', 'Profile Completed'), ('submitted', 'Submitted for Review')], default='not_started', help_text='Track which step user completed', max_length=20),
        ),
    ]
