# Generated by Django 5.1 on 2025-10-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0009_alter_crushprofile_completion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialUserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name to match (case-insensitive)', max_length=150)),
                ('last_name', models.CharField(help_text='Last name to match (case-insensitive)', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this special experience')),
                ('custom_welcome_title', models.CharField(default='Welcome to Your Special Journey', help_text='Custom welcome message title', max_length=200)),
                ('custom_welcome_message', models.TextField(default='Something magical awaits you...', help_text='Custom welcome message body')),
                ('custom_theme_color', models.CharField(default='#FF1493', help_text='Hex color code for custom theme (e.g., #FF1493 for deep pink)', max_length=7)),
                ('animation_style', models.CharField(choices=[('hearts', 'Floating Hearts'), ('stars', 'Sparkling Stars'), ('roses', 'Falling Rose Petals'), ('fireworks', 'Fireworks'), ('aurora', 'Aurora Borealis')], default='hearts', help_text='Animation effect on welcome screen', max_length=20)),
                ('auto_approve_profile', models.BooleanField(default=True, help_text="Automatically approve this user's profile (skip coach review)")),
                ('skip_waitlist', models.BooleanField(default=True, help_text='Skip event waitlists - always get confirmed spot')),
                ('vip_badge', models.BooleanField(default=True, help_text='Display VIP badge on profile')),
                ('custom_landing_url', models.CharField(blank=True, help_text="Optional: Custom landing page path (e.g., 'special-welcome')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Last time this special experience was triggered', null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0, help_text='Number of times this experience has been triggered')),
            ],
            options={
                'verbose_name': 'Special User Experience',
                'verbose_name_plural': 'Special User Experiences',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
