# Generated by Django 5.1 on 2025-10-15 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0010_specialuserexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chapter Progress',
                'verbose_name_plural': 'Chapter Progress Records',
            },
        ),
        migrations.CreateModel(
            name='JourneyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_order', models.IntegerField(help_text='Order within chapter (1, 2, 3...)')),
                ('challenge_type', models.CharField(choices=[('riddle', 'Riddle'), ('word_scramble', 'Word Scramble'), ('multiple_choice', 'Multiple Choice'), ('memory_match', 'Memory Matching Game'), ('photo_puzzle', 'Photo Jigsaw Puzzle'), ('timeline_sort', 'Timeline Sorting'), ('interactive_story', 'Interactive Story Choice'), ('open_text', 'Open Text Response'), ('would_you_rather', 'Would You Rather'), ('constellation', 'Constellation Drawing'), ('star_catcher', 'Star Catcher Mini-Game')], max_length=30)),
                ('question', models.TextField(help_text='The question/prompt/instructions')),
                ('options', models.JSONField(blank=True, default=dict, help_text='JSON data for options, choices, etc. ({"A": "option1", "B": "option2"})')),
                ('correct_answer', models.TextField(help_text='The correct answer')),
                ('alternative_answers', models.JSONField(blank=True, default=list, help_text='Alternative acceptable answers ["answer1", "answer2"]')),
                ('hint_1', models.TextField(blank=True)),
                ('hint_1_cost', models.IntegerField(default=20, help_text='Points deducted for hint 1')),
                ('hint_2', models.TextField(blank=True)),
                ('hint_2_cost', models.IntegerField(default=50, help_text='Points deducted for hint 2')),
                ('hint_3', models.TextField(blank=True)),
                ('hint_3_cost', models.IntegerField(default=80, help_text='Points deducted for hint 3')),
                ('points_awarded', models.IntegerField(default=100, help_text='Points for correct answer (before hint deductions)')),
                ('success_message', models.TextField(help_text='Personal message shown when user answers correctly')),
            ],
            options={
                'verbose_name': 'Journey Challenge',
                'verbose_name_plural': 'Journey Challenges',
                'ordering': ['challenge_order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(help_text='1, 2, 3, etc.')),
                ('title', models.CharField(help_text='e.g., "Down the Rabbit Hole"', max_length=200)),
                ('theme', models.CharField(help_text='e.g., "Mystery & Curiosity"', max_length=100)),
                ('story_introduction', models.TextField(help_text='The story/narrative shown at chapter start')),
                ('background_theme', models.CharField(choices=[('wonderland_night', 'Wonderland Night (Dark starry sky)'), ('enchanted_garden', 'Enchanted Garden (Flowers & butterflies)'), ('art_gallery', 'Art Gallery (Golden frames & vintage)'), ('carnival', 'Carnival (Warm lights & mirrors)'), ('starlit_sky', 'Starlit Observatory (Deep space & cosmos)'), ('magical_door', 'Magical Door (Sunrise & celebration)')], default='wonderland_night', max_length=20)),
                ('estimated_duration', models.IntegerField(default=10, help_text='Estimated minutes to complete')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('requires_previous_completion', models.BooleanField(default=True, help_text='Must complete previous chapter first')),
                ('completion_message', models.TextField(help_text='Personal message shown after completing all challenges')),
            ],
            options={
                'verbose_name': 'Journey Chapter',
                'verbose_name_plural': 'Journey Chapters',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('hints_used', models.JSONField(default=list, help_text='List of hint numbers used [1, 2, 3]')),
                ('points_earned', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('chapter_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='crush_lu.chapterprogress')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.journeychallenge')),
            ],
            options={
                'verbose_name': 'Challenge Attempt',
                'verbose_name_plural': 'Challenge Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='journeychallenge',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='crush_lu.journeychapter'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.journeychapter'),
        ),
        migrations.CreateModel(
            name='JourneyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('journey_name', models.CharField(default='The Wonderland of You', help_text='Name of this journey', max_length=200)),
                ('total_chapters', models.IntegerField(default=6, help_text='Total number of chapters in this journey')),
                ('estimated_duration_minutes', models.IntegerField(default=90, help_text='Estimated total time to complete')),
                ('date_first_met', models.DateField(blank=True, help_text='Date you first met (for Chapter 1 riddle)', null=True)),
                ('location_first_met', models.CharField(blank=True, help_text='Where you first met', max_length=200)),
                ('certificate_enabled', models.BooleanField(default=True, help_text='Generate completion certificate')),
                ('final_message', models.TextField(default="You've completed every challenge and discovered every secret...", help_text='The big reveal message shown in final chapter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='crush_lu.specialuserexperience')),
            ],
            options={
                'verbose_name': 'Journey Configuration',
                'verbose_name_plural': 'Journey Configurations',
            },
        ),
        migrations.AddField(
            model_name='journeychapter',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='crush_lu.journeyconfiguration'),
        ),
        migrations.CreateModel(
            name='JourneyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0, help_text='Total time spent in journey')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('final_response', models.CharField(blank=True, choices=[('yes', "Yes, let's see where this goes 💫"), ('thinking', 'I need to think about this ✨')], max_length=20)),
                ('final_response_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.journeyconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journey Progress',
                'verbose_name_plural': 'Journey Progress Records',
                'unique_together': {('user', 'journey')},
            },
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='journey_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_completions', to='crush_lu.journeyprogress'),
        ),
        migrations.CreateModel(
            name='JourneyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('photo_reveal', 'Photo Reveal (Jigsaw)'), ('poem', 'Poem/Letter'), ('voice_message', 'Voice Recording'), ('video_message', 'Video Message'), ('photo_slideshow', 'Photo Slideshow'), ('future_letter', 'Future Letter'), ('certificate', 'Completion Certificate')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, help_text='Text content (poem, letter, caption, etc.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journey_rewards/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='journey_rewards/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='journey_rewards/video/')),
                ('puzzle_pieces', models.IntegerField(default=16, help_text='Number of jigsaw pieces (4x4=16, 5x4=20, 6x5=30)')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='crush_lu.journeychapter')),
            ],
            options={
                'verbose_name': 'Journey Reward',
                'verbose_name_plural': 'Journey Rewards',
            },
        ),
        migrations.AlterUniqueTogether(
            name='journeychapter',
            unique_together={('journey', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterprogress',
            unique_together={('journey_progress', 'chapter')},
        ),
    ]
