# Generated by Django 5.1 on 2025-10-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0013_rewardprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Challenge Attempt', 'verbose_name_plural': '🎮 8. Challenge Attempts (User Answers)'},
        ),
        migrations.AlterModelOptions(
            name='chapterprogress',
            options={'verbose_name': 'Chapter Progress', 'verbose_name_plural': '📈 7. Chapter Progress (User Tracking)'},
        ),
        migrations.AlterModelOptions(
            name='journeychallenge',
            options={'ordering': ['challenge_order'], 'verbose_name': 'Journey Challenge', 'verbose_name_plural': '🎯 4. Journey Challenges'},
        ),
        migrations.AlterModelOptions(
            name='journeychapter',
            options={'ordering': ['chapter_number'], 'verbose_name': 'Journey Chapter', 'verbose_name_plural': '📖 3. Journey Chapters'},
        ),
        migrations.AlterModelOptions(
            name='journeyconfiguration',
            options={'verbose_name': 'Journey Configuration', 'verbose_name_plural': '🗺️ 2. Journey Configurations'},
        ),
        migrations.AlterModelOptions(
            name='journeyprogress',
            options={'verbose_name': 'Journey Progress', 'verbose_name_plural': '📊 6. Journey Progress (User Tracking)'},
        ),
        migrations.AlterModelOptions(
            name='journeyreward',
            options={'verbose_name': 'Journey Reward', 'verbose_name_plural': '🎁 5. Journey Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardprogress',
            options={'verbose_name': 'Reward Progress', 'verbose_name_plural': '🏆 9. Reward Progress (Puzzle Tracking)'},
        ),
        migrations.AlterModelOptions(
            name='specialuserexperience',
            options={'verbose_name': 'Special User Experience', 'verbose_name_plural': '✨ 1. Special User Experiences'},
        ),
    ]
