# Generated by Django 5.1 on 2025-10-17 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0014_alter_challengeattempt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupevent',
            name='invitation_code',
            field=models.CharField(blank=True, help_text='Unique code for this private event', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meetupevent',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, help_text='When invitations for this event expire', null=True),
        ),
        migrations.AddField(
            model_name='meetupevent',
            name='is_private_invitation',
            field=models.BooleanField(default=False, help_text='Private invitation-only event (visible only to invited guests)'),
        ),
        migrations.AddField(
            model_name='meetupevent',
            name='max_invited_guests',
            field=models.PositiveIntegerField(default=20, help_text='Maximum invited guests for private event'),
        ),
        migrations.AlterField(
            model_name='journeychallenge',
            name='correct_answer',
            field=models.TextField(blank=True, help_text="The correct answer for QUIZ mode. **LEAVE BLANK for QUESTIONNAIRE mode** (all answers accepted & saved for review). Chapters 2/4/5 and types 'open_text'/'would_you_rather' auto-detect questionnaire mode."),
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(help_text="Guest's email address", max_length=254)),
                ('guest_first_name', models.CharField(help_text="Guest's first name", max_length=100)),
                ('guest_last_name', models.CharField(help_text="Guest's last name", max_length=100)),
                ('invitation_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique invitation code (UUID)', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Invitation Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('attended', 'Attended'), ('expired', 'Expired')], default='pending', help_text='Invitation status', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending_approval', 'Awaiting Approval'), ('approved', 'Approved to Attend'), ('rejected', 'Rejected')], default='pending_approval', help_text='Approval status (coach must approve before attendance)', max_length=20)),
                ('invitation_sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Internal notes about approval/rejection')),
                ('coach_notes', models.TextField(blank=True, help_text='Coach notes about the guest')),
                ('created_user', models.ForeignKey(blank=True, help_text='User account created when invitation was accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitation', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='crush_lu.meetupevent')),
                ('invited_by', models.ForeignKey(help_text='Coach/admin who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Invitation',
                'verbose_name_plural': 'Event Invitations',
                'ordering': ['-invitation_sent_at'],
            },
        ),
    ]
