# Generated by Django 5.1 on 2025-10-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0017_add_status_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crushprofile',
            name='needs_screening_call',
        ),
        migrations.RemoveField(
            model_name='crushprofile',
            name='screening_call_completed',
        ),
        migrations.RemoveField(
            model_name='crushprofile',
            name='screening_call_scheduled',
        ),
        migrations.RemoveField(
            model_name='crushprofile',
            name='screening_notes',
        ),
    ]
