# Generated by Django 5.1.3 on 2025-10-20 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0018_remove_crushprofile_needs_screening_call_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(help_text='Last time user made a request')),
                ('last_pwa_visit', models.DateTimeField(blank=True, help_text='Last time user accessed via PWA (standalone mode)', null=True)),
                ('is_pwa_user', models.BooleanField(default=False, help_text='Has this user ever used the installed PWA?')),
                ('total_visits', models.PositiveIntegerField(default=0, help_text='Total number of visits/requests')),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='First time user was tracked')),
                ('user', models.OneToOneField(help_text='User being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': '📊 User Activities',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500)),
                ('p256dh_key', models.CharField(help_text='Public key for encryption (p256dh)', max_length=255)),
                ('auth_key', models.CharField(help_text='Authentication secret (auth)', max_length=255)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('device_name', models.CharField(blank=True, help_text="Friendly device name (e.g., 'Android Chrome', 'iPhone Safari')", max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='User can disable notifications without unsubscribing')),
                ('notify_new_messages', models.BooleanField(default=True, help_text='Notify about new connection messages')),
                ('notify_event_reminders', models.BooleanField(default=True, help_text='Notify about upcoming events')),
                ('notify_new_connections', models.BooleanField(default=True, help_text='Notify about new connection requests')),
                ('notify_profile_updates', models.BooleanField(default=True, help_text='Notify about profile approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a notification was successfully sent', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed deliveries (auto-delete after threshold)')),
                ('user', models.ForeignKey(help_text='User who owns this push subscription', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Subscription',
                'verbose_name_plural': '🔔 Push Notification Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
