# Generated by Django 5.1.4 on 2025-12-01 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0019_useractivity_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyconfiguration',
            name='journey_type',
            field=models.CharField(choices=[('wonderland', 'The Wonderland of You'), ('advent_calendar', 'Advent Calendar'), ('custom', 'Custom Journey')], default='wonderland', help_text='Type of journey experience', max_length=20),
        ),
        migrations.AlterField(
            model_name='journeyconfiguration',
            name='special_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='crush_lu.specialuserexperience'),
        ),
        migrations.AlterUniqueTogether(
            name='journeyconfiguration',
            unique_together={('special_experience', 'journey_type')},
        ),
        migrations.CreateModel(
            name='AdventCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2024, help_text='Year for this advent calendar (e.g., 2024)')),
                ('start_date', models.DateField(help_text='Start date (usually December 1)')),
                ('end_date', models.DateField(help_text='End date (usually December 24)')),
                ('allow_catch_up', models.BooleanField(default=True, help_text='Allow users to open past doors (accumulating access)')),
                ('timezone_name', models.CharField(default='Europe/Luxembourg', help_text='Timezone for date calculations', max_length=50)),
                ('calendar_title', models.CharField(default='Your Advent Calendar', help_text='Title displayed on the calendar', max_length=200)),
                ('calendar_description', models.TextField(blank=True, help_text='Description shown on the calendar page')),
                ('background_image', models.ImageField(blank=True, help_text='Custom background image for the calendar', null=True, upload_to='advent_backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.OneToOneField(help_text='The journey configuration for this advent calendar', on_delete=django.db.models.deletion.CASCADE, related_name='advent_calendar', to='crush_lu.journeyconfiguration')),
            ],
            options={
                'verbose_name': 'Advent Calendar',
                'verbose_name_plural': '🎄 1. Advent Calendars',
            },
        ),
        migrations.CreateModel(
            name='AdventDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.PositiveIntegerField(help_text='Door number (1-24)')),
                ('content_type', models.CharField(choices=[('challenge', 'Interactive Challenge'), ('poem', 'Poem/Letter'), ('photo', 'Photo Reveal'), ('video', 'Video Message'), ('audio', 'Audio Message'), ('gift_teaser', 'Physical Gift Teaser'), ('memory', 'Shared Memory'), ('quiz', 'Fun Quiz'), ('countdown', 'Countdown Special')], default='poem', max_length=20)),
                ('qr_mode', models.CharField(choices=[('none', 'No QR Required'), ('required', 'QR Required to Open Door'), ('bonus', 'QR Unlocks Bonus Content')], default='none', help_text='How QR codes work for this door', max_length=10)),
                ('door_color', models.CharField(default='#C41E3A', help_text='Hex color for the door (e.g., #C41E3A for Christmas red)', max_length=7)),
                ('door_icon', models.CharField(blank=True, help_text='Emoji or icon class for the door (e.g., 🎁, 🎄, ⭐)', max_length=50)),
                ('teaser_text', models.CharField(blank=True, help_text='Short teaser text shown on the closed door', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='crush_lu.adventcalendar')),
                ('chapter', models.OneToOneField(blank=True, help_text='Optional link to a JourneyChapter for challenge content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advent_door', to='crush_lu.journeychapter')),
            ],
            options={
                'verbose_name': 'Advent Door',
                'verbose_name_plural': '🚪 2. Advent Doors',
                'ordering': ['door_number'],
                'unique_together': {('calendar', 'door_number')},
            },
        ),
        migrations.CreateModel(
            name='AdventDoorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title shown when door is opened', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Main text content (poem, letter, description, etc.)')),
                ('photo', models.ImageField(blank=True, help_text='Main photo for this door', null=True, upload_to='advent_doors/')),
                ('video_file', models.FileField(blank=True, help_text='Video message', null=True, upload_to='advent_doors/video/')),
                ('audio_file', models.FileField(blank=True, help_text='Audio message', null=True, upload_to='advent_doors/audio/')),
                ('bonus_title', models.CharField(blank=True, help_text='Title for bonus content unlocked via QR', max_length=200)),
                ('bonus_content', models.TextField(blank=True, help_text='Bonus text content unlocked via QR code')),
                ('bonus_photo', models.ImageField(blank=True, help_text='Bonus photo unlocked via QR code', null=True, upload_to='advent_doors/bonus/')),
                ('gift_hint', models.CharField(blank=True, help_text='Hint about the physical gift', max_length=500)),
                ('gift_location_clue', models.CharField(blank=True, help_text='Clue about where to find the gift', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('door', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='crush_lu.adventdoor')),
            ],
            options={
                'verbose_name': 'Door Content',
                'verbose_name_plural': '📝 3. Door Contents',
            },
        ),
        migrations.CreateModel(
            name='AdventProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_opened', models.JSONField(default=list, help_text='List of door numbers that have been opened [1, 2, 3, ...]')),
                ('qr_scans', models.JSONField(default=list, help_text='List of door numbers where QR was scanned [1, 5, 12, ...]')),
                ('last_door_opened', models.PositiveIntegerField(blank=True, help_text='Last door number opened', null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, help_text='When the last door was opened', null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='crush_lu.adventcalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advent_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advent Progress',
                'verbose_name_plural': '📊 4. Advent Progress',
                'unique_together': {('user', 'calendar')},
            },
        ),
        migrations.CreateModel(
            name='QRCodeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for QR code', unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Has this token been redeemed?')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was redeemed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for this token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='crush_lu.adventdoor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advent_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code Token',
                'verbose_name_plural': '🔑 5. QR Code Tokens',
                'unique_together': {('door', 'user')},
            },
        ),
    ]
