# Generated by Django 4.2.23 on 2025-12-13 12:23

import crush_lu.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0020_advent_calendar_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventdoor',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('riddle', '🧩 Riddle'), ('word_scramble', '🔤 Word Scramble'), ('multiple_choice', '📝 Multiple Choice'), ('memory_match', '🃏 Memory Matching Game'), ('photo_puzzle', '🖼️ Photo Jigsaw Puzzle'), ('timeline_sort', '📅 Timeline Sorting'), ('interactive_story', '📖 Interactive Story Choice'), ('open_text', '✍️ Open Text Response'), ('would_you_rather', '🤔 Would You Rather'), ('constellation', '⭐ Constellation Drawing'), ('star_catcher', '🌟 Star Catcher Mini-Game')], help_text="Type of challenge (only used when content_type is 'challenge')", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='challenge_alternative_answers',
            field=models.JSONField(blank=True, default=list, help_text='Alternative acceptable answers: ["answer1", "answer2"]'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='challenge_correct_answer',
            field=models.TextField(blank=True, help_text='The correct answer. Leave blank for questionnaire mode (all answers accepted).'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='challenge_options',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for options/choices: {"A": "option1", "B": "option2"}'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='challenge_question',
            field=models.TextField(blank=True, help_text='The question/prompt/instructions for the challenge'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_1',
            field=models.TextField(blank=True, help_text='First hint (easiest)'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_1_cost',
            field=models.IntegerField(default=20, help_text='Points deducted for using hint 1'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_2',
            field=models.TextField(blank=True, help_text='Second hint (medium)'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_2_cost',
            field=models.IntegerField(default=50, help_text='Points deducted for using hint 2'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_3',
            field=models.TextField(blank=True, help_text='Third hint (biggest reveal)'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='hint_3_cost',
            field=models.IntegerField(default=80, help_text='Points deducted for using hint 3'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='points_awarded',
            field=models.IntegerField(default=100, help_text='Points for correct answer (before hint deductions)'),
        ),
        migrations.AddField(
            model_name='adventdoorcontent',
            name='success_message',
            field=models.TextField(blank=True, help_text='Personal message shown when user answers correctly'),
        ),
        migrations.AlterField(
            model_name='adventdoor',
            name='content_type',
            field=models.CharField(choices=[('challenge', '🎯 Interactive Challenge'), ('poem', '📜 Poem/Letter'), ('photo', '📷 Photo Reveal'), ('video', '🎥 Video Message'), ('audio', '🎵 Audio Message'), ('gift_teaser', '🎁 Physical Gift Teaser'), ('memory', '💭 Shared Memory'), ('quiz', '❓ Fun Quiz'), ('countdown', '⏰ Countdown Special')], default='poem', max_length=20),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=crush_lu.models.profiles.user_photo_path),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=crush_lu.models.profiles.user_photo_path),
        ),
        migrations.AlterField(
            model_name='crushprofile',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=crush_lu.models.profiles.user_photo_path),
        ),
    ]
