# Generated by Django 4.2.23 on 2025-12-14 13:01

import crush_lu.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0021_update_photo_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='crushcoach',
            name='photo',
            field=models.ImageField(blank=True, help_text='Coach profile photo shown to users', null=True, upload_to=crush_lu.models.profiles.coach_photo_path),
        ),
    ]
