# Generated by Django 4.2.23 on 2025-12-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0023_fix_photo_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('state_id', models.CharField(help_text='Unique state identifier passed through OAuth flow', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('state_data', models.TextField(help_text='JSON serialized state dictionary')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the state was created')),
                ('expires_at', models.DateTimeField(help_text='When the state expires')),
                ('used', models.BooleanField(default=False, help_text='Whether the state has been consumed')),
                ('provider', models.CharField(blank=True, default='', help_text='OAuth provider name', max_length=50)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent of originating request')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of originating request', null=True)),
            ],
            options={
                'verbose_name': 'OAuth State',
                'verbose_name_plural': 'OAuth States',
                'indexes': [models.Index(fields=['expires_at'], name='crush_lu_oa_expires_a71ecd_idx'), models.Index(fields=['used'], name='crush_lu_oa_used_3160a3_idx')],
            },
        ),
    ]
