# Generated by Django 4.2.23 on 2025-12-18 15:06

import crush_lu.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0025_add_oauth_result_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventcalendar',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Custom background image for the calendar', null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='advent_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='adventdoorcontent',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio message', null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='advent_doors/audio/'),
        ),
        migrations.AlterField(
            model_name='adventdoorcontent',
            name='bonus_photo',
            field=models.ImageField(blank=True, help_text='Bonus photo unlocked via QR code', null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='advent_doors/bonus/'),
        ),
        migrations.AlterField(
            model_name='adventdoorcontent',
            name='photo',
            field=models.ImageField(blank=True, help_text='Main photo for this door', null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='advent_doors/'),
        ),
        migrations.AlterField(
            model_name='adventdoorcontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video message', null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='advent_doors/video/'),
        ),
        migrations.AlterField(
            model_name='journeyreward',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='journey_rewards/audio/'),
        ),
        migrations.AlterField(
            model_name='journeyreward',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='journey_rewards/'),
        ),
        migrations.AlterField(
            model_name='journeyreward',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=crush_lu.models.profiles.get_crush_photo_storage, upload_to='journey_rewards/video/'),
        ),
    ]
