# Generated by Django 4.2.23 on 2025-12-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0027_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='is_popup',
            field=models.BooleanField(default=False, help_text='Whether this OAuth flow was initiated from a popup window'),
        ),
    ]
