# Generated by Django 5.1.4 on 2025-12-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0031_migrate_location_to_cantons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500)),
                ('p256dh_key', models.CharField(help_text='Public key for encryption (p256dh)', max_length=255)),
                ('auth_key', models.CharField(help_text='Authentication secret (auth)', max_length=255)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('device_name', models.CharField(blank=True, help_text="Friendly device name (e.g., 'Android Chrome', 'iPhone Safari')", max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Coach can disable notifications without unsubscribing')),
                ('notify_new_submissions', models.BooleanField(default=True, help_text='Notify when new profile is assigned for review')),
                ('notify_screening_reminders', models.BooleanField(default=True, help_text='Notify about pending screening calls')),
                ('notify_user_responses', models.BooleanField(default=True, help_text='Notify when user submits revision')),
                ('notify_system_alerts', models.BooleanField(default=True, help_text='Notify about system/admin messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a notification was successfully sent', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed deliveries (auto-delete after threshold)')),
                ('coach', models.ForeignKey(help_text='Coach who owns this push subscription', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='crush_lu.crushcoach')),
            ],
            options={
                'verbose_name': 'Coach Push Subscription',
                'verbose_name_plural': '🔔 Coach Push Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('coach', 'endpoint')},
            },
        ),
    ]
