# Generated by Django 5.1.4 on 2026-01-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0034_add_device_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a reminder email was sent to this user', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='reminders_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reminder emails sent to this user'),
        ),
        migrations.CreateModel(
            name='ProfileReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 Hour'), ('72h', '72 Hour'), ('7d', '7 Day Final')], help_text='Type of reminder sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the reminder was sent')),
                ('user', models.ForeignKey(help_text='User who received this reminder', on_delete=django.db.models.deletion.CASCADE, related_name='profile_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Reminder',
                'verbose_name_plural': '📬 Profile Reminders',
                'ordering': ['-sent_at'],
                'unique_together': {('user', 'reminder_type')},
            },
        ),
    ]
