# Generated by Django 5.1.15 on 2026-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0035_add_profile_reminder_and_user_activity_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskitDeviceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_library_identifier",
                    models.CharField(
                        help_text="Apple Wallet device library identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "pass_type_identifier",
                    models.CharField(
                        help_text="Pass type identifier used for APNS topic.",
                        max_length=255,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Pass serial number used to target updates.",
                        max_length=64,
                    ),
                ),
                (
                    "push_token",
                    models.CharField(
                        help_text="APNS push token for the device.", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PassKit Device Registration",
                "verbose_name_plural": "PassKit Device Registrations",
                "indexes": [
                    models.Index(
                        fields=["pass_type_identifier", "serial_number"],
                        name="crush_lu_pa_pass_ty_9306eb_idx",
                    ),
                    models.Index(
                        fields=["device_library_identifier", "pass_type_identifier"],
                        name="crush_lu_pa_device__93bb6e_idx",
                    ),
                ],
                "unique_together": {("device_library_identifier", "serial_number")},
            },
        ),
    ]
