# Generated by Django 5.1.15 on 2026-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0035_add_profile_reminder_and_user_activity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="apple_auth_token",
            field=models.CharField(
                blank=True, help_text="Apple Wallet authentication token", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="apple_pass_serial",
            field=models.CharField(
                blank=True, help_text="Apple Wallet pass serial number", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="google_wallet_object_id",
            field=models.CharField(
                blank=True, help_text="Google Wallet object ID", max_length=128
            ),
        ),
    ]
