# Generated by Django 5.1.15 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0038_passkitdeviceregistration"),
    ]

    operations = [
        # CrushProfile: Add wallet photo toggle
        migrations.AddField(
            model_name="crushprofile",
            name="show_photo_on_wallet",
            field=models.BooleanField(
                default=True,
                help_text="Show profile photo on wallet card",
            ),
        ),
        # CrushProfile: Add referral points
        migrations.AddField(
            model_name="crushprofile",
            name="referral_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Points earned from referrals",
            ),
        ),
        # CrushProfile: Add membership tier
        migrations.AddField(
            model_name="crushprofile",
            name="membership_tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                ],
                default="basic",
                help_text="Membership tier based on referral activity",
                max_length=20,
            ),
        ),
        # ReferralAttribution: Add reward tracking fields
        migrations.AddField(
            model_name="referralattribution",
            name="reward_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether the referral reward has been applied to the referrer",
            ),
        ),
        migrations.AddField(
            model_name="referralattribution",
            name="reward_applied_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reward was applied",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referralattribution",
            name="reward_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Points awarded for this referral",
            ),
        ),
    ]
