# Generated by Django 5.1.15 on 2026-01-05 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0039_add_referral_points"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletPassProxy",
            fields=[],
            options={
                "verbose_name": "Wallet Pass",
                "verbose_name_plural": "Wallet Passes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="eventregistration_event_status"
            ),
        ),
    ]
