# Generated by Django 5.1.15 on 2026-01-05 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0040_add_eventregistration_event_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PWADeviceInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Stable browser fingerprint for device identification', max_length=64)),
                ('os_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('chromeos', 'ChromeOS'), ('unknown', 'Unknown')], default='unknown', help_text='Operating system type', max_length=20)),
                ('form_factor', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', help_text='Device form factor (phone, tablet, desktop)', max_length=20)),
                ('device_category', models.CharField(help_text="Combined category like 'Android Phone', 'Windows Desktop'", max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser name (Chrome, Safari, Edge, etc.)', max_length=50)),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string')),
                ('installed_at', models.DateTimeField(auto_now_add=True, help_text='When PWA was first installed on this device')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time PWA was used on this device')),
                ('user', models.ForeignKey(help_text='User who installed the PWA', on_delete=django.db.models.deletion.CASCADE, related_name='pwa_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PWA Device Installation',
                'verbose_name_plural': 'PWA Device Installations',
                'ordering': ['-last_used_at'],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
