# Generated by Django 5.1.15 on 2026-01-10 13:25

import crush_lu.models.journey_gift
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0041_pwa_device_installation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_code', models.CharField(default=crush_lu.models.journey_gift.generate_gift_code, help_text='Unique gift code (e.g., WOY-A1B2C3D4)', max_length=16, unique=True)),
                ('sender_message', models.TextField(blank=True, help_text='Optional personal message from sender')),
                ('recipient_name', models.CharField(help_text="Name/nickname for the journey story (e.g., 'My Crush', 'Marie')", max_length=100)),
                ('recipient_email', models.EmailField(blank=True, help_text='Optional email for notifications', max_length=254)),
                ('date_first_met', models.DateField(help_text='Date the sender and recipient first met')),
                ('location_first_met', models.CharField(help_text='Location where they first met', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', help_text='Current status of the gift', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the gift', null=True)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When the gift was claimed', null=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image', upload_to=crush_lu.models.journey_gift.gift_qr_code_path)),
            ],
            options={
                'verbose_name': 'Journey Gift',
                'verbose_name_plural': 'Journey Gifts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='coachpushsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coach Push Subscription', 'verbose_name_plural': 'Coach Push Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='emailpreference',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Email Preference', 'verbose_name_plural': 'Email Preferences'},
        ),
        migrations.AlterModelOptions(
            name='profilereminder',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Profile Reminder', 'verbose_name_plural': 'Profile Reminders'},
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Push Notification Subscription', 'verbose_name_plural': 'Push Notification Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='referralattribution',
            options={'verbose_name': 'Referral Attribution', 'verbose_name_plural': 'Referral Attributions'},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'verbose_name': 'Referral Code', 'verbose_name_plural': 'Referral Codes'},
        ),
        migrations.AlterModelOptions(
            name='specialuserexperience',
            options={'verbose_name': 'Special User Experience', 'verbose_name_plural': 'Special User Experiences'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-last_seen'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterUniqueTogether(
            name='specialuserexperience',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specialuserexperience',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='Direct link to user (bypasses name matching). Used for gifted journeys.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='specialuserexperience',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_user__isnull', True)), fields=('first_name', 'last_name'), name='unique_name_when_no_linked_user'),
        ),
        migrations.AddConstraint(
            model_name='specialuserexperience',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_user__isnull', False)), fields=('linked_user',), name='unique_linked_user'),
        ),
        migrations.AddField(
            model_name='journeygift',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who claimed this gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_journey_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeygift',
            name='journey',
            field=models.ForeignKey(blank=True, help_text='Journey created from this gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_gift', to='crush_lu.journeyconfiguration'),
        ),
        migrations.AddField(
            model_name='journeygift',
            name='sender',
            field=models.ForeignKey(help_text='User who created this gift', on_delete=django.db.models.deletion.CASCADE, related_name='sent_journey_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeygift',
            name='special_experience',
            field=models.ForeignKey(blank=True, help_text='Special experience created from this gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_gift', to='crush_lu.specialuserexperience'),
        ),
    ]
