# Generated by Django 5.1.15 on 2026-01-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0042_journey_gift_and_linked_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journeyconfiguration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German"), ("fr", "French")],
                default="en",
                help_text="Language of this journey's content",
                max_length=5,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeyconfiguration",
            unique_together={("special_experience", "journey_type", "language")},
        ),
    ]
