# Generated by Django 5.1.15 on 2026-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0043_add_journey_language_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_1_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_1_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_1_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_2_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_2_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_2_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_3_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_3_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="hint_3_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="question_de",
            field=models.TextField(
                help_text="The question/prompt/instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="question_en",
            field=models.TextField(
                help_text="The question/prompt/instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="question_fr",
            field=models.TextField(
                help_text="The question/prompt/instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="success_message_de",
            field=models.TextField(
                help_text="Personal message shown when user answers correctly",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="success_message_en",
            field=models.TextField(
                help_text="Personal message shown when user answers correctly",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychallenge",
            name="success_message_fr",
            field=models.TextField(
                help_text="Personal message shown when user answers correctly",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="completion_message_de",
            field=models.TextField(
                help_text="Personal message shown after completing all challenges",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="completion_message_en",
            field=models.TextField(
                help_text="Personal message shown after completing all challenges",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="completion_message_fr",
            field=models.TextField(
                help_text="Personal message shown after completing all challenges",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="story_introduction_de",
            field=models.TextField(
                help_text="The story/narrative shown at chapter start", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="story_introduction_en",
            field=models.TextField(
                help_text="The story/narrative shown at chapter start", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="story_introduction_fr",
            field=models.TextField(
                help_text="The story/narrative shown at chapter start", null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="theme_de",
            field=models.CharField(
                help_text='e.g., "Mystery & Curiosity"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="theme_en",
            field=models.CharField(
                help_text='e.g., "Mystery & Curiosity"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="theme_fr",
            field=models.CharField(
                help_text='e.g., "Mystery & Curiosity"', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="title_de",
            field=models.CharField(
                help_text='e.g., "Down the Rabbit Hole"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="title_en",
            field=models.CharField(
                help_text='e.g., "Down the Rabbit Hole"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeychapter",
            name="title_fr",
            field=models.CharField(
                help_text='e.g., "Down the Rabbit Hole"', max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="final_message_de",
            field=models.TextField(
                default="You've completed every challenge and discovered every secret...",
                help_text="The big reveal message shown in final chapter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="final_message_en",
            field=models.TextField(
                default="You've completed every challenge and discovered every secret...",
                help_text="The big reveal message shown in final chapter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="final_message_fr",
            field=models.TextField(
                default="You've completed every challenge and discovered every secret...",
                help_text="The big reveal message shown in final chapter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="journey_name_de",
            field=models.CharField(
                default="The Wonderland of You",
                help_text="Name of this journey",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="journey_name_en",
            field=models.CharField(
                default="The Wonderland of You",
                help_text="Name of this journey",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyconfiguration",
            name="journey_name_fr",
            field=models.CharField(
                default="The Wonderland of You",
                help_text="Name of this journey",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="message_de",
            field=models.TextField(
                blank=True,
                help_text="Text content (poem, letter, caption, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="message_en",
            field=models.TextField(
                blank=True,
                help_text="Text content (poem, letter, caption, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="message_fr",
            field=models.TextField(
                blank=True,
                help_text="Text content (poem, letter, caption, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="title_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="journeyreward",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_message_de",
            field=models.TextField(
                default="Something magical awaits you...",
                help_text="Custom welcome message body",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_message_en",
            field=models.TextField(
                default="Something magical awaits you...",
                help_text="Custom welcome message body",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_message_fr",
            field=models.TextField(
                default="Something magical awaits you...",
                help_text="Custom welcome message body",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_title_de",
            field=models.CharField(
                default="Welcome to Your Special Journey",
                help_text="Custom welcome message title",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_title_en",
            field=models.CharField(
                default="Welcome to Your Special Journey",
                help_text="Custom welcome message title",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialuserexperience",
            name="custom_welcome_title_fr",
            field=models.CharField(
                default="Welcome to Your Special Journey",
                help_text="Custom welcome message title",
                max_length=200,
                null=True,
            ),
        ),
    ]
