# Generated by Django 5.1.15 on 2026-01-13 21:12

from django.db import migrations


def copy_content_to_en_fields(apps, schema_editor):
    """
    Copy existing content from original fields to _en fields.
    modeltranslation reads from language-specific fields, so we need
    to populate them with existing data.
    """
    SpecialUserExperience = apps.get_model('crush_lu', 'SpecialUserExperience')
    JourneyConfiguration = apps.get_model('crush_lu', 'JourneyConfiguration')
    JourneyChapter = apps.get_model('crush_lu', 'JourneyChapter')
    JourneyChallenge = apps.get_model('crush_lu', 'JourneyChallenge')
    JourneyReward = apps.get_model('crush_lu', 'JourneyReward')

    # Migrate SpecialUserExperience
    for obj in SpecialUserExperience.objects.all():
        obj.custom_welcome_title_en = obj.custom_welcome_title
        obj.custom_welcome_message_en = obj.custom_welcome_message
        obj.save()

    # Migrate JourneyConfiguration
    for obj in JourneyConfiguration.objects.all():
        obj.journey_name_en = obj.journey_name
        obj.final_message_en = obj.final_message
        obj.save()

    # Migrate JourneyChapter
    for obj in JourneyChapter.objects.all():
        obj.title_en = obj.title
        obj.theme_en = obj.theme
        obj.story_introduction_en = obj.story_introduction
        obj.completion_message_en = obj.completion_message
        obj.save()

    # Migrate JourneyChallenge
    for obj in JourneyChallenge.objects.all():
        obj.question_en = obj.question
        obj.hint_1_en = obj.hint_1
        obj.hint_2_en = obj.hint_2
        obj.hint_3_en = obj.hint_3
        obj.success_message_en = obj.success_message
        obj.save()

    # Migrate JourneyReward
    for obj in JourneyReward.objects.all():
        obj.title_en = obj.title
        obj.message_en = obj.message
        obj.save()


def reverse_copy_en_to_original(apps, schema_editor):
    """
    Reverse migration: copy _en fields back to original fields.
    """
    SpecialUserExperience = apps.get_model('crush_lu', 'SpecialUserExperience')
    JourneyConfiguration = apps.get_model('crush_lu', 'JourneyConfiguration')
    JourneyChapter = apps.get_model('crush_lu', 'JourneyChapter')
    JourneyChallenge = apps.get_model('crush_lu', 'JourneyChallenge')
    JourneyReward = apps.get_model('crush_lu', 'JourneyReward')

    # Reverse SpecialUserExperience
    for obj in SpecialUserExperience.objects.all():
        obj.custom_welcome_title = obj.custom_welcome_title_en or obj.custom_welcome_title
        obj.custom_welcome_message = obj.custom_welcome_message_en or obj.custom_welcome_message
        obj.save()

    # Reverse JourneyConfiguration
    for obj in JourneyConfiguration.objects.all():
        obj.journey_name = obj.journey_name_en or obj.journey_name
        obj.final_message = obj.final_message_en or obj.final_message
        obj.save()

    # Reverse JourneyChapter
    for obj in JourneyChapter.objects.all():
        obj.title = obj.title_en or obj.title
        obj.theme = obj.theme_en or obj.theme
        obj.story_introduction = obj.story_introduction_en or obj.story_introduction
        obj.completion_message = obj.completion_message_en or obj.completion_message
        obj.save()

    # Reverse JourneyChallenge
    for obj in JourneyChallenge.objects.all():
        obj.question = obj.question_en or obj.question
        obj.hint_1 = obj.hint_1_en or obj.hint_1
        obj.hint_2 = obj.hint_2_en or obj.hint_2
        obj.hint_3 = obj.hint_3_en or obj.hint_3
        obj.success_message = obj.success_message_en or obj.success_message
        obj.save()

    # Reverse JourneyReward
    for obj in JourneyReward.objects.all():
        obj.title = obj.title_en or obj.title
        obj.message = obj.message_en or obj.message
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0044_add_modeltranslation_fields"),
    ]

    operations = [
        migrations.RunPython(copy_content_to_en_fields, reverse_copy_en_to_original),
    ]
