# Generated by Django 5.1.15 on 2026-01-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0045_migrate_content_to_en_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journeyconfiguration",
            unique_together={("special_experience", "journey_type")},
        ),
        migrations.RemoveField(
            model_name="journeyconfiguration",
            name="language",
        ),
    ]
