# Generated by Django 5.1.15 on 2026-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0046_remove_language_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="event_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages the user can speak at in-person events",
            ),
        ),
    ]
