# Generated by Django 5.1.15 on 2026-01-19 12:51

import crush_lu.models.journey
import crush_lu.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0047_add_event_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeyreward",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey.journey_reward_audio_path,
            ),
        ),
        migrations.AlterField(
            model_name="journeyreward",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey.journey_reward_photo_path,
            ),
        ),
        migrations.AlterField(
            model_name="journeyreward",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey.journey_reward_video_path,
            ),
        ),
    ]
