# Generated by Django 5.1.15 on 2026-01-19 14:22

import crush_lu.models.journey_gift
import crush_lu.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0048_user_specific_journey_reward_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="journeygift",
            name="chapter1_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo for the Chapter 1 puzzle reveal (recommended: 800x800px)",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter1_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter3_image_1",
            field=models.ImageField(
                blank=True,
                help_text="First slideshow photo",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter3_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter3_image_2",
            field=models.ImageField(
                blank=True,
                help_text="Second slideshow photo",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter3_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter3_image_3",
            field=models.ImageField(
                blank=True,
                help_text="Third slideshow photo",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter3_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter3_image_4",
            field=models.ImageField(
                blank=True,
                help_text="Fourth slideshow photo",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter3_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter3_image_5",
            field=models.ImageField(
                blank=True,
                help_text="Fifth slideshow photo",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter3_image_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter4_audio",
            field=models.FileField(
                blank=True,
                help_text="Voice message audio file (MP3, WAV, M4A - max 10MB)",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter4_audio_path,
            ),
        ),
        migrations.AddField(
            model_name="journeygift",
            name="chapter4_video",
            field=models.FileField(
                blank=True,
                help_text="Video message file (MP4, MOV - max 50MB)",
                null=True,
                storage=crush_lu.models.profiles.get_crush_photo_storage,
                upload_to=crush_lu.models.journey_gift.gift_chapter4_audio_path,
            ),
        ),
    ]
