# Generated by Django 5.1.15 on 2026-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0051_increase_journey_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='crushprofile',
            name='outlook_contact_id',
            field=models.CharField(blank=True, help_text='Microsoft Graph contact ID for Outlook sync', max_length=255),
        ),
    ]
