# Generated by Django 5.1.15 on 2026-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0052_add_outlook_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeychallenge',
            name='options_de',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for options, choices, etc. ({"A": "option1", "B": "option2"})', null=True),
        ),
        migrations.AddField(
            model_name='journeychallenge',
            name='options_en',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for options, choices, etc. ({"A": "option1", "B": "option2"})', null=True),
        ),
        migrations.AddField(
            model_name='journeychallenge',
            name='options_fr',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for options, choices, etc. ({"A": "option1", "B": "option2"})', null=True),
        ),
    ]
