# Generated by Django 5.1.15 on 2026-01-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0056_add_chapter5_letter_music_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesubmission',
            name='review_call_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Structured checklist data from screening call'),
        ),
    ]
