# Generated by Django 5.1.15 on 2026-01-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0059_add_profilesubmission_composite_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Needs Revision'), ('recontact_coach', 'Recontact Coach Required')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the call attempt was made')),
                ('result', models.CharField(choices=[('success', 'Call Completed'), ('failed', 'Call Failed')], help_text='Whether the call succeeded or failed', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('no_answer', 'No answer'), ('voicemail', 'Voicemail left'), ('wrong_number', 'Wrong number'), ('user_busy', 'User busy'), ('scheduled_callback', 'Scheduled callback')], help_text='Reason why call failed (if applicable)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the call attempt')),
                ('coach', models.ForeignKey(help_text='Coach who made the call attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crush_lu.crushcoach')),
                ('submission', models.ForeignKey(help_text='The profile submission this call attempt is for', on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='crush_lu.profilesubmission')),
            ],
            options={
                'verbose_name': 'Call Attempt',
                'verbose_name_plural': 'Call Attempts',
                'ordering': ['-attempt_date'],
                'indexes': [models.Index(fields=['submission', '-attempt_date'], name='crush_lu_ca_submiss_6c56c6_idx')],
            },
        ),
    ]
