# Generated by Django 5.1.15 on 2026-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0061_update_journey_gift_qr_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='crushprofile',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict, help_text='Temporary storage for incomplete/invalid step data'),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-delete inactive drafts after 30 days', null=True),
        ),
        migrations.AddField(
            model_name='crushprofile',
            name='last_draft_saved',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last auto-save', null=True),
        ),
    ]
