# Generated by Django 5.1.15 on 2026-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0062_crushprofile_draft_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="canton",
            field=models.CharField(
                blank=True,
                help_text="Canton/region visible to public visitors (e.g., 'Luxembourg', 'Esch-sur-Alzette'). Free-text entry for flexibility.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="enable_activity_voting",
            field=models.BooleanField(
                default=False,
                help_text="Enable 3-phase interactive system (voting, presentations, speed dating)",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="require_approved_profile",
            field=models.BooleanField(
                default=True,
                help_text="Require attendees to have approved profiles (recommended for dating events)",
            ),
        ),
    ]
