# Generated by Django 5.1.15 on 2026-02-04 14:20

from django.db import migrations


def populate_cantons(apps, schema_editor):
    """Set default canton for existing events"""
    MeetupEvent = apps.get_model('crush_lu', 'MeetupEvent')
    MeetupEvent.objects.filter(canton='').update(canton='Luxembourg')


def reverse_populate(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0063_meetupevent_canton_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_cantons, reverse_populate),
    ]
