# Generated by Django 5.1.15 on 2026-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0064_populate_event_cantons"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="accessibility_needs",
            field=models.TextField(
                blank=True, help_text="Any accessibility accommodations needed"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="bringing_guest",
            field=models.BooleanField(
                default=False, help_text="Attending with a guest"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="guest_name",
            field=models.CharField(
                blank=True,
                help_text="Guest's name (if bringing someone)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="allow_plus_ones",
            field=models.BooleanField(
                default=False, help_text="Can attendees bring a guest?"
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="has_food_component",
            field=models.BooleanField(
                default=False,
                help_text="Does this event include food/drinks? (Shows dietary restrictions field)",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True,
                help_text="Only for events with food component",
                max_length=200,
            ),
        ),
    ]
