# Generated by Django 5.1.15 on 2026-02-04 17:53

import crush_lu.storage
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0065_eventregistration_accessibility_needs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event banner image (recommended: 1200x400px, displayed on event detail page)",
                null=True,
                storage=crush_lu.storage.get_crush_media_storage,
                upload_to=functools.partial(
                    crush_lu.storage._domain_upload_path,
                    *("crush-lu", "events/banners"),
                    **{}
                ),
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="title_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
