# Generated by Django 5.1.15 on 2026-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0066_add_event_image_and_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrushSiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: 352621XXXXXX (no + or spaces)",
                        max_length=20,
                        verbose_name="WhatsApp number",
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=True, verbose_name="WhatsApp button enabled"
                    ),
                ),
                (
                    "whatsapp_default_message",
                    models.CharField(
                        blank=True,
                        default="Hi! I have a question about Crush.lu.",
                        help_text="Pre-filled message when user clicks the button",
                        max_length=200,
                        verbose_name="Default WhatsApp message",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
