# Generated by Django 5.1.15 on 2026-02-06 00:43

import crush_lu.storage
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0067_add_crush_site_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailpreference",
            name="email_newsletter",
            field=models.BooleanField(
                default=True,
                help_text="Newsletter emails about upcoming events and community news",
            ),
        ),
        migrations.AlterField(
            model_name="meetupevent",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event banner image (recommended: 1200x600px, 2:1 ratio for best results)",
                null=True,
                storage=crush_lu.storage.get_crush_media_storage,
                upload_to=functools.partial(
                    crush_lu.storage._domain_upload_path,
                    *("crush-lu", "events/banners"),
                    **{}
                ),
            ),
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body_html",
                    models.TextField(help_text="Newsletter body content (HTML)"),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text fallback (auto-stripped from HTML if blank)",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_users", "All registered users"),
                            ("all_profiles", "Users who created a profile"),
                            ("approved_profiles", "Users with approved profiles"),
                            ("segment", "Specific user segment"),
                        ],
                        default="all_users",
                        max_length=20,
                    ),
                ),
                (
                    "segment_key",
                    models.CharField(
                        blank=True,
                        help_text="Segment key from user_segments.py (only used when audience='segment')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("total_skipped", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email snapshot at send time", max_length=254
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="crush_lu.newsletter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Recipient",
                "verbose_name_plural": "Newsletter Recipients",
                "indexes": [
                    models.Index(
                        fields=["newsletter", "status"],
                        name="crush_lu_ne_newslet_92696a_idx",
                    )
                ],
                "unique_together": {("newsletter", "user")},
            },
        ),
    ]
