# Generated by Django 5.1.15 on 2026-02-06 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0068_newsletter_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "powerup_consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="User consents to PowerUp identity layer (User model + OAuth data)",
                    ),
                ),
                ("powerup_consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "powerup_consent_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "powerup_terms_version",
                    models.CharField(default="1.0", max_length=10),
                ),
                (
                    "crushlu_consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="User consents to Crush.lu profile layer (dating profile + photos)",
                    ),
                ),
                ("crushlu_consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "crushlu_consent_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "crushlu_terms_version",
                    models.CharField(default="1.0", max_length=10),
                ),
                (
                    "crushlu_banned",
                    models.BooleanField(
                        default=False,
                        help_text="User is permanently banned from creating new Crush.lu profiles",
                    ),
                ),
                ("crushlu_ban_date", models.DateTimeField(blank=True, null=True)),
                (
                    "crushlu_ban_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_deletion", "User deleted profile"),
                            ("admin_action", "Admin action"),
                            ("terms_violation", "Terms violation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="User consents to marketing communications",
                    ),
                ),
                ("marketing_consent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Data Consent",
                "verbose_name_plural": "User Data Consents",
            },
        ),
    ]
