# Generated by Django 5.1.15 on 2026-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0069_add_user_data_consent_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushcoach",
            name="bio_de",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="bio_en",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="bio_fr",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="specializations_de",
            field=models.CharField(
                blank=True,
                help_text="e.g., Young professionals, Students, 30+, etc.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="specializations_en",
            field=models.CharField(
                blank=True,
                help_text="e.g., Young professionals, Students, 30+, etc.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="specializations_fr",
            field=models.CharField(
                blank=True,
                help_text="e.g., Young professionals, Students, 30+, etc.",
                max_length=200,
                null=True,
            ),
        ),
    ]
