# Generated by Django 5.1.15 on 2026-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0070_add_crushcoach_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushcoach",
            name="spoken_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages the coach can speak for profile reviews",
            ),
        ),
    ]
