# Generated by Django 5.1.15 on 2026-02-09 00:20

import crush_lu.storage
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0071_add_spoken_languages_to_crushcoach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event banner image (recommended: 1200x600px, 2:1 ratio for best results)",
                null=True,
                storage=crush_lu.storage.get_crush_media_storage,
                upload_to=functools.partial(
                    crush_lu.storage._domain_upload_path, *("", "events/banners"), **{}
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="eventconnection",
            index=models.Index(
                fields=["event", "status"], name="crush_lu_conn_event_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventconnection",
            index=models.Index(
                fields=["requester", "status"], name="crush_lu_conn_req_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventconnection",
            index=models.Index(
                fields=["recipient", "status"], name="crush_lu_conn_recip_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilesubmission",
            index=models.Index(
                fields=["status", "submitted_at"], name="crush_lu_prof_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilesubmission",
            index=models.Index(
                fields=["status", "coach"], name="crush_lu_prof_status_coach_idx"
            ),
        ),
    ]
