# Generated by Django 5.1.15 on 2026-02-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0072_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushprofile",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="crushprofile",
            name="phone_verification_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Firebase UID from phone verification (for audit/anti-replay)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profilesubmission",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crush_lu.crushcoach",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="last_pwa_visit",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time user accessed via PWA (standalone mode)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="last_seen",
            field=models.DateTimeField(
                db_index=True, help_text="Last time user made a request"
            ),
        ),
    ]
