# Generated by Django 5.1.15 on 2026-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0073_add_indexes_and_coach_cascade_protection"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="language",
            field=models.CharField(
                choices=[
                    ("all", "All languages"),
                    ("en", "English"),
                    ("de", "German"),
                    ("fr", "French"),
                ],
                default="all",
                help_text="Restrict recipients to this language. Use 'All' to send to everyone.",
                max_length=5,
            ),
        ),
    ]
