# Generated by Django 5.1.15 on 2026-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0074_newsletter_language_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="social_facebook_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.facebook.com/crush.lu",
                verbose_name="Facebook URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="social_google_business_url",
            field=models.URLField(
                blank=True,
                help_text="Your Google Business Profile URL",
                verbose_name="Google Business URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="social_instagram_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.instagram.com/crush.lu",
                verbose_name="Instagram URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="social_linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.linkedin.com/company/crush-lu",
                verbose_name="LinkedIn URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="social_reddit_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.reddit.com/r/crushlu",
                verbose_name="Reddit URL",
            ),
        ),
    ]
