# Generated by Django 5.1.15 on 2026-02-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0075_add_social_media_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an event to auto-generate announcement content per-user in their language",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newsletters",
                to="crush_lu.meetupevent",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="body_html",
            field=models.TextField(
                blank=True,
                help_text="Newsletter body content (HTML). Auto-generated when event is selected.",
            ),
        ),
    ]
