# Generated by Django 5.1.15 on 2026-02-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0076_newsletter_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all_users", "All registered users"),
                    ("all_profiles", "Users who created a profile"),
                    ("approved_profiles", "Users with approved profiles"),
                    ("pending_review", "Users awaiting coach approval"),
                    ("segment", "Specific user segment"),
                ],
                default="all_users",
                max_length=20,
            ),
        ),
    ]
