# Generated by Django 5.1.15 on 2026-02-14 21:54

import crush_lu.models.crush_spark
import crush_lu.models.profiles
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0077_newsletter_pending_review_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="max_sparks_per_event",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of Crush Sparks a user can send per event",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="spark_request_deadline_hours",
            field=models.PositiveIntegerField(
                default=168,
                help_text="Hours after event end until spark requests close (default: 7 days)",
            ),
        ),
        migrations.CreateModel(
            name="CrushSpark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("coach_assigned", "Coach Assigned"),
                            ("journey_created", "Journey Created"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "sender_description",
                    models.TextField(
                        help_text="Describe the person you liked (e.g. 'person in red dress who talked about hiking')"
                    ),
                ),
                (
                    "coach_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from coach about this assignment",
                    ),
                ),
                ("is_sender_revealed", models.BooleanField(default=False)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender_message",
                    models.TextField(
                        blank=True, help_text="Personal message revealed in Chapter 6"
                    ),
                ),
                (
                    "chapter1_image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo for Chapter 1 puzzle reveal (recommended: 800x800px)",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter1_image_path,
                    ),
                ),
                (
                    "chapter3_image_1",
                    models.ImageField(
                        blank=True,
                        help_text="First slideshow photo",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter3_image_path,
                    ),
                ),
                (
                    "chapter3_image_2",
                    models.ImageField(
                        blank=True,
                        help_text="Second slideshow photo",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter3_image_path,
                    ),
                ),
                (
                    "chapter3_image_3",
                    models.ImageField(
                        blank=True,
                        help_text="Third slideshow photo",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter3_image_path,
                    ),
                ),
                (
                    "chapter3_image_4",
                    models.ImageField(
                        blank=True,
                        help_text="Fourth slideshow photo",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter3_image_path,
                    ),
                ),
                (
                    "chapter3_image_5",
                    models.ImageField(
                        blank=True,
                        help_text="Fifth slideshow photo",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter3_image_path,
                    ),
                ),
                (
                    "chapter4_video",
                    models.FileField(
                        blank=True,
                        help_text="Video message for Chapter 4 (MP4, MOV - max 50MB)",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter4_video_path,
                    ),
                ),
                (
                    "chapter5_letter_music",
                    models.FileField(
                        blank=True,
                        help_text="Background music for Chapter 5 letter (MP3, WAV, M4A - max 10MB)",
                        max_length=255,
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to=crush_lu.models.crush_spark.spark_chapter5_audio_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("coach_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("journey_created_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-set to created_at + 14 days",
                        null=True,
                    ),
                ),
                (
                    "assigned_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sparks",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparks",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_spark",
                        to="crush_lu.journeyconfiguration",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_sparks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_sparks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "special_experience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_spark",
                        to="crush_lu.specialuserexperience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crush Spark",
                "verbose_name_plural": "Crush Sparks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"], name="crushspark_event_status"
                    ),
                    models.Index(
                        fields=["sender", "event"], name="crushspark_sender_event"
                    ),
                ],
            },
        ),
    ]
