# Generated by Django 5.1.15 on 2026-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0078_meetupevent_max_sparks_per_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushspark",
            name="sender_description",
            field=models.TextField(
                blank=True,
                help_text="Describe the person you liked (e.g. 'person in red dress who talked about hiking')",
            ),
        ),
        migrations.AlterField(
            model_name="crushspark",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("pending_review", "Pending Review"),
                    ("coach_approved", "Coach Approved"),
                    ("coach_assigned", "Coach Assigned"),
                    ("journey_created", "Journey Created"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
            ),
        ),
    ]
