# Generated by Django 5.1.15 on 2026-02-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0079_spark_pending_review_and_coach_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the attendee was checked in via QR scan",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Signed token for QR check-in",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="google_wallet_ticket_object_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Wallet EventTicketObject ID",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="google_wallet_event_class_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Wallet EventTicketClass ID for this event",
                max_length=128,
            ),
        ),
    ]
