# Generated by Django 5.1.15 on 2026-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0080_event_qr_checkin_and_wallet_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages this event will be conducted in (e.g. ['en', 'fr']). Empty list means no language restriction.",
            ),
        ),
    ]
