# Generated by Django 5.1.15 on 2026-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0082_meetupevent_coaches"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="max_participants_f",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum confirmed spots for Female attendees. Leave blank to use total-only cap.",
                null=True,
                verbose_name="Max spots (Women)",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="max_participants_m",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum confirmed spots for Male attendees. Leave blank to use total-only cap.",
                null=True,
                verbose_name="Max spots (Men)",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="max_participants_nb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum confirmed spots for Non-binary/Other/Prefer-not-to-say. Leave blank to use total-only cap.",
                null=True,
                verbose_name="Max spots (Other genders)",
            ),
        ),
    ]
