# Generated by Django 5.1.15 on 2026-02-23 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0083_add_gender_capacity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventactivityvote',
            unique_together={('event', 'user')},
        ),
        migrations.AlterField(
            model_name='eventactivityvote',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.eventactivityoption'),
        ),
    ]
