# Generated by Django 5.1.15 on 2026-02-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0085_phone_validator_and_coach_on_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedProfile",
            fields=[],
            options={
                "verbose_name": "Approved Profile",
                "verbose_name_plural": "Approved Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.CreateModel(
            name="AwaitingReviewProfile",
            fields=[],
            options={
                "verbose_name": "Awaiting Review Profile",
                "verbose_name_plural": "Awaiting Review Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.CreateModel(
            name="IncompleteProfile",
            fields=[],
            options={
                "verbose_name": "Incomplete Profile",
                "verbose_name_plural": "Incomplete Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
    ]
