# Generated by Django 5.1.15 on 2026-02-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0086_approvedprofile_awaitingreviewprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Completed Submission',
                'verbose_name_plural': 'Completed Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crush_lu.profilesubmission',),
        ),
        migrations.CreateModel(
            name='InProcessSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'In-Process Submission',
                'verbose_name_plural': 'In-Process Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crush_lu.profilesubmission',),
        ),
    ]
