# Generated by Django 5.1.15 on 2026-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0087_completedsubmission_inprocesssubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="preferred_age_max",
            field=models.PositiveSmallIntegerField(
                default=99, help_text="Maximum preferred age"
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="preferred_age_min",
            field=models.PositiveSmallIntegerField(
                default=18, help_text="Minimum preferred age"
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="preferred_genders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Gender codes the user is interested in",
            ),
        ),
    ]
