# Generated by Django 5.1.15 on 2026-02-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0088_crushprofile_preferred_age_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_template_de",
            field=models.CharField(
                blank=True,
                default="Hallo {first_name}, hier ist {coach_name} von Crush.lu. Ich habe versucht, dich wegen deiner Profilverifizierung anzurufen. Könntest du mich zurückrufen? Danke!",
                help_text="Placeholders: {first_name}, {coach_name}",
                max_length=320,
                verbose_name="SMS template (German)",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_template_en",
            field=models.CharField(
                blank=True,
                default="Hi {first_name}, this is {coach_name} from Crush.lu. I tried calling you regarding your profile verification. Could you call me back when you have a moment? Thanks!",
                help_text="Placeholders: {first_name}, {coach_name}",
                max_length=320,
                verbose_name="SMS template (English)",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_template_fr",
            field=models.CharField(
                blank=True,
                default="Bonjour {first_name}, c'est {coach_name} de Crush.lu. J'ai essayé de vous appeler concernant la vérification de votre profil. Pourriez-vous me rappeler ? Merci !",
                help_text="Placeholders: {first_name}, {coach_name}",
                max_length=320,
                verbose_name="SMS template (French)",
            ),
        ),
        migrations.AlterField(
            model_name="callattempt",
            name="result",
            field=models.CharField(
                choices=[
                    ("success", "Call Completed"),
                    ("failed", "Call Failed"),
                    ("sms_sent", "SMS Sent"),
                ],
                help_text="Whether the call succeeded or failed",
                max_length=20,
            ),
        ),
    ]
