# Generated by Django 5.1.15 on 2026-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0089_add_sms_template_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingReviewProfile",
            fields=[],
            options={
                "verbose_name": "Pending Review Profile",
                "verbose_name_plural": "Pending Review Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.CreateModel(
            name="RecontactCoachProfile",
            fields=[],
            options={
                "verbose_name": "Recontact Coach Profile",
                "verbose_name_plural": "Recontact Coach Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.CreateModel(
            name="RejectedProfile",
            fields=[],
            options={
                "verbose_name": "Rejected Profile",
                "verbose_name_plural": "Rejected Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.CreateModel(
            name="RevisionNeededProfile",
            fields=[],
            options={
                "verbose_name": "Revision Needed Profile",
                "verbose_name_plural": "Revision Needed Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crush_lu.crushprofile",),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="max_cross_gender_connections",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum cross-gender connection requests per user per event (0 = unlimited). Same-gender connections are always unlimited.",
            ),
        ),
    ]
