# Generated by Django 5.1.15 on 2026-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0090_pendingreviewprofile_recontactcoachprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_enabled",
            field=models.BooleanField(default=False, verbose_name="Banner enabled"),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_text",
            field=models.CharField(
                blank=True,
                help_text="Optional CTA button text (leave blank for no link).",
                max_length=100,
                verbose_name="Banner link text",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_text_de",
            field=models.CharField(
                blank=True,
                help_text="Optional CTA button text (leave blank for no link).",
                max_length=100,
                null=True,
                verbose_name="Banner link text",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_text_en",
            field=models.CharField(
                blank=True,
                help_text="Optional CTA button text (leave blank for no link).",
                max_length=100,
                null=True,
                verbose_name="Banner link text",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_text_fr",
            field=models.CharField(
                blank=True,
                help_text="Optional CTA button text (leave blank for no link).",
                max_length=100,
                null=True,
                verbose_name="Banner link text",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_url",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /events/) or full URL.",
                max_length=500,
                verbose_name="Banner link URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_message",
            field=models.TextField(
                blank=True,
                help_text="The message to display in the banner.",
                verbose_name="Banner message",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_message_de",
            field=models.TextField(
                blank=True,
                help_text="The message to display in the banner.",
                null=True,
                verbose_name="Banner message",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_message_en",
            field=models.TextField(
                blank=True,
                help_text="The message to display in the banner.",
                null=True,
                verbose_name="Banner message",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_message_fr",
            field=models.TextField(
                blank=True,
                help_text="The message to display in the banner.",
                null=True,
                verbose_name="Banner message",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_style",
            field=models.CharField(
                choices=[
                    ("info", "Info (blue)"),
                    ("warning", "Warning (amber)"),
                    ("success", "Success (green)"),
                    ("purple", "Purple"),
                ],
                default="info",
                max_length=10,
                verbose_name="Banner style",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_target_statuses",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Show banner only to users with these submission statuses. Empty = show to ALL authenticated users.",
                verbose_name="Target profile statuses",
            ),
        ),
    ]
