# Generated by Django 5.1.15 on 2026-03-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0091_crushsiteconfig_banner_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_url_de",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /events/) or full URL.",
                max_length=500,
                null=True,
                verbose_name="Banner link URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_url_en",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /events/) or full URL.",
                max_length=500,
                null=True,
                verbose_name="Banner link URL",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="banner_link_url_fr",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /events/) or full URL.",
                max_length=500,
                null=True,
                verbose_name="Banner link URL",
            ),
        ),
    ]
