# Generated by Django 5.1.15 on 2026-03-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0092_add_banner_link_url_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="first_step_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("i_initiate", "I prefer to make the first step"),
                    (
                        "they_initiate",
                        "I prefer the other person to make the first step",
                    ),
                    ("no_preference", "No preference"),
                ],
                default="",
                help_text="Who should make the first step?",
                max_length=20,
            ),
        ),
    ]
