# Generated by Django 6.0.3 on 2026-03-20 18:14

from django.conf import settings
from django.db import migrations, models


def deduplicate_phone_numbers(apps, schema_editor):
    """Clear duplicate phone numbers before adding unique constraint.

    Keeps the phone number on the most recently updated profile,
    clears it on all other profiles with the same number.
    """
    CrushProfile = apps.get_model('crush_lu', 'CrushProfile')
    from django.db.models import Count

    duplicates = (
        CrushProfile.objects.exclude(phone_number='')
        .exclude(phone_number__isnull=True)
        .values('phone_number')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for entry in duplicates:
        phone = entry['phone_number']
        profiles = CrushProfile.objects.filter(phone_number=phone).order_by('-updated_at', '-id')
        # Keep the first one (most recently updated), clear the rest
        profiles_to_clear = profiles[1:]
        CrushProfile.objects.filter(id__in=[p.id for p in profiles_to_clear]).update(
            phone_number='',
            phone_verified=False,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0102_callattempt_nullable_submission_add_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_phone_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='crushprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='unique_non_empty_phone_number'),
        ),
    ]
