# Generated by Django 6.0.3 on 2026-03-20 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0102_callattempt_nullable_submission_add_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crushprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='unique_non_empty_phone_number'),
        ),
    ]
