# Generated by Django 6.0.3 on 2026-03-22 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0103_unique_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventactivityvote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventactivityvote',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crush_lu.globalactivityoption'),
        ),
        migrations.AlterUniqueTogether(
            name='eventactivityvote',
            unique_together={('event', 'user', 'selected_option')},
        ),
    ]
