# Generated by Django 6.0.3 on 2026-03-25 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0104_alter_eventactivityvote_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="astro_enabled",
            field=models.BooleanField(
                default=True, help_text="Include zodiac compatibility in matching score"
            ),
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier, e.g. 'patient' or 'stubborn'",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "trait_type",
                    models.CharField(
                        choices=[("quality", "Quality"), ("defect", "Defect")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("social", "Social"),
                            ("emotional", "Emotional"),
                            ("mindset", "Mindset"),
                            ("relational", "Relational"),
                            ("energy", "Energy"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "opposite",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opposite trait (quality ↔ defect pair)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opposite_of",
                        to="crush_lu.trait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trait",
                "verbose_name_plural": "Traits",
                "ordering": ["trait_type", "sort_order"],
            },
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="defects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Your top 5 defects (max 5)",
                limit_choices_to={"trait_type": "defect"},
                related_name="profiles_as_defect",
                to="crush_lu.trait",
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="qualities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Your top 5 qualities (max 5)",
                limit_choices_to={"trait_type": "quality"},
                related_name="profiles_as_quality",
                to="crush_lu.trait",
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="sought_qualities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Top 5 qualities you seek in a partner (max 5)",
                limit_choices_to={"trait_type": "quality"},
                related_name="profiles_seeking",
                to="crush_lu.trait",
            ),
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_qualities", models.FloatField(default=0)),
                ("score_zodiac_west", models.FloatField(default=0)),
                ("score_zodiac_cn", models.FloatField(default=0)),
                ("score_final", models.FloatField(db_index=True, default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Score",
                "verbose_name_plural": "Match Scores",
                "ordering": ["-score_final"],
                "indexes": [
                    models.Index(
                        fields=["user_a", "score_final"],
                        name="crush_lu_ma_user_a__a5fc7a_idx",
                    ),
                    models.Index(
                        fields=["user_b", "score_final"],
                        name="crush_lu_ma_user_b__35fafc_idx",
                    ),
                ],
                "unique_together": {("user_a", "user_b")},
            },
        ),
    ]
