# Generated by Django 6.0.3 on 2026-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0106_seed_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='score_age_fit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='score_language',
            field=models.FloatField(default=0),
        ),
    ]
