# Generated by Django 6.0.3 on 2026-03-28 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0107_add_language_age_fit_to_matchscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='draft', max_length=10)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='crush_lu.meetupevent')),
            ],
            options={
                'verbose_name': 'Quiz Event',
                'verbose_name_plural': 'Quiz Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('time_per_question', models.PositiveIntegerField(default=30, help_text='Seconds allowed per question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='crush_lu.quizevent')),
            ],
            options={
                'verbose_name': 'Quiz Round',
                'verbose_name_plural': 'Quiz Rounds',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False')], default='multiple_choice', max_length=20)),
                ('choices', models.JSONField(help_text='List of {"text": "...", "is_correct": true/false}')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=10)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='crush_lu.quizround')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='quizevent',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crush_lu.quizround'),
        ),
        migrations.CreateModel(
            name='QuizTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='crush_lu.quizevent')),
            ],
            options={
                'verbose_name': 'Quiz Table',
                'verbose_name_plural': 'Quiz Tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizTableMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crush_lu.quiztable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Membership',
                'verbose_name_plural': 'Table Memberships',
                'unique_together': {('table', 'user')},
            },
        ),
        migrations.AddField(
            model_name='quiztable',
            name='members',
            field=models.ManyToManyField(related_name='quiz_tables', through='crush_lu.QuizTableMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(help_text='The chosen answer')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='crush_lu.quizevent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='crush_lu.quizquestion')),
            ],
            options={
                'verbose_name': 'Individual Score',
                'verbose_name_plural': 'Individual Scores',
                'ordering': ['-answered_at'],
                'unique_together': {('quiz', 'user', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='quiztable',
            unique_together={('quiz', 'table_number')},
        ),
    ]
