# Generated by Django 6.0.3 on 2026-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0109_quizquestion_correct_answer_quizround_is_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='current_question_index',
            field=models.IntegerField(default=-1),
        ),
    ]
