# Generated by Django 6.0.3 on 2026-04-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0112_crushcoach_phone_number"),
        ("crush_lu", "0112_require_plus_prefix_phone_validator"),
    ]

    operations = []
