# Generated by Django 6.0.3 on 2026-04-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0114_quizevent_question_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='choices_de',
            field=models.JSONField(blank=True, default=list, help_text='List of {"text": "...", "is_correct": true/false}', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choices_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {"text": "...", "is_correct": true/false}', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choices_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of {"text": "...", "is_correct": true/false}', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer_de',
            field=models.CharField(blank=True, help_text='Reference answer for host (used for open-ended questions)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer_en',
            field=models.CharField(blank=True, help_text='Reference answer for host (used for open-ended questions)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer_fr',
            field=models.CharField(blank=True, help_text='Reference answer for host (used for open-ended questions)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizround',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizround',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizround',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
