# Generated by Django 6.0.3 on 2026-04-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0117_add_event_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crushprofile',
            name='blur_photos',
        ),
    ]
