# Generated by Django 6.0.3 on 2026-04-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0118_remove_blur_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crushprofile',
            name='looking_for',
        ),
    ]
