# Generated by Django 6.0.3 on 2026-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0119_remove_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizevent",
            name="display_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shared secret for projector display access. Leave blank for unrestricted access.",
                max_length=32,
            ),
        ),
    ]
