# Generated by Django 6.0.3 on 2026-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0120_quiz_display_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesubmission",
            name="candidate_note",
            field=models.TextField(
                blank=True,
                help_text="Optional note from candidate to coach during review wait",
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="candidate_note_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the candidate submitted their note",
                null=True,
            ),
        ),
    ]
