# Generated by Django 6.0.4 on 2026-04-19 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0123_migrate_newsletter_content_to_en"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "user", "status"], name="eventreg_event_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["user", "status"], name="eventreg_user_status"),
        ),
    ]
