# Generated by Django 6.0.4 on 2026-04-19 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0124_add_event_registration_user_status_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushcoach",
            name="availability_windows",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of weekly availability windows, each {'day': 'tuesday', 'start': '18:00', 'end': '21:00', 'label': 'Tuesday evenings'}",
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="away_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional end date for the away period. NULL = indefinite",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="hybrid_features_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Per-coach opt-in flag for the Hybrid Coach Review System. Gated in addition to settings.HYBRID_COACH_SYSTEM_ENABLED.",
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="is_away",
            field=models.BooleanField(
                default=False,
                help_text="Temporarily exclude this coach from new assignments",
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="working_mode",
            field=models.CharField(
                choices=[
                    ("spontaneous", "Spontaneous — I call users on my own schedule"),
                    ("hybrid", "Hybrid — I call users but also accept bookings"),
                    ("booking", "Booking-first — users pick a slot from my calendar"),
                ],
                default="spontaneous",
                help_text="How this coach prefers to conduct screening calls",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When a coach was assigned. Used as the SLA anchor.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="booking_token",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Opaque token used in booking URLs; 30-day expiry.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="booking_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="escalated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this submission was auto-reassigned after SLA breach.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="fallback_offered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user was shown the self-booking fallback.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="is_paused",
            field=models.BooleanField(
                default=False,
                help_text="User action required before the submission can proceed.",
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="nudge_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 36h coach nudge was sent (sentinel to prevent repeats).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="paused_reason",
            field=models.CharField(
                blank=True,
                help_text="Short machine-readable reason, e.g. 'recontact_timeout'.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="recontact_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When status became 'recontact_coach' (used for 14-day expiry).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="sla_deadline",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this submission must be reviewed by (assigned_at + 48h).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="system_actions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ScreeningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("cancelled_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_slots",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_slots",
                        to="crush_lu.profilesubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
                "indexes": [
                    models.Index(
                        fields=["coach", "status", "start_at"],
                        name="crush_lu_sc_coach_i_1db28b_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="screening_slot_end_after_start",
                    )
                ],
            },
        ),
    ]
