# Generated by Django 6.0.4 on 2026-04-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0126_hybrid_coach_backfill"),
        ("crush_lu", "0127_add_screening_call_mode"),
    ]

    operations = []
