# Generated by Django 6.0.4 on 2026-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0128_merge_20260420_1004"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="screeningslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "booked")),
                fields=("coach", "start_at", "end_at"),
                name="screening_slot_unique_booked_per_coach_time",
            ),
        ),
    ]
