# Generated by Django 6.0.4 on 2026-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0129_add_unique_booked_slot_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="intent_probe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("events", "I want to meet people at real events"),
                    ("curious", "I'm curious but still exploring"),
                    ("online", "I want online dating, events are a bonus"),
                    ("friend", "A friend recommended it"),
                ],
                help_text="Which of the 4 intent options the user picked on /welcome/.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="welcome_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First time the user saw the /welcome/ page. Gates re-entry.",
                null=True,
            ),
        ),
    ]
