# Generated by Django 6.0.4 on 2026-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0130_crushprofile_intent_probe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="coach_intro_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First time the user saw the step-3 coach intro page. Advances the journey past step 3.",
                null=True,
            ),
        ),
    ]
