# Generated by Django 6.0.4 on 2026-04-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0131_patchnote_auto_generated_and_patchrelease_index"),
        ("crush_lu", "0133_alter_crushprofile_completion_status"),
    ]

    operations = []
