# Generated by Django 6.0.4 on 2026-05-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0135_callattempt_whatsapp_sent_choice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="feedback_request_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp the post-event feedback survey email was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="recap_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp the post-event recap email was sent",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nps_score",
                    models.PositiveSmallIntegerField(
                        help_text="Net Promoter Score: 0 (would not recommend) to 10 (would strongly recommend)"
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        default=True,
                        help_text="Quick yes/no convenience flag derived from NPS at submission time",
                    ),
                ),
                (
                    "what_worked",
                    models.TextField(
                        blank=True,
                        help_text="Free-text: what the attendee enjoyed. Visible to coaches only.",
                    ),
                ),
                (
                    "what_to_improve",
                    models.TextField(
                        blank=True,
                        help_text="Free-text: suggestions for next event. Visible to coaches only.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-created_at"],
                        name="crush_lu_ev_event_i_13e4dd_idx",
                    )
                ],
                "unique_together": {("event", "user")},
            },
        ),
    ]
