# Generated by Django 6.0.4 on 2026-05-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0136_eventregistration_feedback_request_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="connection_intro_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {category, language, body, is_active} entries used as starter text on the coach connection-review page.",
                verbose_name="Coach connection-intro templates",
            ),
        ),
    ]
