# Generated by Django 6.0.4 on 2026-05-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0138_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesubmission",
            name="revision_round",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of completed revision cycles. 0 = first review. Incremented when a coach issues a 'revision' verdict so the next review surfaces the resubmission banner.",
            ),
        ),
    ]
