# Generated by Django 6.0.4 on 2026-05-14 15:59
# Schema + initial 10 prompt seed for Crush Connect M1.

from django.db import migrations, models


SEED_PROMPTS = [
    {
        "weight": 3,
        "text_en": "What in their profile made you curious?",
        "text_de": "Was an ihrem Profil hat dich neugierig gemacht?",
        "text_fr": "Qu'est-ce qui, dans son profil, a éveillé ta curiosité ?",
    },
    {
        "weight": 2,
        "text_en": "What would your perfect first meetup look like?",
        "text_de": "Wie würde dein perfektes erstes Treffen aussehen?",
        "text_fr": "À quoi ressemblerait votre première rencontre idéale ?",
    },
    {
        "weight": 2,
        "text_en": "What's a small thing that delights you?",
        "text_de": "Was ist eine kleine Sache, die dich begeistert?",
        "text_fr": "Quelle est une petite chose qui t'enchante ?",
    },
    {
        "weight": 2,
        "text_en": "Share a moment from a recent event you enjoyed.",
        "text_de": "Erzähle von einem Moment bei einer kürzlichen Veranstaltung, der dir gefallen hat.",
        "text_fr": "Partage un moment d'un événement récent que tu as apprécié.",
    },
    {
        "weight": 1,
        "text_en": "What's a place in Luxembourg you'd love to share with someone?",
        "text_de": "Welcher Ort in Luxemburg würdest du gerne mit jemandem teilen?",
        "text_fr": "Quel endroit au Luxembourg aimerais-tu partager avec quelqu'un ?",
    },
    {
        "weight": 1,
        "text_en": "What's something you're learning right now?",
        "text_de": "Was lernst du gerade Neues?",
        "text_fr": "Qu'apprends-tu en ce moment ?",
    },
    {
        "weight": 1,
        "text_en": "What's the last thing that made you laugh out loud?",
        "text_de": "Was hat dich zuletzt laut zum Lachen gebracht?",
        "text_fr": "Qu'est-ce qui t'a fait éclater de rire récemment ?",
    },
    {
        "weight": 1,
        "text_en": "Describe your ideal Sunday in three words.",
        "text_de": "Beschreibe deinen idealen Sonntag in drei Worten.",
        "text_fr": "Décris ton dimanche idéal en trois mots.",
    },
    {
        "weight": 1,
        "text_en": "What's a song that's been on repeat for you lately?",
        "text_de": "Welches Lied hörst du in letzter Zeit immer wieder?",
        "text_fr": "Quelle chanson écoutes-tu en boucle ces derniers temps ?",
    },
    {
        "weight": 1,
        "text_en": "If you could plan our first activity, what would it be?",
        "text_de": "Wenn du unsere erste Aktivität planen könntest, was wäre das?",
        "text_fr": "Si tu pouvais planifier notre première activité, quelle serait-elle ?",
    },
]


def seed_prompts(apps, schema_editor):
    SparkPrompt = apps.get_model("crush_lu", "SparkPrompt")
    for row in SEED_PROMPTS:
        SparkPrompt.objects.create(
            text=row["text_en"],
            text_en=row["text_en"],
            text_de=row["text_de"],
            text_fr=row["text_fr"],
            is_active=True,
            weight=row["weight"],
        )


def unseed_prompts(apps, schema_editor):
    SparkPrompt = apps.get_model("crush_lu", "SparkPrompt")
    SparkPrompt.objects.filter(
        text_en__in=[row["text_en"] for row in SEED_PROMPTS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0141_connection_window_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparkPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Prompt text shown to the sender (translated via modeltranslation)",
                        max_length=200,
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        help_text="Prompt text shown to the sender (translated via modeltranslation)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "text_de",
                    models.CharField(
                        help_text="Prompt text shown to the sender (translated via modeltranslation)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "text_fr",
                    models.CharField(
                        help_text="Prompt text shown to the sender (translated via modeltranslation)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive prompts stop being offered to senders but stay linked from historical Sparks",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Rotation weight (higher = more often)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spark Prompt",
                "verbose_name_plural": "Spark Prompts",
                "ordering": ["-is_active", "-weight", "id"],
            },
        ),
        migrations.RunPython(seed_prompts, unseed_prompts),
    ]
