# Generated by Django 6.0.4 on 2026-05-14 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0142_sparkprompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrushConnectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onboarded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the user completes Crush Connect onboarding. Null = waitlisted/not opted-in.",
                        null=True,
                    ),
                ),
                (
                    "excluded_by_coach",
                    models.BooleanField(
                        default=False,
                        help_text="Coach exclusion — removes the user from every Crush Connect pool",
                    ),
                ),
                ("excluded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exclusion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this user was excluded (audit trail; never shown to the user)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "excluded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connect_exclusions_made",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crush_connect_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crush Connect Membership",
                "verbose_name_plural": "Crush Connect Memberships",
            },
        ),
    ]
