# Generated by Django 6.0.4 on 2026-05-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0143_crushconnectmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectDailyDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drop_date",
                    models.DateField(
                        help_text="The local date this Drop was generated for"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connect_drops_appeared_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_drops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crush Connect Daily Drop",
                "verbose_name_plural": "Crush Connect Daily Drops",
                "ordering": ["-drop_date", "user_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "drop_date"), name="connect_drop_unique_per_day"
                    )
                ],
            },
        ),
    ]
