# Generated by Django 6.0.4 on 2026-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0143_presentationrating_is_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_last_minute_invite_template_de",
            field=models.CharField(
                blank=True,
                default="Hi {first_name}! Ein Platz ist gerade frei geworden fuer {event_title} HEUTE ({event_date})! Hier ist {coach_name} von Crush.lu — komm dazu! {event_url}",
                help_text="Placeholders: {first_name}, {coach_name}, {event_title}, {event_date}, {event_url}",
                max_length=320,
                verbose_name="Last-minute invite SMS (German)",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_last_minute_invite_template_en",
            field=models.CharField(
                blank=True,
                default="Hi {first_name}! A spot just opened up for {event_title} TONIGHT ({event_date})! {coach_name} from Crush.lu here — join us! {event_url}",
                help_text="Placeholders: {first_name}, {coach_name}, {event_title}, {event_date}, {event_url}",
                max_length=320,
                verbose_name="Last-minute invite SMS (English)",
            ),
        ),
        migrations.AddField(
            model_name="crushsiteconfig",
            name="sms_last_minute_invite_template_fr",
            field=models.CharField(
                blank=True,
                default="Salut {first_name} ! Une place vient de se liberer pour {event_title} CE SOIR ({event_date}) ! C'est {coach_name} de Crush.lu — rejoins-nous ! {event_url}",
                help_text="Placeholders: {first_name}, {coach_name}, {event_title}, {event_date}, {event_url}",
                max_length=320,
                verbose_name="Last-minute invite SMS (French)",
            ),
        ),
        migrations.AlterField(
            model_name="meetupevent",
            name="connection_window_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours after event start until post-event connection requests close (default: 24 = 1 day). After the window closes, attendees are redirected to the Crush Connect teaser.",
            ),
        ),
    ]
