# Generated by Django 6.0.4 on 2026-05-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0144_connectdailydrop"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="story_answer",
            field=models.CharField(
                blank=True,
                help_text="One-line answer shown on the member's Drop card",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="story_prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="The prompt this member chose to answer for their Drop card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_owners",
                to="crush_lu.sparkprompt",
            ),
        ),
    ]
