# Generated by Django 6.0.4 on 2026-05-26 17:49

from django.db import migrations


def fix_revision_completion_status(apps, schema_editor):
    """
    Profiles with a latest submission status of 'revision' should have
    completion_status='step4' so users can re-enter the wizard and resubmit.

    Previously, coach review actions never updated completion_status, so users
    who received a revision request were left stuck at 'submitted' — the wizard
    gate treated them as if they were pending rather than needing to act.

    Rejected profiles are intentionally left as-is: rejection is terminal, and
    the wizard immediately redirects rejected users to the profile_rejected page
    regardless of completion_status.
    """
    CrushProfile = apps.get_model("crush_lu", "CrushProfile")
    ProfileSubmission = apps.get_model("crush_lu", "ProfileSubmission")

    # Find all profiles whose latest submission is 'revision'
    # and whose completion_status is still 'submitted' (stuck)
    revision_profile_ids = (
        ProfileSubmission.objects.filter(status="revision")
        .values_list("profile_id", flat=True)
        .distinct()
    )

    fixed = 0
    for profile_id in revision_profile_ids:
        # Check if the latest submission for this profile is actually 'revision'
        latest = (
            ProfileSubmission.objects.filter(profile_id=profile_id)
            .order_by("-submitted_at")
            .first()
        )
        if latest and latest.status == "revision":
            updated = CrushProfile.objects.filter(
                pk=profile_id, completion_status="submitted"
            ).update(completion_status="step4")
            fixed += updated

    print(f"  Fixed {fixed} profiles: completion_status submitted -> step4 (revision pending)")


def reverse_fix(apps, schema_editor):
    pass  # No safe reverse; leave as-is


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0148_merge_crush_connect_foundations"),
    ]

    operations = [
        migrations.RunPython(fix_revision_completion_status, reverse_fix),
    ]
