# Generated by Django 6.0.4 on 2026-05-30 13:07

import django.db.models.deletion
from django.db import migrations, models


def backfill_verification_status(apps, schema_editor):
    CrushProfile = apps.get_model("crush_lu", "CrushProfile")
    for profile in CrushProfile.objects.only("pk", "is_approved", "completion_status"):
        if profile.is_approved:
            status = "verified"
        elif profile.completion_status in ("submitted", "step4"):
            status = "pending"
        else:
            status = "incomplete"
        CrushProfile.objects.filter(pk=profile.pk).update(verification_status=status)


def backfill_assigned_coach(apps, schema_editor):
    ProfileSubmission = apps.get_model("crush_lu", "ProfileSubmission")
    CrushProfile = apps.get_model("crush_lu", "CrushProfile")
    # Use the most recent approved submission with a coach to populate
    # assigned_coach. Iterate newest-first so that — combined with the
    # assigned_coach__isnull=True guard below — the latest approved coach
    # wins and older submissions are skipped.
    for sub in (
        ProfileSubmission.objects.filter(
            status="approved", coach__isnull=False, reviewed_at__isnull=False
        )
        .order_by("-reviewed_at")
        .values("profile_id", "coach_id", "reviewed_at")
    ):
        CrushProfile.objects.filter(
            pk=sub["profile_id"], assigned_coach__isnull=True
        ).update(
            assigned_coach_id=sub["coach_id"],
            assigned_coach_at=sub["reviewed_at"],
        )


class Migration(migrations.Migration):

    atomic = False  # FK + db_index in same txn hits PostgreSQL pending trigger events

    dependencies = [
        ("crush_lu", "0149_fix_revision_completion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="assigned_coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Permanently assigned coach (set at first event attendance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_members",
                to="crush_lu.crushcoach",
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="assigned_coach_at",
            field=models.DateTimeField(
                blank=True, help_text="When this coach was assigned", null=True
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="incomplete",
                help_text="User's verification and profile completion state",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_verification_status,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_assigned_coach,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
