# Generated by Django 6.0.4 on 2026-05-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0150_add_verification_status_and_assigned_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="profile_requirement",
            field=models.CharField(
                choices=[
                    ("approved", "Approved profile required"),
                    ("coach_assigned", "Premium member — coach assigned"),
                    ("unverified", "Unverified profile only"),
                    ("profile_exists", "Profile must exist"),
                    ("none", "No profile required"),
                ],
                default="approved",
                help_text="Controls what level of profile is needed to register for this event",
                max_length=20,
            ),
        ),
    ]
