# Generated by Django 6.0.4 on 2026-05-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0151_add_coach_assigned_profile_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="reserved_premium_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seats within the total capacity held back for premium (coach-assigned) members. General members fill only (max participants − reserved). 0 = no reservation.",
                verbose_name="Reserved premium seats",
            ),
        ),
    ]
