# Generated by Django 6.0.4 on 2026-06-02 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0153_add_verification_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crushcoach",
            name="accepting_premium",
            field=models.BooleanField(
                default=False,
                help_text="Show this coach in the premium directory for members to choose",
            ),
        ),
        migrations.AddField(
            model_name="crushcoach",
            name="max_premium_members",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Maximum number of premium members this coach takes on",
            ),
        ),
        migrations.CreateModel(
            name="PremiumMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_confirmed", models.BooleanField(default=False)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        help_text="The coach the member chose",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_memberships",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who confirmed payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_premium_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium Membership",
                "verbose_name_plural": "Premium Memberships",
                "ordering": ["-created_at"],
            },
        ),
    ]
