# Generated by Django 6.0.4 on 2026-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0154_crushcoach_accepting_premium_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushprofile",
            name="verification_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("luxid", "LuxID identity"),
                    ("coach_event", "Coach at event"),
                    ("premium_coach", "Premium coach"),
                    ("admin", "Verified by Crush.lu"),
                    ("legacy", "Legacy"),
                ],
                db_index=True,
                default="",
                help_text="How the profile became verified (set at the verification point)",
                max_length=20,
            ),
        ),
    ]
