# Generated by Django 6.0.4 on 2026-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0155_alter_crushprofile_verification_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="profile_requirement",
            field=models.CharField(
                choices=[
                    ("completed", "Completed profile (entry event)"),
                    ("approved", "Verified profile only (members)"),
                    ("coach_assigned", "Premium member — coach assigned"),
                    ("unverified", "Unverified profile only"),
                    ("profile_exists", "Profile must exist"),
                    ("none", "No profile required"),
                ],
                default="completed",
                help_text="Controls what level of profile is needed to register for this event",
                max_length=20,
            ),
        ),
    ]
