# Generated by Django 6.0.4 on 2026-06-08 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0156_alter_meetupevent_profile_requirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who confirmed the €10 payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_crush_connect_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="payment_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="€10/month payment confirmed by staff (manual, no processor)",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="selected_as_tester",
            field=models.BooleanField(
                default=False, help_text="Marked as one of the 20 beta testers"
            ),
        ),
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
