# Generated by Django 6.0.6 on 2026-06-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0159_connectcoachpick"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="lifestyle_energy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homebody", "Homebody"),
                    ("mix", "Mix of both"),
                    ("adventurer", "Adventurer"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="lifestyle_pace",
            field=models.CharField(
                blank=True,
                choices=[
                    ("structured", "Structured"),
                    ("balanced", "Balanced"),
                    ("spontaneous", "Spontaneous"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="lifestyle_social",
            field=models.CharField(
                blank=True,
                choices=[
                    ("intimate", "Deep 1:1s"),
                    ("flexible", "Depends on mood"),
                    ("social", "Group energy"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="relationship_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("serious", "Looking for something serious"),
                    ("open", "Open to see where it goes"),
                    ("curious", "Here to explore"),
                ],
                help_text="Member's relationship intent, set during Connect onboarding",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="story_answer_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="story_prompt_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_owners_2",
                to="crush_lu.sparkprompt",
            ),
        ),
    ]
