# Generated by Django 6.0.6 on 2026-06-13 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0160_crushconnectmembership_onboarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier, e.g. 'hiking' or 'live-music'",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        help_text="Display label (translated via modeltranslation)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("music", "Music"),
                            ("travel", "Travel"),
                            ("food", "Food & Drink"),
                            ("arts", "Arts & Culture"),
                            ("outdoors", "Outdoors"),
                            ("games", "Games"),
                            ("wellness", "Wellness"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Connect Interest",
                "verbose_name_plural": "Connect Interests",
                "ordering": ["category", "sort_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="drinking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Doesn't drink"),
                    ("socially", "Socially"),
                    ("regularly", "Regularly"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High school"),
                    ("vocational", "Vocational training"),
                    ("bachelor", "Bachelor's degree"),
                    ("master", "Master's degree"),
                    ("doctorate", "Doctorate"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="has_children",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No children"),
                    ("yes", "Has children"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Height in centimetres (optional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(120),
                    django.core.validators.MaxValueValidator(230),
                ],
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages this member speaks (codes from CONNECT_LANGUAGE_CHOICES)",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="onboarding_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="preferred_age_max",
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="preferred_age_min",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="preferred_genders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Genders this member wants to see in their Drop (empty = open to all)",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="relationship_timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ready_now", "Ready for a relationship now"),
                    ("few_months", "Open in the next few months"),
                    ("no_rush", "No rush, taking it slow"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="smoking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Non-smoker"),
                    ("occasionally", "Occasionally"),
                    ("yes", "Smoker"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="wants_children",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Wants children"),
                    ("open", "Open to it"),
                    ("no", "Doesn't want children"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="work_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("finance", "Finance"),
                    ("eu_public", "EU institutions & public sector"),
                    ("it", "IT & tech"),
                    ("health", "Healthcare"),
                    ("education", "Education"),
                    ("legal", "Legal"),
                    ("construction", "Construction & trades"),
                    ("hospitality", "Hospitality"),
                    ("logistics", "Logistics & transport"),
                    ("creative", "Creative & media"),
                    ("entrepreneur", "Entrepreneur / self-employed"),
                    ("student", "Student"),
                    ("other", "Other"),
                    ("prefer_not_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Curated interests & hobbies (cap of 8 enforced in the wizard)",
                related_name="interested_members",
                to="crush_lu.connectinterest",
            ),
        ),
    ]
