# Generated by Django 6.0.6 on 2026-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0160_crushconnectmembership_onboarding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="draft_step",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Last onboarding wizard step the user reached (1–4); used to resume.",
            ),
        ),
    ]
