# Generated by Django 6.0.6 on 2026-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0163_seed_connect_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="astro_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Include zodiac compatibility in this member's match score",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="defects",
            field=models.ManyToManyField(
                blank=True,
                help_text="This member's top 5 defects (max 5)",
                limit_choices_to={"trait_type": "defect"},
                related_name="connect_profiles_as_defect",
                to="crush_lu.trait",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="first_step_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("i_initiate", "I prefer to make the first step"),
                    (
                        "they_initiate",
                        "I prefer the other person to make the first step",
                    ),
                    ("no_preference", "No preference"),
                ],
                default="",
                help_text="Who should make the first step?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="qualities",
            field=models.ManyToManyField(
                blank=True,
                help_text="This member's top 5 qualities (max 5)",
                limit_choices_to={"trait_type": "quality"},
                related_name="connect_profiles_as_quality",
                to="crush_lu.trait",
            ),
        ),
        migrations.AddField(
            model_name="crushconnectmembership",
            name="sought_qualities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Top 5 qualities this member seeks in a partner (max 5)",
                limit_choices_to={"trait_type": "quality"},
                related_name="connect_profiles_seeking",
                to="crush_lu.trait",
            ),
        ),
    ]
