# Generated by Django 6.0.6 on 2026-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0167_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='Monday (ISO) that begins the reported week.', unique=True)),
                ('week_end', models.DateField(help_text='Sunday (inclusive) that ends the reported week.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Full KPI payload for the week (see compute_weekly_snapshot).')),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly KPI snapshot',
                'verbose_name_plural': 'Weekly KPI snapshots',
                'ordering': ['-week_start'],
            },
        ),
    ]
