# Generated by Django 6.0.6 on 2026-06-29 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0168_weeklymetricssnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("harassment", "Harassment or abuse"),
                            ("inappropriate", "Inappropriate content"),
                            ("fake", "Fake or suspicious profile"),
                            ("not_interested", "Just not interested"),
                            ("other", "Other"),
                        ],
                        help_text="Optional — why the member blocked them (private).",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Block",
                "verbose_name_plural": "User Blocks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["blocked"], name="userblock_blocked_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="userblock_unique_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked")), _negated=True
                        ),
                        name="userblock_no_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment or abuse"),
                            ("fake_profile", "Fake or impersonating profile"),
                            ("inappropriate_photos", "Inappropriate photos"),
                            ("spam", "Spam or solicitation"),
                            ("underage", "Appears underage"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Free-text context the reporter added."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spark", "Curiosity Spark"),
                            ("connection", "Event connection"),
                            ("message", "Message"),
                            ("profile", "Profile"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("actioned", "Actioned"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal note on how the report was resolved (audit trail).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff/coach who actioned or dismissed the report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Report",
                "verbose_name_plural": "User Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="userreport_queue_idx"
                    )
                ],
            },
        ),
    ]
