# Generated by Django 6.0.6 on 2026-06-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0169_userblock_userreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreport",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spark", "Curiosity Spark"),
                    ("connection", "Event connection"),
                    ("message", "Message"),
                    ("profile", "Profile"),
                    ("drop", "Daily Drop"),
                ],
                max_length=16,
            ),
        ),
    ]
