# Generated by Django 6.0.6 on 2026-07-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0170_alter_userreport_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crushprofile',
            name='not_on_whatsapp',
            field=models.BooleanField(default=False, help_text='Set when Meta reports this number is not a WhatsApp user (error 131026). We stop attempting WhatsApp and fall back to email.'),
        ),
        migrations.CreateModel(
            name='DailyUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(db_index=True, help_text='Calendar date the user was active (local TZ)')),
                ('was_pwa', models.BooleanField(default=False, help_text='User accessed via the installed PWA at least once this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User active on this day', on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily User Activity',
                'verbose_name_plural': 'Daily User Activities',
                'ordering': ['-activity_date', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date'), name='daily_activity_unique_per_day')],
            },
        ),
    ]
