# Generated by Django 6.0.6 on 2026-07-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0176_seed_connect_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushconnectmembership",
            name="excluded_by_coach",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Coach exclusion — removes the user from every Crush Connect pool",
            ),
        ),
        migrations.AlterField(
            model_name="crushconnectmembership",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when the user completes Crush Connect onboarding. Null = waitlisted/not opted-in.",
                null=True,
            ),
        ),
    ]
