# Generated by Django 6.0.6 on 2026-07-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0178_ios_app_readiness"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="iosappdevice",
            new_name="crush_lu_io_user_id_8e5ab7_idx",
            old_name="crush_lu_io_user_id_a52b0a_idx",
        ),
        migrations.RenameIndex(
            model_name="iosappdevice",
            new_name="crush_lu_io_environ_b20026_idx",
            old_name="crush_lu_io_environ_9b61d5_idx",
        ),
    ]
