# Generated by Django 6.0.6 on 2026-07-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0178_ios_app_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="iosappdevice",
            new_name="crush_lu_io_user_id_8e5ab7_idx",
            old_name="crush_lu_io_user_id_a52b0a_idx",
        ),
        migrations.RenameIndex(
            model_name="iosappdevice",
            new_name="crush_lu_io_environ_b20026_idx",
            old_name="crush_lu_io_environ_9b61d5_idx",
        ),
        migrations.AddField(
            model_name="connectdailydrop",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectdailydrop",
            name="read_target",
            field=models.ForeignKey(
                blank=True,
                help_text="The one Drop card this user chose to read",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
