# Generated by Django 6.0.6 on 2026-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0179_connect_drop_one_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revision", "Needs Revision"),
                    ("recontact_coach", "Recontact Coach Required"),
                    ("expired", "Expired — routed to self-serve verification"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
