# Generated by Django 6.0.7 on 2026-07-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0179_connect_drop_one_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("speed_dating", "Speed Dating"),
                    ("mixer", "Social Mixer"),
                    ("activity", "Activity Meetup"),
                    ("themed", "Themed Event"),
                    ("quiz_night", "Quiz Night"),
                    ("crush_cache", "Crush Cache Hunt"),
                ],
                max_length=20,
            ),
        ),
    ]
