# Generated by Django 6.0.7 on 2026-07-12 08:19

import crush_lu.models.crush_cache
import crush_lu.models.profiles
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0180_alter_meetupevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheHunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_de", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Intro text shown in the lobby before the hunt starts",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Intro text shown in the lobby before the hunt starts",
                        null=True,
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Intro text shown in the lobby before the hunt starts",
                        null=True,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True,
                        help_text="Intro text shown in the lobby before the hunt starts",
                        null=True,
                    ),
                ),
                (
                    "navigation_mode",
                    models.CharField(
                        choices=[
                            ("map", "Map (target pin shown)"),
                            ("compass", "Compass (distance + direction only)"),
                            ("hidden", "Hidden (no navigation help until QR scan)"),
                        ],
                        default="map",
                        help_text="How players are guided to the next station",
                        max_length=10,
                    ),
                ),
                (
                    "team_size_max",
                    models.PositiveIntegerField(
                        default=4, help_text="Maximum members per team"
                    ),
                ),
                (
                    "allow_self_join",
                    models.BooleanField(
                        default=True,
                        help_text="Allow attendees to create/join teams themselves via join code. Disable to have the coach form all teams.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_cache_hunts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cache_hunt",
                        to="crush_lu.meetupevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Hunt",
                "verbose_name_plural": "🗺️ 1. Cache Hunts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CacheStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position in the hunt (1 = first station)"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_de", models.CharField(max_length=200, null=True)),
                ("name_fr", models.CharField(max_length=200, null=True)),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Story/clue text shown when the station becomes the target",
                    ),
                ),
                (
                    "intro_text_en",
                    models.TextField(
                        blank=True,
                        help_text="Story/clue text shown when the station becomes the target",
                        null=True,
                    ),
                ),
                (
                    "intro_text_de",
                    models.TextField(
                        blank=True,
                        help_text="Story/clue text shown when the station becomes the target",
                        null=True,
                    ),
                ),
                (
                    "intro_text_fr",
                    models.TextField(
                        blank=True,
                        help_text="Story/clue text shown when the station becomes the target",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo shown with the station intro",
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to="cache_hunt/stations/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Station latitude (required for GPS unlock modes)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Station longitude (required for GPS unlock modes)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="How close (meters) a team must be to count as arrived",
                    ),
                ),
                (
                    "unlock_mode",
                    models.CharField(
                        choices=[
                            ("none", "None (challenges available immediately)"),
                            ("gps", "GPS (reach the location)"),
                            ("qr", "QR (scan the code on site)"),
                            ("gps_qr", "GPS + QR (reach the location, then scan)"),
                        ],
                        default="gps",
                        max_length=10,
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "completion_message",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team completes this station",
                    ),
                ),
                (
                    "completion_message_en",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team completes this station",
                        null=True,
                    ),
                ),
                (
                    "completion_message_de",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team completes this station",
                        null=True,
                    ),
                ),
                (
                    "completion_message_fr",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team completes this station",
                        null=True,
                    ),
                ),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="crush_lu.cachehunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Station",
                "verbose_name_plural": "📍 2. Cache Stations",
                "ordering": ["order"],
                "unique_together": {("hunt", "order")},
            },
        ),
        migrations.CreateModel(
            name="CacheChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_order", models.PositiveIntegerField(default=1)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("riddle", "Riddle"),
                            ("multiple_choice", "Multiple Choice"),
                            ("open_text", "Open Text"),
                            ("word_scramble", "Word Scramble"),
                            ("photo_task", "Photo Task"),
                        ],
                        default="riddle",
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="The question/prompt/instructions for the challenge"
                    ),
                ),
                (
                    "question_en",
                    models.TextField(
                        help_text="The question/prompt/instructions for the challenge",
                        null=True,
                    ),
                ),
                (
                    "question_de",
                    models.TextField(
                        help_text="The question/prompt/instructions for the challenge",
                        null=True,
                    ),
                ),
                (
                    "question_fr",
                    models.TextField(
                        help_text="The question/prompt/instructions for the challenge",
                        null=True,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON data for options/choices: {"A": "option1", "B": "option2"}',
                    ),
                ),
                (
                    "options_en",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON data for options/choices: {"A": "option1", "B": "option2"}',
                        null=True,
                    ),
                ),
                (
                    "options_de",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON data for options/choices: {"A": "option1", "B": "option2"}',
                        null=True,
                    ),
                ),
                (
                    "options_fr",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON data for options/choices: {"A": "option1", "B": "option2"}',
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        help_text="The correct answer. Leave blank to accept every submission (photo tasks, opinion prompts).",
                    ),
                ),
                (
                    "alternative_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Alternative acceptable answers: ["answer1", "answer2"]',
                    ),
                ),
                (
                    "hint_1",
                    models.TextField(blank=True, help_text="First hint (easiest)"),
                ),
                (
                    "hint_1_en",
                    models.TextField(
                        blank=True, help_text="First hint (easiest)", null=True
                    ),
                ),
                (
                    "hint_1_de",
                    models.TextField(
                        blank=True, help_text="First hint (easiest)", null=True
                    ),
                ),
                (
                    "hint_1_fr",
                    models.TextField(
                        blank=True, help_text="First hint (easiest)", null=True
                    ),
                ),
                (
                    "hint_1_cost",
                    models.IntegerField(
                        default=20, help_text="Points deducted for using hint 1"
                    ),
                ),
                (
                    "hint_2",
                    models.TextField(blank=True, help_text="Second hint (medium)"),
                ),
                (
                    "hint_2_en",
                    models.TextField(
                        blank=True, help_text="Second hint (medium)", null=True
                    ),
                ),
                (
                    "hint_2_de",
                    models.TextField(
                        blank=True, help_text="Second hint (medium)", null=True
                    ),
                ),
                (
                    "hint_2_fr",
                    models.TextField(
                        blank=True, help_text="Second hint (medium)", null=True
                    ),
                ),
                (
                    "hint_2_cost",
                    models.IntegerField(
                        default=50, help_text="Points deducted for using hint 2"
                    ),
                ),
                (
                    "hint_3",
                    models.TextField(
                        blank=True, help_text="Third hint (biggest reveal)"
                    ),
                ),
                (
                    "hint_3_en",
                    models.TextField(
                        blank=True, help_text="Third hint (biggest reveal)", null=True
                    ),
                ),
                (
                    "hint_3_de",
                    models.TextField(
                        blank=True, help_text="Third hint (biggest reveal)", null=True
                    ),
                ),
                (
                    "hint_3_fr",
                    models.TextField(
                        blank=True, help_text="Third hint (biggest reveal)", null=True
                    ),
                ),
                (
                    "hint_3_cost",
                    models.IntegerField(
                        default=80, help_text="Points deducted for using hint 3"
                    ),
                ),
                (
                    "points_awarded",
                    models.IntegerField(
                        default=100,
                        help_text="Points for correct answer (before hint deductions)",
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team answers correctly",
                    ),
                ),
                (
                    "success_message_en",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team answers correctly",
                        null=True,
                    ),
                ),
                (
                    "success_message_de",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team answers correctly",
                        null=True,
                    ),
                ),
                (
                    "success_message_fr",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the team answers correctly",
                        null=True,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="crush_lu.cachestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Challenge",
                "verbose_name_plural": "🧩 3. Cache Challenges",
                "ordering": ["challenge_order"],
                "unique_together": {("station", "challenge_order")},
            },
        ),
        migrations.CreateModel(
            name="CacheTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "join_code",
                    models.CharField(
                        default=crush_lu.models.crush_cache.generate_join_code,
                        help_text="Short code members use to join this team",
                        max_length=6,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#ef4444", "Red"),
                            ("#f97316", "Orange"),
                            ("#eab308", "Yellow"),
                            ("#22c55e", "Green"),
                            ("#06b6d4", "Cyan"),
                            ("#3b82f6", "Blue"),
                            ("#8b5cf6", "Violet"),
                            ("#ec4899", "Pink"),
                        ],
                        default="#ef4444",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="crush_lu.cachehunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Team",
                "verbose_name_plural": "👥 4. Cache Teams",
                "ordering": ["created_at"],
                "unique_together": {("hunt", "join_code")},
            },
        ),
        migrations.CreateModel(
            name="CacheStationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, help_text="GPS proximity satisfied", null=True
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, help_text="QR code scanned", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="All challenges answered", null=True
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="crush_lu.cachestation",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_attempts",
                        to="crush_lu.cacheteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Station Attempt",
                "verbose_name_plural": "🚩 7. Cache Station Attempts",
                "ordering": ["station__order"],
                "unique_together": {("team", "station")},
            },
        ),
        migrations.CreateModel(
            name="CacheTeamProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("is_finished", models.BooleanField(default=False)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "last_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_accuracy", models.FloatField(blank=True, null=True)),
                ("last_position_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crush_lu.cachestation",
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="crush_lu.cacheteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Team Progress",
                "verbose_name_plural": "📊 6. Cache Team Progress",
            },
        ),
        migrations.CreateModel(
            name="CacheChallengeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_answer", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                (
                    "hints_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hint numbers revealed, e.g. [1, 2]",
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Submitted photo for photo tasks",
                        null=True,
                        storage=crush_lu.models.profiles.get_crush_photo_storage,
                        upload_to="cache_hunt/attempts/",
                    ),
                ),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="crush_lu.cachechallenge",
                    ),
                ),
                (
                    "station_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_attempts",
                        to="crush_lu.cachestationattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Challenge Attempt",
                "verbose_name_plural": "✏️ 8. Cache Challenge Attempts",
                "unique_together": {("station_attempt", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="CacheTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="crush_lu.cachehunt",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cache_memberships",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="crush_lu.cacheteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Team Member",
                "verbose_name_plural": "👥 5. Cache Team Members",
                "unique_together": {("hunt", "registration")},
            },
        ),
    ]
