# Generated by Django 6.0.7 on 2026-07-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0180_profilesubmission_expired_status"),
        ("crush_lu", "0181_cachehunt_cachestation_cachechallenge_cacheteam_and_more"),
    ]

    operations = []
