# Generated by Django 6.0.6 on 2026-07-13 22:46

import secrets

from django.db import migrations, models

# Keep in sync with crush_lu.models.crush_cache.JOIN_CODE_ALPHABET —
# copied here so the migration stays valid if the model constant moves.
CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
CODE_LENGTH = 6


def backfill_manual_codes(apps, schema_editor):
    """Give every existing station a per-hunt-unique manual code before
    the unique constraint lands (multiple blank codes would violate it)."""
    CacheStation = apps.get_model("crush_lu", "CacheStation")
    used_by_hunt = {}
    for station in CacheStation.objects.filter(manual_code="").iterator():
        used = used_by_hunt.setdefault(
            station.hunt_id,
            set(
                CacheStation.objects.filter(hunt_id=station.hunt_id)
                .exclude(manual_code="")
                .values_list("manual_code", flat=True)
            ),
        )
        while True:
            code = "".join(secrets.choice(CODE_ALPHABET) for _ in range(CODE_LENGTH))
            if code not in used:
                break
        used.add(code)
        station.manual_code = code
        station.save(update_fields=["manual_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0182_merge_20260713_0940"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cachestation",
            unique_together={("hunt", "order")},
        ),
        migrations.AddField(
            model_name="cachestation",
            name="manual_code",
            field=models.CharField(
                blank=True,
                help_text="Short code players can type instead of scanning the QR",
                max_length=6,
            ),
        ),
        migrations.RunPython(backfill_manual_codes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="cachestation",
            unique_together={("hunt", "manual_code"), ("hunt", "order")},
        ),
    ]
