# Generated by Django 6.0.7 on 2026-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0183_cachestation_manual_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="lobby_consent_given",
            field=models.BooleanField(
                default=False,
                help_text="Acknowledged clear-photo sharing consent for the Event Lobby",
            ),
        ),
    ]
