# Generated by Django 6.0.7 on 2026-07-17 17:29

import crush_lu.models.event_lobby
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0183_cachestation_manual_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLobbyParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        default=crush_lu.models.event_lobby._new_lobby_handle,
                        editable=False,
                        help_text="Opaque event-scoped participant handle used on all pre-mutual surfaces",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="First eligible lobby time — immutable, orders the roster newest-first",
                    ),
                ),
                (
                    "eligibility_source",
                    models.CharField(
                        choices=[
                            ("checkin", "Eligible at QR check-in"),
                            (
                                "onboarding_completed",
                                "Completed Crush Connect onboarding mid-event",
                            ),
                        ],
                        default="checkin",
                        help_text="Audit: how the member became eligible (§9.1)",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_participations",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "event_registration",
                    models.OneToOneField(
                        help_text="Authoritative attendance link — participation never exists without it",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_participation",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Lobby Participation",
                "verbose_name_plural": "Event Lobby Participations",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-joined_at"], name="eventlobby_roster_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="eventlobby_participation_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventMeetSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mutual_revealed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on both rows of a pair when the reverse signal arrives (audit + idempotent UX)",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_meet_signals",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_signals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_signals_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Meet Signal",
                "verbose_name_plural": "Event Meet Signals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "recipient"], name="eventlobby_signal_rcpt_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "sender", "recipient"),
                        name="eventlobby_signal_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")), _negated=True
                        ),
                        name="eventlobby_signal_no_self",
                    ),
                ],
            },
        ),
    ]
