# Generated by Django 6.0.7 on 2026-07-18 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0184_backfill_tester_premium_memberships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AndroidAppDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_token",
                    models.CharField(
                        help_text="FCM registration token for the native Android app",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable app-generated device identifier",
                        max_length=128,
                    ),
                ),
                (
                    "package_name",
                    models.CharField(default="lu.crush.app", max_length=128),
                ),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("app_build", models.CharField(blank=True, max_length=32)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("system_version", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "notify_new_messages",
                    models.BooleanField(
                        default=True, help_text="Notify about new connection messages"
                    ),
                ),
                (
                    "notify_event_reminders",
                    models.BooleanField(
                        default=True, help_text="Notify about upcoming events"
                    ),
                ),
                (
                    "notify_new_connections",
                    models.BooleanField(
                        default=True, help_text="Notify about new connection requests"
                    ),
                ),
                (
                    "notify_profile_updates",
                    models.BooleanField(
                        default=True, help_text="Notify about profile approval status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("last_push_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this Android app installation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="android_app_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Android App Device",
                "verbose_name_plural": "Android App Devices",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "enabled"],
                        name="crush_lu_an_user_id_0ca759_idx",
                    )
                ],
            },
        ),
    ]
