# Generated by Django 6.0.7 on 2026-07-17 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0184_eventlobbyparticipation_eventmeetsignal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmedEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removal_pending", "Removal requested — hidden"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_from_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal audit provenance — never rendered in the collection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_created",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "user_high",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters_as_high",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_low",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters_as_low",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmed Encounter",
                "verbose_name_plural": "Confirmed Encounters",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_low", "user_high"),
                        name="eventlobby_encounter_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("user_low__lt", models.F("user_high"))),
                        name="eventlobby_encounter_canonical_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventMeetingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_confirmations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_meeting_confirmations",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "other_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_confirmations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Meeting Confirmation",
                "verbose_name_plural": "Event Meeting Confirmations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "other_user"],
                        name="eventlobby_confirm_other_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "confirmer", "other_user"),
                        name="eventlobby_confirmation_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confirmer", models.F("other_user")), _negated=True
                        ),
                        name="eventlobby_confirmation_no_self",
                    ),
                ],
            },
        ),
    ]
