# Generated by Django on 2026-07-18
# Merge migration to resolve conflict between 0185_androidappdevice and 0186_confirmedencounterremovalrequest

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0185_androidappdevice"),
        ("crush_lu", "0186_confirmedencounterremovalrequest"),
    ]

    operations = []
