# Generated by Django 6.0.7 on 2026-07-18 22:06
"""Align the post-event connection window with the Event Lobby recap.

``connection_window_deadline`` is now computed from the event's scheduled END
(it used to count from the start), and the default span becomes 48h — the
same as the lobby recap, so both post-event surfaces close together
(unification decision 2026-07-18).

Rows still carrying the old 24h default are bumped to 48 so already-created
upcoming events align too; deliberate per-event overrides (any other value)
are preserved. Mirrors the 0141 rename's data-migration approach.
"""

from django.db import migrations, models


def bump_default_window(apps, schema_editor):
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    MeetupEvent.objects.filter(connection_window_hours=24).update(
        connection_window_hours=48
    )


def restore_default_window(apps, schema_editor):
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    MeetupEvent.objects.filter(connection_window_hours=48).update(
        connection_window_hours=24
    )


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0187_merge_20260718_0721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="connection_window_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="Hours after the event's scheduled end until post-event connection requests close (default: 48 — the same span as the Event Lobby recap, so both close together). After the window closes, attendees are redirected to the Crush Connect teaser.",
            ),
        ),
        migrations.RunPython(bump_default_window, restore_default_window),
    ]
