# Generated by Django 6.0.7 on 2026-07-21 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0188_connection_window_from_end"),
        ("hub", "0003_whatsappinboundmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used as utm_campaign in tracked links",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text='Enabled channels, e.g. ["email", "push"]',
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_users", "All registered users"),
                            ("all_profiles", "Users who created a profile"),
                            ("approved_profiles", "Users with approved profiles"),
                            ("pending_review", "Users awaiting coach approval"),
                            ("segment", "Specific user segment"),
                        ],
                        default="segment",
                        max_length=20,
                    ),
                ),
                (
                    "segment_key",
                    models.CharField(
                        blank=True,
                        help_text="Segment key from user_segments.py (when audience='segment')",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("all", "All languages"),
                            ("en", "English"),
                            ("de", "German"),
                            ("fr", "French"),
                        ],
                        default="all",
                        max_length=5,
                    ),
                ),
                (
                    "audience_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-channel eligible counts captured at creation time",
                    ),
                ),
                (
                    "whatsapp_template_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "whatsapp_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Template body parameters keyed by placeholder index, e.g. {"1": "Hi {first_name}"}. Supports {first_name}, {last_name} and {email} merge tokens.',
                    ),
                ),
                ("push_title", models.CharField(blank=True, max_length=120)),
                (
                    "push_title_en",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "push_title_de",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "push_title_fr",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("push_body", models.CharField(blank=True, max_length=300)),
                (
                    "push_body_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "push_body_de",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "push_body_fr",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("push_url", models.CharField(blank=True, default="/", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("partial", "Partially sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("dispatch_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="campaign",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_newsletter",
                to="crush_lu.campaign",
            ),
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("push", "Web Push")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="crush_lu.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whatsapp_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_recipients",
                        to="hub.whatsappmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Recipient",
                "verbose_name_plural": "Campaign Recipients",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "scheduled_at"], name="crush_lu_ca_status_80818b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(
                fields=["campaign", "channel", "status"],
                name="crush_lu_ca_campaig_7d87ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignrecipient",
            unique_together={("campaign", "channel", "user")},
        ),
    ]
