# Generated by Django 6.0.7 on 2026-07-21 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0189_campaign_newsletter_campaign_campaignrecipient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("original_url", models.CharField(max_length=1000)),
                (
                    "tracked_url",
                    models.CharField(
                        help_text="original_url with utm_source/medium/campaign merged in",
                        max_length=1200,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="crush_lu.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Link",
                "verbose_name_plural": "Campaign Links",
                "unique_together": {("campaign", "channel", "original_url")},
            },
        ),
        migrations.CreateModel(
            name="CampaignClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_clicks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="crush_lu.campaignlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Click",
                "verbose_name_plural": "Campaign Clicks",
                "indexes": [
                    models.Index(
                        fields=["link", "clicked_at"],
                        name="crush_lu_ca_link_id_748723_idx",
                    )
                ],
            },
        ),
    ]
