# Generated by Django 6.0.7 on 2026-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0190_campaignlink_campaignclick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
