# Generated by Django 6.0.7 on 2026-07-21 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0191_alter_phoneotp_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=120,
                validators=[django.core.validators.MaxValueValidator(10080)],
            ),
        ),
    ]
