# Generated by Django 6.0.7 on 2026-07-21 23:11

from django.conf import settings
from django.db import migrations, models

# Keep in sync with MeetupEvent.MAX_DURATION_MINUTES (migrations freeze values).
DURATION_CEILING_MINUTES = 10080  # 7 days


def clamp_durations_over_ceiling(apps, schema_editor):
    """Remediate pre-existing rows above the ceiling.

    A validator does not run on bulk updates or plain save(), so legacy or
    programmatically-created events may exceed the ceiling. Clamp them first so
    the CheckConstraint can be added without failing on existing data.
    """
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    MeetupEvent.objects.filter(
        duration_minutes__gt=DURATION_CEILING_MINUTES
    ).update(duration_minutes=DURATION_CEILING_MINUTES)


def noop(apps, schema_editor):
    """Reverse is a no-op — the original over-ceiling values are not recoverable."""


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0192_alter_meetupevent_duration_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clamp_durations_over_ceiling, noop),
        migrations.AddConstraint(
            model_name="meetupevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__lte", 10080)),
                name="crush_lu_meetupevent_duration_within_ceiling",
            ),
        ),
    ]
