# Generated by Django 6.0.7 on 2026-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0194_rename_connectinterest_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="ask_me_about",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Up to 3 interest ids to highlight as conversation starters",
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="event_vibe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dance_floor", "First one on the dance floor"),
                    ("quiet_corner", "Quiet corner conversations"),
                    ("meet_everyone", "Here to meet everyone"),
                    ("dragged_along", "Dragged along by friends"),
                    ("at_the_bar", "I'll be at the bar — come say hi"),
                ],
                default="",
                help_text="Your event vibe — one chip shown on event surfaces",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="interests_new",
            field=models.ManyToManyField(
                blank=True,
                help_text="Curated event interests (max 8) — replaces free-text interests",
                related_name="event_profiles",
                to="crush_lu.interest",
            ),
        ),
        migrations.AlterField(
            model_name="crushprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED (Event Identity redesign): legacy free-text bio, coach-visible only",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="crushprofile",
            name="interests",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED (Event Identity redesign): legacy free-text interests, coach-visible only",
                max_length=300,
            ),
        ),
    ]
