# Generated by Django 6.0.7 on 2026-07-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0196_seed_interest_additions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interest",
            options={
                "ordering": ["category", "sort_order", "label"],
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
            },
        ),
    ]
