# Generated by Django 6.0.7 on 2026-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_lu', '0198_rename_interest_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconnection',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('completed', 'Call completed'), ('no_answer', 'No answer'), ('rescheduled', 'Rescheduled'), ('unreachable', 'Unreachable')], help_text='Outcome of the coach call', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventconnection',
            name='coach_call_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the coach call with the requester was completed', null=True),
        ),
        migrations.AddField(
            model_name='eventconnection',
            name='coach_call_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the coach call with the requester is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='eventconnection',
            name='flow',
            field=models.CharField(choices=[('legacy', 'Legacy connection request'), ('crush', 'My Crush! coach lead')], db_index=True, default='legacy', help_text="Post-event flow this row belongs to. Historical rows stay 'legacy' (no backfill); only explicit 'My Crush!' declarations become crush coach leads.", max_length=10),
        ),
        migrations.AddField(
            model_name='eventconnection',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Idempotency record for the 24h untouched-lead reminder — repeated timer delivery must never double-remind.', null=True),
        ),
    ]
