# Generated by Django 6.0.7 on 2026-07-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0199_eventconnection_call_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_coach",
            field=models.ForeignKey(
                blank=True,
                help_text="The recipient's own coach, when different from the routed coach — owns the recipient-side outreach task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crush_cocoach_leads",
                to="crush_lu.crushcoach",
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_outreach_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the co-coach recorded reaching out to the recipient",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_response",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consented", "Recipient consented to the introduction"),
                    ("declined", "Recipient declined the introduction"),
                ],
                help_text="Recipient's answer, as recorded by their own coach",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the recipient's answer was recorded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="system_actions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Append-only audit trail of narrow coach writes (actor + timestamp), so the co-coach path is reconstructable.",
            ),
        ),
    ]
