# Generated by Django 6.0.7 on 2026-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0200_my_crush_phase_d_cocoach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="profile_requirement",
            field=models.CharField(
                choices=[
                    (
                        "completed",
                        "Verified, or phone-verified and awaiting verification (entry event)",
                    ),
                    ("approved", "Verified members only"),
                    ("coach_assigned", "Has an assigned coach (NOT a Premium check)"),
                    (
                        "unverified",
                        "Not-yet-verified profiles only (excludes rejected)",
                    ),
                    (
                        "profile_exists",
                        "Any profile, verified or not (excludes rejected)",
                    ),
                    ("none", "No profile required — any logged-in account"),
                ],
                default="completed",
                help_text="Controls what level of profile is needed to register for this event",
                max_length=20,
            ),
        ),
    ]
