# Generated by Django 6.0.7 on 2026-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0201_profile_requirement_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="profile_requirement",
            field=models.CharField(
                choices=[
                    ("none", "All logged-in people"),
                    ("completed", "Participation-ready Crush profile"),
                    ("approved", "Verified members only"),
                    ("profile_exists", "Any Crush profile (except rejected)"),
                    ("unverified", "Not-yet-verified profiles only (except rejected)"),
                    ("coach_assigned", "Members with an assigned coach (not Premium)"),
                ],
                default="completed",
                help_text="Controls which audience can register for this event.",
                max_length=20,
            ),
        ),
    ]
