# Generated by Django 6.0.7 on 2026-07-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0202_alter_meetupevent_profile_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_granted_coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Coach this check-in granted the member as their permanent coach (empty when the member already had one)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crush_lu.crushcoach",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_granted_coach_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The exact CrushProfile.assigned_coach_at this check-in wrote. Undo clears the coach only while the profile still holds this pair, so any later write — premium confirmation, admin reassignment — survives the undo.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_prior_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Status this registration held immediately before check-in",
                max_length=20,
            ),
        ),
    ]
