# Generated by Django 6.0.7 on 2026-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0203_checkin_undo_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp the day-before reminder email was sent",
                null=True,
            ),
        ),
    ]
