# Generated by Django 6.0.7 on 2026-07-31 22:14

import crush_lu.storage
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0204_event_reminder_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded image/video/audio (public Azure Blob). Recommended for images and short clips — use an external embed URL for long video/audio.",
                null=True,
                storage=crush_lu.storage.get_crush_media_storage,
                upload_to=functools.partial(
                    crush_lu.storage._domain_upload_path, "", "quiz"
                ),
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="media_kind",
            field=models.CharField(
                choices=[
                    ("none", "No media"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                ],
                default="none",
                help_text="Optional media (image/video/audio) shown alongside the prompt.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="External embed URL (YouTube / Vimeo / Spotify / SoundCloud). Watch URLs are normalized to their embed form on save.",
                max_length=500,
            ),
        ),
    ]
