# Generated by Django 6.0.7 on 2026-07-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0205_quizquestion_media_file_quizquestion_media_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="media_description",
            field=models.CharField(
                blank=True,
                help_text="Accessible description of the media (alt text for images / label for audio). Used by screen readers so the stimulus isn't hidden from participants who need it.",
                max_length=300,
            ),
        ),
    ]
