# Generated by Django 6.0.7 on 2026-08-02 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0211_backfill_event_ticket_auth_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushconnectwaitlist",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who confirmed the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_crush_connect_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="crushconnectwaitlist",
            name="payment_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Monthly payment confirmed by staff (manual, no processor)",
            ),
        ),
        migrations.AlterField(
            model_name="crushconnectwaitlist",
            name="selected_as_tester",
            field=models.BooleanField(
                default=False,
                help_text="Hand-picked beta tester: may buy Premium and receive Drops",
            ),
        ),
    ]
