# Generated by Django 6.0.7 on 2026-08-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0212_alter_crushconnectwaitlist_confirmed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="language_explicitly_set",
            field=models.BooleanField(
                default=False,
                help_text="True when the member picked their language themselves, rather than it being inferred from their browser or LuxID locale.",
            ),
        ),
    ]
