# Generated by Django 6.0.7 on 2026-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0213_explicit_language_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="failure_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this payment did not complete, in words. The provider's own wording where it gives one.",
            ),
        ),
    ]
