# Generated by Django 6.0.7 on 2026-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0214_paymenttransaction_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="is_community_supporter",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether user has donated to support Crush.lu",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("event_registration", "Event Registration"),
                    ("premium_membership", "Premium Membership"),
                    ("donation", "Donation / Support"),
                ],
                max_length=30,
            ),
        ),
    ]
