# Generated by Django 6.0.7 on 2026-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0215_crushprofile_is_community_supporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="outlook_photo_key",
            field=models.CharField(
                blank=True,
                help_text="photo_1 storage key last uploaded to the Outlook contact, so unchanged photos are not re-uploaded on every sync",
                max_length=255,
            ),
        ),
    ]
