# Generated by Django 6.0.7 on 2026-08-07 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0216_outlook_photo_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="EchoExperienceSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Server-assigned echo.lu experience id. Empty until the first successful create. This is the only handle we have on the listing — never clear it while the listing still exists.",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("withdrawn", "Withdrawn"),
                            ("suppressed", "Suppressed"),
                            ("orphaned", "Orphaned — accepted without an id"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of the last payload echo.lu accepted. A resync whose payload hashes the same is skipped, so the hourly sweep and the save-signal do not spend a request per event per pass.",
                        max_length=64,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When echo.lu last accepted a write for this event.",
                        null=True,
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a sync was last attempted, successful or not.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Failure detail from the last attempt, cleared on success. echo.lu returns field-level validation errors here — most often an unknown category/audience slug.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        help_text="The Crush.lu event this echo.lu listing mirrors.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echo_sync",
                        to="crush_lu.meetupevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "echo.lu experience sync",
                "verbose_name_plural": "echo.lu experience syncs",
                "ordering": ["-updated_at"],
            },
        ),
    ]
