# Generated by Django 6.0.7 on 2026-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0217_echo_lu_experience_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="echoexperiencesync",
            name="removal_requested",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Somebody asked for this listing to come down and echo.lu has not confirmed it yet. Survives a failed take-down on purpose: the event itself still says 'publish me', so without this a failed removal would look like an ordinary failure and the next sweep would republish the listing instead of retrying the removal.",
            ),
        ),
    ]
