# Generated by Django 6.0.7 on 2026-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0218_echo_lu_removal_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echoexperiencesync",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                    ("withdrawn", "Withdrawn"),
                    ("cancelled", "Cancelled — notice still public"),
                    ("suppressed", "Suppressed"),
                    ("orphaned", "Orphaned — may hold an untracked listing"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
