# Generated by Django 6.0.7 on 2026-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0219_echo_lu_cancelled_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EchoVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Normalised venue string (see services.echo_lu.venue_key) — lowercased name plus postcode, so casing and spacing changes do not register a second venue for the same place.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "venue_id",
                    models.CharField(
                        db_index=True,
                        help_text="Server-assigned echo.lu venue id.",
                        max_length=128,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The venue name as echo.lu holds it, for the admin.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by_us",
                    models.BooleanField(
                        default=False,
                        help_text="True when we registered this venue rather than matching one that already existed. Worth knowing before deleting anything: the registry is shared with every other organiser.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "echo.lu venue",
                "verbose_name_plural": "echo.lu venues",
                "ordering": ["title", "key"],
            },
        ),
    ]
