# Generated by Django 6.0.7 on 2026-08-10 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0220_echo_lu_venue_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="address_number",
            field=models.CharField(
                blank=True,
                help_text="House number exactly as written: '7', '12A', '12-14'. Leave blank if the venue has no number.",
                max_length=20,
                verbose_name="House number",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="address_postcode",
            field=models.CharField(
                blank=True,
                help_text="Four digits. Type 'L-2229' or '2229' - the 'L-' is added on display.",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Luxembourg postcodes are exactly four digits.",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="Postcode",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="address_street",
            field=models.CharField(
                blank=True,
                help_text="Street name only, without the house number (e.g. 'rue du Nord').",
                max_length=200,
                verbose_name="Street",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="address_town",
            field=models.CharField(
                blank=True,
                help_text="The town the venue is in (e.g. 'Luxembourg', 'Differdange'). This is NOT the canton - the canton is its own field.",
                max_length=100,
                verbose_name="Town",
            ),
        ),
        migrations.AlterField(
            model_name="meetupevent",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Superseded by the street/number/postcode/town fields above. Kept so events created before the split keep rendering. Do not type new addresses here.",
                verbose_name="Legacy address (free text)",
            ),
        ),
    ]
