# Generated by Django 6.0.7 on 2026-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0222_normalize_event_canton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="canton",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Capellen", "Capellen"),
                    ("Clervaux", "Clervaux"),
                    ("Diekirch", "Diekirch"),
                    ("Echternach", "Echternach"),
                    ("Esch-sur-Alzette", "Esch-sur-Alzette"),
                    ("Grevenmacher", "Grevenmacher"),
                    ("Luxembourg", "Luxembourg"),
                    ("Mersch", "Mersch"),
                    ("Redange", "Redange"),
                    ("Remich", "Remich"),
                    ("Vianden", "Vianden"),
                    ("Wiltz", "Wiltz"),
                ],
                help_text="The region anonymous visitors see instead of the exact address. This is the canton, not the town - the town has its own field.",
                max_length=200,
            ),
        ),
    ]
