# Generated by Django 6.0.7 on 2026-08-13 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0224_normalize_event_canton_again"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[("sumup", "SumUp"), ("credit", "Crush Credit")],
                default="sumup",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CrushCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        help_text="Face value issued, in cents. Never edited after issue."
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Computed on first save as issued_at + 6 months, then stored.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("member_cancellation", "Member cancelled (>48h)"),
                            ("seat_resold", "Late cancellation, seat resold"),
                            ("event_cancelled", "Crush.lu cancelled the event"),
                            ("goodwill", "Goodwill"),
                            ("referral", "Referral"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("consumed", "Fully redeemed"),
                            ("expired", "Expired"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "cash_refund_eligible",
                    models.BooleanField(
                        default=False,
                        help_text="This member may ask for their money back instead. Set only when Crush.lu cancelled the event — Luxembourg consumer law entitles them to a cash refund there and a voucher is not a substitute. Refunds themselves are still made by hand in the SumUp dashboard.",
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "source_payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The captured payment this credit gives back, where known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_credits",
                        to="crush_lu.paymenttransaction",
                    ),
                ),
                (
                    "source_registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The seat this credit was issued against, where there was one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_credits",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The member who holds this credit. Non-transferable.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crush_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crush Credit",
                "verbose_name_plural": "Crush Credits",
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CreditRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_redemptions",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="crush_lu.crushcredit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Redemption",
                "verbose_name_plural": "Credit Redemptions",
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="crushcredit",
            index=models.Index(
                fields=["user", "status", "expires_at"], name="crushcredit_balance_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crushcredit",
            index=models.Index(
                fields=["cash_refund_eligible", "issued_at"],
                name="crushcredit_refundq_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reason", "seat_resold")),
                fields=("source_registration", "reason"),
                name="one_resale_credit_per_registration",
            ),
        ),
        migrations.AddIndex(
            model_name="creditredemption",
            index=models.Index(
                fields=["event_registration"], name="creditredeem_reg_idx"
            ),
        ),
    ]
