# Generated by Django 6.0.7 on 2026-08-13 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0225_crush_credit_ledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crushcredit",
            name="one_resale_credit_per_registration",
        ),
        migrations.AlterField(
            model_name="creditredemption",
            name="event_registration",
            field=models.ForeignKey(
                blank=True,
                help_text="The seat this was spent on, while that seat still exists.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_redemptions",
                to="crush_lu.eventregistration",
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reason", "seat_resold")),
                fields=("source_registration", "source_payment", "reason"),
                name="one_resale_credit_per_payment",
            ),
        ),
    ]
