# Generated by Django 6.0.7 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0226_crush_credit_ledger_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crushcredit",
            name="one_resale_credit_per_payment",
        ),
        migrations.AddField(
            model_name="crushcredit",
            name="restored_from_credit",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The original funding tranche restored by this issue. Its "
                    "expiry is preserved so booking and cancelling cannot extend credit."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restoration_credits",
                to="crush_lu.crushcredit",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="resale_source_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resale_replacements",
                to="crush_lu.paymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="resale_source_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resale_replacements",
                to="crush_lu.eventregistration",
            ),
        ),
        migrations.AlterField(
            model_name="crushcredit",
            name="user",
            field=models.ForeignKey(
                db_index=True,
                help_text="The member who holds this credit. Non-transferable.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crush_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="crushcredit",
            options={
                "ordering": ["-issued_at", "-id"],
                "permissions": [("void_crushcredit", "Can void Crush Credit")],
                "verbose_name": "Crush Credit",
                "verbose_name_plural": "Crush Credits",
            },
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "seat_resold"),
                    ("restored_from_credit__isnull", True),
                ),
                fields=("source_registration", "source_payment", "reason"),
                name="one_resale_credit_per_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "seat_resold"),
                    ("restored_from_credit__isnull", False),
                ),
                fields=(
                    "source_registration",
                    "source_payment",
                    "reason",
                    "restored_from_credit",
                ),
                name="one_resale_restore_per_tranche",
            ),
        ),
    ]
