# Generated by Django 6.0.7 on 2026-08-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_payment_lifecycle(apps, schema_editor):
    """Preserve historical cash revenue and pending resale beneficiaries."""
    PaymentTransaction = apps.get_model("crush_lu", "PaymentTransaction")
    EventRegistration = apps.get_model("crush_lu", "EventRegistration")

    # ``updated_at`` is mutable: merely reconciling an old SumUp checkout moves
    # it to today and would make the weekly KPI count that historical payment
    # again. ``created_at`` is the immutable timestamp available on every
    # historical transaction and keeps it in its original payment cycle.
    PaymentTransaction.objects.filter(status="paid", paid_at__isnull=True).update(
        paid_at=models.F("created_at")
    )

    pending_claims = (
        EventRegistration.objects.filter(resale_beneficiary__isnull=True)
        .filter(
            models.Q(resale_source_registration__isnull=False)
            | models.Q(resale_source_payment__isnull=False)
        )
        .select_related("resale_source_registration", "resale_source_payment")
    )
    for registration in pending_claims.iterator(chunk_size=500):
        beneficiary_id = None
        if registration.resale_source_registration_id:
            beneficiary_id = registration.resale_source_registration.user_id
        if beneficiary_id is None and registration.resale_source_payment_id:
            beneficiary_id = registration.resale_source_payment.user_id
        if beneficiary_id:
            EventRegistration.objects.filter(pk=registration.pk).update(
                resale_beneficiary_id=beneficiary_id
            )

    # Before MANUAL existed, staff confirmed cash/bank payments only on the
    # registration. Materialise those immutable cash records so weekly and
    # lifetime revenue do not depend on a seat flag later cleared by credit.
    registrations = (
        EventRegistration.objects.filter(
            payment_confirmed=True,
            event__registration_fee__gt=0,
        )
        .exclude(payment_transactions__status="paid")
        .select_related("event")
        .order_by("pk")
    )
    rows = []
    for registration in registrations.iterator(chunk_size=500):
        rows.append(
            PaymentTransaction(
                transaction_reference=f"CRUSH-MANUAL-BACKFILL-{registration.pk}",
                provider="manual",
                amount=registration.event.registration_fee,
                currency="EUR",
                status="paid",
                purpose="event_registration",
                user_id=registration.user_id,
                event_registration_id=registration.pk,
                paid_at=(
                    registration.payment_date
                    or registration.updated_at
                    or registration.registered_at
                ),
                raw_response={"method": "historical_manual_backfill"},
            )
        )
    PaymentTransaction.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0227_credit_resale_settlement_and_retention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crushcredit",
            name="one_resale_credit_per_payment",
        ),
        migrations.RemoveConstraint(
            model_name="crushcredit",
            name="one_resale_restore_per_tranche",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="organiser_cancellation_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the organiser-cancellation remedy email was delivered. Used to resume bounded cancellation batches safely.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="resale_beneficiary",
            field=models.ForeignKey(
                blank=True,
                help_text="The member owed the resale share. Kept separately so account merges or source-registration deletion cannot erase the obligation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_resale_replacements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this transaction first became paid. Never moved later.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("sumup", "SumUp"),
                    ("credit", "Crush Credit"),
                    ("manual", "Cash / bank transfer"),
                ],
                default="sumup",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_payment_lifecycle, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "seat_resold"),
                    ("restored_from_credit__isnull", True),
                    ("source_payment__isnull", False),
                ),
                fields=("source_payment", "reason"),
                name="one_resale_credit_per_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "seat_resold"),
                    ("restored_from_credit__isnull", False),
                    ("source_payment__isnull", False),
                ),
                fields=("source_payment", "reason", "restored_from_credit"),
                name="one_resale_restore_per_tranche",
            ),
        ),
    ]
