# Generated by Django 6.0.7 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_events(apps, schema_editor):
    """Copy event attribution before registrations can later disappear."""
    PaymentTransaction = apps.get_model("crush_lu", "PaymentTransaction")
    payments = (
        PaymentTransaction.objects.filter(
            event__isnull=True,
            event_registration__isnull=False,
            status__in=("paid", "refunded"),
        )
        .select_related("event_registration")
        .order_by("pk")
    )
    batch = []
    for payment in payments.iterator(chunk_size=500):
        payment.event_id = payment.event_registration.event_id
        batch.append(payment)
        if len(batch) == 500:
            PaymentTransaction.objects.bulk_update(batch, ["event"], batch_size=500)
            batch = []
    if batch:
        PaymentTransaction.objects.bulk_update(batch, ["event"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0228_credit_payment_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Immutable event attribution, retained if the registration "
                    "is deleted."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transactions",
                to="crush_lu.meetupevent",
            ),
        ),
        migrations.RunPython(backfill_payment_events, migrations.RunPython.noop),
    ]
