# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models


def backfill_cancelled_at(apps, schema_editor):
    EventRegistration = apps.get_model("crush_lu", "EventRegistration")
    EventRegistration.objects.filter(
        status="cancelled",
        cancelled_at__isnull=True,
    ).update(cancelled_at=models.F("updated_at"))


def release_abandoned_checkout_events(apps, schema_editor):
    PaymentTransaction = apps.get_model("crush_lu", "PaymentTransaction")
    PaymentTransaction.objects.exclude(status__in=("paid", "refunded")).update(
        event=None
    )


class Migration(migrations.Migration):

    atomic = False  # adding db_index cancelled_at alongside RunPython on PostgreSQL

    dependencies = [
        ("crush_lu", "0229_payment_transaction_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "When this registration entered cancelled status. Used to "
                    "apply the cancellation policy at the member's actual "
                    "cancellation time."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(backfill_cancelled_at, migrations.RunPython.noop),
        migrations.RunPython(
            release_abandoned_checkout_events,
            migrations.RunPython.noop,
        ),
    ]
