# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models


def backfill_cancellation_cycles(apps, schema_editor):
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    MeetupEvent.objects.filter(
        is_cancelled=True,
        organiser_cancellation_started_at__isnull=True,
    ).update(organiser_cancellation_started_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0230_event_registration_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="organiser_cancellation_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Start of the current organiser-cancellation cycle. Used to "
                    "keep remedy emails from reusing credit issued before an "
                    "event restore."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_cancellation_cycles,
            migrations.RunPython.noop,
        ),
    ]
