# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models
from django.db.models import OuterRef, Q, Subquery
from django.db.models.functions import Coalesce


def backfill_cancellation_cycles(apps, schema_editor):
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    CrushCredit = apps.get_model("crush_lu", "CrushCredit")
    earliest_remedy = (
        CrushCredit.objects.filter(reason="event_cancelled")
        .filter(
            Q(source_registration__event_id=OuterRef("pk"))
            | Q(source_payment__event_id=OuterRef("pk"))
        )
        .order_by("issued_at", "pk")
        .values("issued_at")[:1]
    )
    MeetupEvent.objects.filter(
        is_cancelled=True,
        organiser_cancellation_started_at__isnull=True,
    ).update(
        # The legacy cancellation action used QuerySet.update(is_cancelled=True),
        # so auto_now did not stamp updated_at at cancellation time. Prefer the
        # first durable remedy in that cycle; only credit-less events fall back
        # to the best timestamp available on the event row.
        organiser_cancellation_started_at=Coalesce(
            Subquery(earliest_remedy),
            models.F("updated_at"),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0230_event_registration_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="organiser_cancellation_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Start of the current organiser-cancellation cycle. Used to "
                    "keep remedy emails from reusing credit issued before an "
                    "event restore."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_cancellation_cycles,
            migrations.RunPython.noop,
        ),
    ]
