# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crush_lu", "0231_meetupevent_cancellation_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="photo_verification_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text=(
                    "Exact photo_1 storage key last verified in person. A different "
                    "current key invalidates the verified-photo badge."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_verified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the current primary photo was verified in person",
                null=True,
            ),
        ),
    ]
