# Generated by Django 6.0.7 on 2026-08-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0231_meetupevent_cancellation_cycle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crushcredit",
            options={
                "ordering": ["-issued_at", "-id"],
                "permissions": [
                    ("issue_crushcredit", "Can issue Crush Credit (goodwill)"),
                    ("void_crushcredit", "Can void Crush Credit"),
                ],
                "verbose_name": "Crush Credit",
                "verbose_name_plural": "Crush Credits",
            },
        ),
    ]
