# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crush_lu", "0232_alter_crushcredit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="photo_verification_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text=(
                    "Exact photo_1 storage key last verified in person. A different "
                    "current key invalidates the verified-photo badge."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_verified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the current primary photo was verified in person",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_attested_photo_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text=(
                    "Photo key verified during this check-in. Cleared on undo to revoke "
                    "the in-person photo trust badge."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_attested_photo_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the photo was attested during this check-in.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="checkin_auto_verified",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="True if this check-in auto-verified a previously pending profile.",
            ),
        ),
    ]
