# Generated by Django 6.0.7 on 2026-08-16 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0232_alter_crushcredit_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(
                blank=True,
                help_text="Optional once-only claim token. When set, the database refuses a second row with the same (user, notification_type, dedupe_key), which is how concurrent senders agree on who delivers.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key__isnull", False)),
                fields=("user", "notification_type", "dedupe_key"),
                name="crush_notif_unique_dedupe_key",
            ),
        ),
    ]
