# Generated by Django 6.0.7 on 2026-08-18 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0234_crushprofile_photo_verification"),
        ("hub", "0009_paymentin_payroll_refund_paymentout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectCycleCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveSmallIntegerField(
                        help_text="Cycle day on which this card was generated (1-7)"
                    ),
                ),
                (
                    "card_index",
                    models.PositiveSmallIntegerField(
                        help_text="Index of the card for the day (1, 2, or 3)"
                    ),
                ),
                ("generated_date", models.DateField(db_index=True)),
                (
                    "answers_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Private responses and compatibility signals recorded for this card",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the user answered the card questions",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False,
                        help_text="True if midnight passed without completion",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_cards_as_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Cycle Card",
                "verbose_name_plural": "Connect Cycle Cards",
                "ordering": ["day_number", "card_index"],
            },
        ),
        migrations.CreateModel(
            name="ConnectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=50)),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_connect_reports",
                        to="crush_lu.crushcoach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Report",
                "verbose_name_plural": "Connect Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectTemporaryChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            (
                                "meeting_confirmed",
                                "Meeting Confirmed (3-day countdown)",
                            ),
                            ("closed", "Closed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Default 7-day expiration if no meeting is scheduled"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="True when 24h gentle reminder was sent",
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inactivity_timeout", "Inactivity Timeout (7 days)"),
                            (
                                "post_meeting_retention",
                                "Post-meeting retention finished",
                            ),
                            ("member_declined", "Member closed conversation"),
                            ("blocked", "Blocked by participant"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "participant_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_chats_as_p1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_chats_as_p2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Temporary Chat",
                "verbose_name_plural": "Connect Temporary Chats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectCoffeeDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_venue_name", models.CharField(blank=True, max_length=255)),
                ("custom_venue_address", models.CharField(blank=True, max_length=255)),
                ("proposed_date", models.DateField()),
                (
                    "proposed_time_slot",
                    models.CharField(
                        blank=True, help_text="e.g. 18:30 or Evening", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted / Scheduled"),
                            ("rescheduled", "Rescheduled"),
                            ("confirmed_by_both", "Confirmed (Both attended)"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "participant_1_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "participant_2_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "meeting_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when both members confirmed attending",
                        null=True,
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_connect_dates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Curated partner café/bar location from the Hub",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connect_coffee_dates",
                        to="hub.location",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_date",
                        to="crush_lu.connecttemporarychat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Coffee Date",
                "verbose_name_plural": "Connect Coffee Dates",
                "ordering": ["-proposed_date"],
            },
        ),
        migrations.CreateModel(
            name="ConnectChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1000)),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connect_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crush_lu.connecttemporarychat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Chat Message",
                "verbose_name_plural": "Connect Chat Messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectWeeklyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (Awaiting recipient response)"),
                            ("accepted", "Accepted (Chat opened)"),
                            ("declined", "Declined"),
                            ("expired", "Expired (24h timeout)"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="Ich möchte dich kennenlernen.",
                        help_text="Standard connection invitation copy",
                        max_length=255,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="24 hours from sent_at for recipient to respond"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_connect_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connect_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_requests",
                        to="crush_lu.connectcyclecard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Weekly Request",
                "verbose_name_plural": "Connect Weekly Requests",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="connecttemporarychat",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="crush_lu.connectweeklyrequest",
            ),
        ),
        migrations.CreateModel(
            name="ConnectWeekSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "current_day_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Current day in the 7-day cycle (1 to 7)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active (In 7-day cycle)"),
                            ("review_open", "Review Open (24h review window)"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_review_open",
                    models.BooleanField(
                        default=False,
                        help_text="True during the 24h review window on Day 8",
                    ),
                ),
                ("review_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="24 hours after review opened", null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compatibility_highlight_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Platform-generated compatibility highlight for this cycle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlighted_in_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_week_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Week Session",
                "verbose_name_plural": "Connect Week Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="connectweeklyrequest",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_requests",
                to="crush_lu.connectweeksession",
            ),
        ),
        migrations.AddField(
            model_name="connectcyclecard",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="crush_lu.connectweeksession",
            ),
        ),
        migrations.CreateModel(
            name="ConnectPairExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cycle_completed", "Completed Connect cycle"),
                            ("request_declined", "Connection request declined"),
                            ("request_expired", "Connection request expired"),
                            ("member_blocked", "Blocked by member"),
                            ("coach_excluded", "Excluded by coach"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_exclusions_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_exclusions_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Pair Exclusion",
                "verbose_name_plural": "Connect Pair Exclusions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_a", "user_b"),
                        name="unique_connect_pair_exclusion",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="connectcyclecard",
            constraint=models.UniqueConstraint(
                fields=("session", "day_number", "card_index"),
                name="unique_card_per_day_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectcyclecard",
            constraint=models.UniqueConstraint(
                fields=("session", "target_user"), name="unique_target_per_session"
            ),
        ),
    ]
