# Generated by Django 6.0.7 on 2026-08-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crush_lu",
            "0235_connectcyclecard_connectreport_connecttemporarychat_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crushcredit",
            options={
                "ordering": ["-issued_at", "-id"],
                "permissions": [
                    ("issue_crushcredit", "Can issue Crush Credit (goodwill)"),
                    ("void_crushcredit", "Can void Crush Credit"),
                    ("refund_crushcredit", "Can refund Crush Credit via SumUp"),
                ],
                "verbose_name": "Crush Credit",
                "verbose_name_plural": "Crush Credits",
            },
        ),
        migrations.CreateModel(
            name="CrushCreditExpiryReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reminder was sent"
                    ),
                ),
                (
                    "credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_reminder",
                        to="crush_lu.crushcredit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crush Credit Expiry Reminder",
                "verbose_name_plural": "Crush Credit Expiry Reminders",
            },
        ),
    ]
