# Generated by Django 6.0.7 on 2026-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0236_alter_crushcredit_options_crushcreditexpiryreminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="reserved_premium_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seats within the total capacity held back for Premium members (an active paid membership — an assigned coach alone does not count). General members fill only (max participants − reserved). 0 = no reservation.",
                verbose_name="Reserved premium seats",
            ),
        ),
    ]
