# Generated by Django 6.0.7 on 2026-08-21 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0237_alter_meetupevent_reserved_premium_seats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="beta_invite_wave",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Which send_connect_beta_invites wave delivered the invite (1 = Connect Week, 2 = In the Mix, 3 = verification reminder)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crushconnectwaitlist",
            name="beta_invited_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the Connect beta launch invite was emailed (blank = never)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ConnectCycleFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good week"),
                            ("mixed", "Mixed"),
                            ("poor", "Not for me"),
                        ],
                        db_index=True,
                        help_text="Overall verdict on the 7-day cycle (blank when dismissed)",
                        max_length=10,
                    ),
                ),
                (
                    "match_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good fit"),
                            ("mixed", "Mixed"),
                            ("poor", "Not really"),
                        ],
                        help_text="Whether the three daily cards felt like a fit",
                        max_length=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text note from the member",
                        max_length=1000,
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="Member closed the prompt without answering; never ask again",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="crush_lu.connectweeksession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_cycle_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect Cycle Feedback",
                "verbose_name_plural": "Connect Cycle Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
