# Generated by Django 6.0.7 on 2026-08-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0238_crushconnectwaitlist_beta_invite_wave_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectdailydrop",
            name="connect_drop_unique_per_day",
        ),
        migrations.RemoveIndex(
            model_name="connectquestionanswer",
            name="connect_answer_owner_q_idx",
        ),
        migrations.RemoveConstraint(
            model_name="connectquestionanswer",
            name="connect_answer_unique",
        ),
        migrations.RemoveConstraint(
            model_name="connectquestionanswer",
            name="connect_answer_no_self",
        ),
        migrations.RemoveConstraint(
            model_name="curiosityspark",
            name="connect_spark_unique_pair",
        ),
        migrations.RemoveConstraint(
            model_name="curiosityspark",
            name="connect_spark_no_self",
        ),
        migrations.AlterField(
            model_name="crushconnectwaitlist",
            name="selected_as_tester",
            field=models.BooleanField(
                default=False,
                help_text="Hand-picked beta tester: may enter Connect Week and buy Premium",
            ),
        ),
        migrations.AlterField(
            model_name="sparkprompt",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive prompts stop being offered during onboarding",
            ),
        ),
        migrations.AlterModelOptions(
            name="sparkprompt",
            options={
                "ordering": ["-is_active", "-weight", "id"],
                "verbose_name": "Story Prompt",
                "verbose_name_plural": "Story Prompts",
            },
        ),
        migrations.AlterField(
            model_name="userreport",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("connection", "Event connection"),
                    ("message", "Message"),
                    ("profile", "Profile"),
                    ("connect_week", "Connect Week"),
                    ("coach_pick", "Coach pick"),
                ],
                max_length=16,
            ),
        ),
        migrations.RemoveField(
            model_name="connectdailydrop",
            name="read_target",
        ),
        migrations.RemoveField(
            model_name="connectdailydrop",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="connectdailydrop",
            name="user",
        ),
        migrations.RemoveField(
            model_name="curiosityspark",
            name="drop",
        ),
        migrations.RemoveField(
            model_name="curiosityspark",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="curiosityspark",
            name="sender",
        ),
        migrations.DeleteModel(
            name="ConnectQuestionAnswer",
        ),
        migrations.DeleteModel(
            name="ConnectDailyDrop",
        ),
        migrations.DeleteModel(
            name="CuriositySpark",
        ),
    ]
