# Generated by Django 6.0.7 on 2026-08-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0239_retire_connect_curiosity_sparks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushconnectmembership",
            name="preferred_genders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Genders this member wants to see in Connect (empty = open to all)",
            ),
        ),
        migrations.AlterField(
            model_name="crushconnectmembership",
            name="story_answer",
            field=models.CharField(
                blank=True,
                help_text="One-line answer shown on the member's private Connect card",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="crushconnectmembership",
            name="story_prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="The story prompt this member chose during onboarding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_owners",
                to="crush_lu.sparkprompt",
            ),
        ),
        migrations.AlterField(
            model_name="sparkprompt",
            name="text",
            field=models.CharField(
                help_text="Story prompt shown to the member (translated via modeltranslation)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sparkprompt",
            name="text_de",
            field=models.CharField(
                help_text="Story prompt shown to the member (translated via modeltranslation)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sparkprompt",
            name="text_en",
            field=models.CharField(
                help_text="Story prompt shown to the member (translated via modeltranslation)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sparkprompt",
            name="text_fr",
            field=models.CharField(
                help_text="Story prompt shown to the member (translated via modeltranslation)",
                max_length=200,
                null=True,
            ),
        ),
    ]
