# Generated by Django 6.0.7 on 2026-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0240_update_connect_story_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="paused_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set while the member has paused Crush Connect; onboarding and existing chats are preserved",
                null=True,
            ),
        ),
    ]
