# Generated by Django 6.0.8 on 2026-08-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0241_connect_member_pause"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistrationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_genders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Gender codes the applicant wants to meet; empty = open to all",
                    ),
                ),
                ("preferred_age_min", models.PositiveSmallIntegerField(default=18)),
                ("preferred_age_max", models.PositiveSmallIntegerField(default=99)),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Event-language codes (en/de/fr/lu) the applicant wants at the table; empty = any",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="crush_lu.eventregistration",
                    ),
                ),
            ],
        ),
    ]
