# Generated by Django 6.0.8 on 2026-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0243_curated_registration_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="group_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Curated speed dating only: how many people are in one group. Set max participants to this times the most groups you can run in parallel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="planned_groups",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Curated speed dating only: how many parallel groups you have committed to running. Leave blank while undecided — the event page then says “up to N” and selection measures against the full ceiling.",
                null=True,
            ),
        ),
    ]
