# Generated by Django 6.0.8 on 2026-09-01 14:18

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


def clear_curated_speed_dating_gender_caps(apps, schema_editor):
    """Remove stale door caps from events whose groups now own composition."""
    MeetupEvent = apps.get_model("crush_lu", "MeetupEvent")
    MeetupEvent.objects.filter(
        event_type="speed_dating",
        registration_mode="curated",
        group_size__isnull=False,
    ).update(
        max_participants_m=None,
        max_participants_f=None,
        max_participants_nb=None,
    )


def keep_cleared_caps_on_reverse(apps, schema_editor):
    """No-op: historical gender-cap values cannot be reconstructed safely."""


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0244_curated_parallel_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            clear_curated_speed_dating_gender_caps,
            keep_cleared_caps_on_reverse,
        ),
        migrations.AlterField(
            model_name="meetupevent",
            name="group_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Curated speed dating only: how many people are in one group (6–42; six is required to guarantee at least 5 different dates). Set max participants to this times the most groups you can run in parallel.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CuratedEventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Projection generation. Recalculations increment this value so cancelled history does not consume the evening's group numbers.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "group_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("provisional", "Provisional — selected and payable"),
                            ("locked", "Locked — final evening roster"),
                            ("degraded", "Degraded — reproject or compensate"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(default="reciprocal-graph-v1", max_length=64),
                ),
                (
                    "seed",
                    models.CharField(
                        default="0",
                        help_text="Deterministic seed used to reproduce this projection.",
                        max_length=64,
                    ),
                ),
                (
                    "audit_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-sensitive projection scores and decision metadata. Do not copy member preference values here.",
                    ),
                ),
                ("viability_summary", models.JSONField(blank=True, default=dict)),
                (
                    "schedule_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="SHA-256 proof of the provisional roster and schedule structure; contains no raw preference or profile values.",
                        max_length=64,
                    ),
                ),
                ("provisional_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("degraded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "degradation_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "degraded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_groups",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisional_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_id", "group_number"],
            },
        ),
        migrations.CreateModel(
            name="CuratedEventGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_group_memberships",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="crush_lu.curatedeventgroup",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_group_memberships",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "position", "assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="CuratedEventPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("table_number", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_pairings",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="crush_lu.curatedeventgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "round_number", "table_number"],
            },
        ),
        migrations.CreateModel(
            name="CuratedEventPairingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "seat",
                    models.CharField(choices=[("a", "A"), ("b", "B")], max_length=1),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_pairing_participants",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_participants",
                        to="crush_lu.curatedeventgroup",
                    ),
                ),
                (
                    "pairing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="crush_lu.curatedeventpairing",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_pairing_participations",
                        to="crush_lu.eventregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["pairing_id", "seat"],
            },
        ),
        migrations.AddConstraint(
            model_name="curatedeventgroup",
            constraint=models.UniqueConstraint(
                fields=("event", "generation", "group_number"),
                name="curated_group_unique_number_per_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(generation__gte=1, group_number__gte=1),
                name="curated_group_positive_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cancelled_at__isnull", True),
                        ("degraded_at__isnull", True),
                        ("locked_at__isnull", True),
                        ("provisional_at__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("cancelled_at__isnull", True),
                        ("degraded_at__isnull", True),
                        ("locked_at__isnull", True),
                        ("provisional_at__isnull", False),
                        ("status", "provisional"),
                    ),
                    models.Q(
                        ("cancelled_at__isnull", True),
                        ("degraded_at__isnull", True),
                        ("locked_at__isnull", False),
                        ("provisional_at__isnull", False),
                        ("status", "locked"),
                    ),
                    models.Q(
                        ("cancelled_at__isnull", True),
                        ("degraded_at__isnull", False),
                        ("provisional_at__isnull", False),
                        ("status", "degraded"),
                    ),
                    models.Q(("cancelled_at__isnull", False), ("status", "cancelled")),
                    _connector="OR",
                ),
                name="curated_group_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventgroupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("registration",),
                name="curated_member_one_active_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventgroupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("group", "position"),
                name="curated_member_unique_active_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventpairing",
            constraint=models.UniqueConstraint(
                fields=("group", "round_number", "table_number"),
                name="curated_pairing_unique_table_per_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventpairingparticipant",
            constraint=models.UniqueConstraint(
                fields=("group", "round_number", "registration"),
                name="curated_participant_one_group_slot_per_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventpairingparticipant",
            constraint=models.UniqueConstraint(
                fields=("pairing", "seat"),
                name="curated_participant_unique_pairing_seat",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedeventpairingparticipant",
            constraint=models.UniqueConstraint(
                fields=("pairing", "registration"),
                name="curated_participant_unique_in_pairing",
            ),
        ),
    ]
