# Generated by Django 6.0.8 on 2026-09-01 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0245_curated_event_group_persistence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="curated_rounds_started_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Audited start of round one for a locked curated evening. Once set, the all-evening groups are delivered history and never reprojected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="curated_rounds_started_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curated_evenings_started",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventCheckoutCreationClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_id_snapshot",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                ("event_id_snapshot", models.PositiveBigIntegerField(db_index=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("transaction_reference", models.CharField(max_length=64, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Card"), ("credit", "Crush Credit")],
                        max_length=10,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retiring", "Retiring"),
                            ("retired", "Safely retired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "provider_checkout_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Event checkout creation claim",
                "verbose_name_plural": "Event checkout creation claims",
            },
        ),
        migrations.CreateModel(
            name="CuratedGroupNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id_snapshot", models.PositiveBigIntegerField(db_index=True)),
                (
                    "registration_id_snapshot",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("selection", "Selection invitation"),
                            ("remedy", "Unavailable-group payment remedy"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=96, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled as stale"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "claim_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_notifications",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_notifications",
                        to="crush_lu.eventregistration",
                    ),
                ),
                (
                    "source_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_notifications",
                        to="crush_lu.paymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "kind", "created_at"],
                        name="curated_notice_queue_idx",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="crushcredit",
            name="cash_refund_eligible",
            field=models.BooleanField(
                default=False,
                help_text="This member may ask for their money back instead. Set only when Crush.lu cancelled the event or could not provide the certified curated group sold to them — a voucher is not a substitute. Refunds themselves are still made by hand in the SumUp dashboard.",
            ),
        ),
        migrations.AlterField(
            model_name="crushcredit",
            name="reason",
            field=models.CharField(
                choices=[
                    ("member_cancellation", "Member cancelled (>48h)"),
                    ("seat_resold", "Late cancellation, seat resold"),
                    ("event_cancelled", "Crush.lu cancelled the event"),
                    ("curated_group_unavailable", "Curated group became unavailable"),
                    ("goodwill", "Goodwill"),
                    ("referral", "Referral"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="crushcredit",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("refunding", "Refund in progress"),
                    ("consumed", "Fully redeemed"),
                    ("expired", "Expired"),
                    ("void", "Void"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "curated_group_unavailable"),
                    ("restored_from_credit__isnull", True),
                    ("source_payment__isnull", False),
                ),
                fields=("source_payment", "reason"),
                name="one_group_remedy_per_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="crushcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reason", "curated_group_unavailable"),
                    ("restored_from_credit__isnull", False),
                    ("source_payment__isnull", False),
                ),
                fields=("source_payment", "reason", "restored_from_credit"),
                name="one_group_restore_per_tranche",
            ),
        ),
        migrations.AddField(
            model_name="eventcheckoutcreationclaim",
            name="registration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_creation_claim",
                to="crush_lu.eventregistration",
            ),
        ),
    ]
