# Generated by Django 6.0.8 on 2026-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0247_curated_group_withdrawal_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curatedgroupnotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("selection", "Selection invitation"),
                    ("remedy", "Unavailable-group payment remedy"),
                    ("withdrawal", "Unpaid-group withdrawal"),
                    ("reserve", "Not selected — application stays in the pool"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
