# Generated by Django 6.0.8 on 2026-09-04 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0248_curated_reserve_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callattempt",
            name="logged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that recorded this attempt — kept alongside coach so a superuser without a coach row (e.g. on the Custom SMS page) is still attributed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_call_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="callattempt",
            name="result",
            field=models.CharField(
                choices=[
                    ("success", "Call Completed"),
                    ("failed", "Call Failed"),
                    ("sms_sent", "SMS Sent"),
                    ("whatsapp_sent", "WhatsApp Sent"),
                    ("event_invite_sms", "Event Invite SMS"),
                    ("custom_sms", "Custom SMS"),
                ],
                help_text="Whether the call succeeded or failed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomSmsBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label so you can find this batch again later.",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("event", "Event registrations"),
                            ("segment", "User segment"),
                            ("manual", "Manual list (emails or phone numbers)"),
                        ],
                        default="event",
                        max_length=16,
                    ),
                ),
                (
                    "registration_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="EventRegistration statuses included (event audience only).",
                    ),
                ),
                ("segment_key", models.CharField(blank=True, max_length=64)),
                (
                    "manual_user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User ids resolved from the pasted list (manual audience).",
                    ),
                ),
                (
                    "include_unverified_phones",
                    models.BooleanField(
                        default=False,
                        help_text="Also list members whose phone number is not verified. Off by default: an unverified number may belong to someone else.",
                    ),
                ),
                (
                    "message_en",
                    models.TextField(
                        help_text="Used for every recipient without a variant below."
                    ),
                ),
                ("message_de", models.TextField(blank=True)),
                ("message_fr", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_sms_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source of recipients for an event audience; for other audiences it only feeds the {event_title} / {event_date} / {event_url} placeholders.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_sms_batches",
                        to="crush_lu.meetupevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom SMS batch",
                "verbose_name_plural": "Custom SMS batches",
                "ordering": ["-created_at"],
            },
        ),
    ]
