# Generated by Django 6.0.8 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0249_custom_sms_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crushsiteconfig",
            name="social_facebook_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.facebook.com/crushluxembourg",
                verbose_name="Facebook URL",
            ),
        ),
        migrations.AlterField(
            model_name="crushsiteconfig",
            name="social_instagram_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.instagram.com/crushluofficial/",
                verbose_name="Instagram URL",
            ),
        ),
        migrations.AlterField(
            model_name="crushsiteconfig",
            name="social_linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://www.linkedin.com/showcase/crushluapp/",
                verbose_name="LinkedIn URL",
            ),
        ),
    ]
