# Generated by Django 6.0.8 on 2026-09-13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0250_site_config_social_help_text"),
    ]
    operations = [
        migrations.CreateModel(
            name="EmailBounceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_message_id", models.CharField(max_length=512, unique=True)),
                ("recipient", models.EmailField(blank=True, max_length=254)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("hard", "Hard bounce"),
                            ("soft", "Soft bounce"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("diagnostic", models.TextField(blank=True)),
                (
                    "received_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-received_at", "-processed_at"]},
        ),
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "reason",
                    models.CharField(default="hard_bounce", max_length=120),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("graph_ndr", "Microsoft Graph NDR"),
                            ("manual", "Manual"),
                        ],
                        default="graph_ndr",
                        max_length=20,
                    ),
                ),
                ("diagnostic", models.TextField(blank=True)),
                (
                    "suppressed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-suppressed_at"]},
        ),
    ]
