# Generated by Django 6.0.8 on 2026-09-14 19:06

from django.conf import settings
from django.db import migrations, models


def mark_legacy_read(apps, schema_editor):
    from django.utils import timezone

    Message = apps.get_model("crush_lu", "ConnectChatMessage")
    Message.objects.using(schema_editor.connection.alias).filter(
        read_at__isnull=True
    ).update(read_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0251_email_delivery_suppression"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(mark_legacy_read, migrations.RunPython.noop),
        migrations.AddField(
            model_name="connectchatmessage",
            name="client_submission_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="connectchatmessage",
            constraint=models.UniqueConstraint(
                fields=("chat", "sender", "client_submission_id"),
                name="connect_message_submission_unique",
            ),
        ),
    ]
