# Generated by Django 6.0.8 on 2026-09-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0252_connect_chat_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectcyclecard",
            name="card_index",
            field=models.PositiveSmallIntegerField(
                help_text="Position of the card within its day (1-based)"
            ),
        ),
        migrations.AlterField(
            model_name="connectcyclecard",
            name="day_number",
            field=models.PositiveSmallIntegerField(
                help_text="Cycle day on which this card was generated (1-based)"
            ),
        ),
        migrations.AlterField(
            model_name="connectweeksession",
            name="current_day_number",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Current day of the cycle (1-based)"
            ),
        ),
        migrations.AlterField(
            model_name="connectweeksession",
            name="is_review_open",
            field=models.BooleanField(
                default=False,
                help_text="True during the 24h review window after the last cycle day",
            ),
        ),
        migrations.AlterField(
            model_name="connectweeksession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active (in cycle)"),
                    ("review_open", "Review Open (24h review window)"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("abandoned", "Abandoned"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
