# Generated by Django 6.0.8 on 2026-09-26 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0253_connect_cycle_two_by_five"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpoll",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Anyone can view; any logged-in account can vote (no approved profile needed).",
            ),
        ),
        migrations.AddField(
            model_name="eventpollvote",
            name="voter_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Woman"),
                    ("M", "Man"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="EventPollSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("language", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="crush_lu.eventpoll",
                    ),
                ),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="crush_lu.eventpolloption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_poll_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Suggestion",
                "verbose_name_plural": "Poll Suggestions",
                "ordering": ["-created_at"],
            },
        ),
    ]
