# Generated by Django 6.0.8 on 2026-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0254_event_poll_public_and_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_shares_email",
            field=models.BooleanField(
                default=True,
                help_text="Recipient chose to include their email in what is shared",
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="requester_shares_email",
            field=models.BooleanField(
                default=True,
                help_text="Requester chose to include their email in what is shared",
            ),
        ),
        # The AddFields above backfill existing rows as True (their historical
        # behaviour); new rows default to False.
        migrations.AlterField(
            model_name="eventconnection",
            name="recipient_shares_email",
            field=models.BooleanField(
                default=False,
                help_text="Recipient chose to include their email in what is shared",
            ),
        ),
        migrations.AlterField(
            model_name="eventconnection",
            name="requester_shares_email",
            field=models.BooleanField(
                default=False,
                help_text="Requester chose to include their email in what is shared",
            ),
        ),
    ]
