# Generated by Django 6.0.8 on 2026-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0254_event_poll_public_and_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="on_break_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set while the member has taken a self-service break — hides them from events, Connect matching and marketing until they resume.",
                null=True,
            ),
        ),
    ]
