# Generated by Django 6.1.1 on 2026-09-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0254_event_poll_public_and_suggestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreport",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spark", "Curiosity Spark (legacy)"),
                    ("drop", "Daily Drop (legacy)"),
                    ("connection", "Event connection"),
                    ("message", "Message"),
                    ("profile", "Profile"),
                    ("connect_week", "Connect Week"),
                    ("coach_pick", "Coach pick"),
                    ("connect_chat", "Connect chat"),
                ],
                max_length=16,
            ),
        ),
    ]
