# Generated by Django 6.0.8 on 2026-09-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0255_eventconnection_recipient_shares_email_and_more"),
        ("crush_lu", "0255_userreport_connect_chat_source"),
    ]

    operations = []
