# Generated by Django 6.0.8 on 2026-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0255_crushprofile_on_break_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushconnectmembership",
            name="paused_by_break",
            field=models.BooleanField(
                default=False,
                help_text="True when this pause was set by CrushProfile.take_a_break() rather than the member's own Connect pause control. resume_from_break() only reactivates Connect when this is True, so it never undoes an independent, self-service Connect pause (UX Wave 3 · WP13).",
            ),
        ),
    ]
