# Generated by Django 6.0.8 on 2026-09-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0256_merge_20260927_1319"),
        ("crush_lu", "0256_crushconnectmembership_paused_by_break"),
    ]

    operations = []
