# Generated by Django 6.1.1 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0257_merge_20260927_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventconnection",
            name="recipient_shares_phone",
            field=models.BooleanField(
                default=False,
                help_text="Recipient chose to include their phone number in what is shared",
            ),
        ),
        migrations.AddField(
            model_name="eventconnection",
            name="requester_shares_phone",
            field=models.BooleanField(
                default=False,
                help_text="Requester chose to include their phone number in what is shared",
            ),
        ),
    ]
