# Generated by Django 6.0.8 on 2026-10-02 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0258_eventconnection_shares_phone_opt_in"),
        ("hub", "0012_partner_and_offers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupevent",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetup_events",
                to="hub.partneroffer",
            ),
        ),
        migrations.AddField(
            model_name="meetupevent",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetup_events",
                to="hub.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetupevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("offer__isnull", True), ("partner__isnull", False), _connector="OR"
                ),
                name="crush_event_offer_requires_partner",
            ),
        ),
    ]
