# Generated by Django 6.1.1 on 2026-10-02 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0259_event_partner_offer_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumPaymentRecoveryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("duplicate_capture", "Duplicate capture"),
                            ("coach_unavailable", "Coach unavailable"),
                            ("request_cancelled", "Request cancelled"),
                            ("beta_revoked", "Beta access revoked"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("member_notified_at", models.DateTimeField(blank=True, null=True)),
                ("staff_alerted_at", models.DateTimeField(blank=True, null=True)),
                ("staff_only", models.BooleanField(default=False)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_recovery_case",
                        to="crush_lu.paymenttransaction",
                    ),
                ),
                (
                    "premium_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_cases",
                        to="crush_lu.premiummembership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_recovery_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium payment recovery case",
                "verbose_name_plural": "Premium payment recovery cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
