# Generated by Django 6.0.8 on 2026-10-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0259_event_partner_offer_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="crushprofile",
            name="photo_review_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Storage key of photo_1 when reviewed; change invalidates review",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_review_notes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal note from coach on photo decision",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved / Authentic"),
                    ("needs_revision", "Needs Revision (Unclear / Inappropriate)"),
                    ("flagged_fake", "Flagged Fake / Suspicious"),
                ],
                db_index=True,
                default="pending",
                help_text="Coach online photo review status for Crush Connect",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_reviewed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the current photo was reviewed by a coach",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crushprofile",
            name="photo_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Coach who reviewed the current photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo_reviews_conducted",
                to="crush_lu.crushcoach",
            ),
        ),
        migrations.CreateModel(
            name="ProfilePhotoReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_key", models.CharField(max_length=255)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved / Authentic"),
                            ("flagged_fake", "Flagged Fake or Suspicious"),
                            ("needs_revision", "Needs Revision"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear_authentic", "Clear and authentic photo"),
                            ("fake_profile", "Fake or impersonating profile"),
                            ("inappropriate", "Inappropriate or explicit content"),
                            ("unclear_face", "Face unclear or covered"),
                            ("group_photo", "Group photo / cannot identify member"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_review_logs",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_review_logs",
                        to="crush_lu.crushprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Photo Review Log",
                "verbose_name_plural": "Profile Photo Review Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["coach", "-created_at"], name="photo_rev_coach_idx"
                    ),
                    models.Index(
                        fields=["profile", "-created_at"], name="photo_rev_prof_idx"
                    ),
                ],
            },
        ),
    ]
