# Generated by Django 6.0.8 on 2026-10-06 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0260_crushprofile_photo_review_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="decision_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="exclusion_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crush_lu.userreport",
            ),
        ),
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="undone_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="withdrawn_picks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
