# Generated by Django 6.1.1 on 2026-10-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0260_premium_payment_recovery_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="premium_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transactions",
                to="crush_lu.premiummembership",
            ),
        ),
    ]
