# Generated by Django 6.0.8 on 2026-10-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0261_photo_review_undo_audit"),
        ("crush_lu", "0262_backfill_premium_recovery_cases"),
    ]

    operations = []
