# Generated by Django 6.1.1 on 2026-10-06 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0262_backfill_premium_recovery_cases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumpaymentrecoverycase",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("refunded", "Refunded"),
                    ("applied", "Applied (member agreed)"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="premiumpaymentrecoverycase",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="premiumpaymentrecoverycase",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
