# Generated by Django 6.0.8 on 2026-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0263_merge_photo_review_and_premium_recovery"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="revision_notification_state",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=20
            ),
        ),
    ]
