# Generated by Django 6.0.8 on 2026-10-06 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def copy_primary_review_state(apps, schema_editor):
    Profile = apps.get_model("crush_lu", "CrushProfile")
    ReviewState = apps.get_model("crush_lu", "ProfilePhotoReviewState")
    database = schema_editor.connection.alias
    for profile in Profile.objects.using(database).iterator():
        if profile.photo_review_status == "pending" or not profile.photo_1:
            continue
        if (
            not profile.photo_review_key
            and profile.photo_review_status != "flagged_fake"
        ):
            # Never bound to a file, so it never approved the current one.
            continue
        ReviewState.objects.using(database).create(
            profile_id=profile.pk,
            photo_field="photo_1",
            photo_key=profile.photo_review_key or str(profile.photo_1),
            status=profile.photo_review_status,
            reviewed_at=profile.photo_reviewed_at or timezone.now(),
            reviewed_by_id=profile.photo_reviewed_by_id,
            notes=profile.photo_review_notes,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0266_photo_review_membership_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="photo_field",
            field=models.CharField(
                choices=[
                    ("photo_1", "Primary photo"),
                    ("photo_2", "Photo 2"),
                    ("photo_3", "Photo 3"),
                ],
                default="photo_1",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="ProfilePhotoReviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_field",
                    models.CharField(
                        choices=[
                            ("photo_1", "Primary photo"),
                            ("photo_2", "Photo 2"),
                            ("photo_3", "Photo 3"),
                        ],
                        max_length=7,
                    ),
                ),
                ("photo_key", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Coach reviewed"),
                            ("needs_revision", "Needs revision"),
                            ("flagged_fake", "Flagged fake or suspicious"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_review_states",
                        to="crush_lu.crushprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_review_states",
                        to="crush_lu.crushcoach",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["photo_field", "status"],
                        name="photo_state_field_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "photo_field"),
                        name="unique_photo_review_state_per_slot",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_primary_review_state, migrations.RunPython.noop),
    ]
