# Generated by Django 6.0.8 on 2026-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0267_per_photo_review_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesubmission",
            name="fallback_offer_claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the sweep last claimed this submission for a fallback email.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilesubmission",
            name="fallback_offer_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the fallback email was sent or terminally skipped.",
                null=True,
            ),
        ),
    ]
