# Generated by Django 6.0.8 on 2026-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0269_email_suppression_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilephotoreviewlog",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clear_authentic", "Clear and authentic photo"),
                    ("fake_profile", "Fake or impersonating profile"),
                    ("inappropriate", "Inappropriate or explicit content"),
                    ("unclear_face", "Face unclear or covered"),
                    ("group_photo", "Group photo / cannot identify member"),
                    ("blurry_photo", "Blurry or low-quality photo"),
                    ("poor_lighting", "Photo too dark or poorly lit"),
                    ("heavy_filter", "Heavy filters or altered appearance"),
                    ("not_person", "Does not show the member"),
                    ("cropped_face", "Face cropped or too far away"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
