# Generated by Django 6.1.1 on 2026-10-09 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0270_photo_review_refusal_reasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="batch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="profilephotoreviewlog",
            name="previous_published_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="PhotoReviewClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_review_claims",
                        to="crush_lu.crushcoach",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_review_claim",
                        to="crush_lu.crushprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePhotoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_field",
                    models.CharField(
                        choices=[
                            ("photo_1", "Primary photo"),
                            ("photo_2", "Photo 2"),
                            ("photo_3", "Photo 3"),
                        ],
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_uploads",
                        to="crush_lu.crushprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "photo_field", "created_at"],
                        name="photo_upload_slot_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublishedProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_field",
                    models.CharField(
                        choices=[
                            ("photo_1", "Primary photo"),
                            ("photo_2", "Photo 2"),
                            ("photo_3", "Photo 3"),
                        ],
                        max_length=7,
                    ),
                ),
                ("photo_key", models.CharField(max_length=255)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_photos",
                        to="crush_lu.crushprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "photo_field"),
                        name="unique_published_photo_per_slot",
                    )
                ],
            },
        ),
    ]
