# Generated by Django 6.0.8 on 2026-10-10 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0272_publish_existing_profile_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="event_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Mixer ticket number, frozen at the first print",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_number__isnull", False)),
                fields=("event", "event_number"),
                name="eventreg_unique_event_number",
            ),
        ),
    ]
