# Generated by Django 6.0.8 on 2026-10-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0272_publish_existing_profile_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="MixerTicketNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("in_first_print", models.BooleanField(default=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mixer_ticket_numbers",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mixer_ticket_numbers",
                        to="crush_lu.eventregistration",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "number"), name="mixerticket_unique_number"
                    ),
                    models.UniqueConstraint(
                        fields=("event", "registration"),
                        name="mixerticket_unique_registration",
                    ),
                ],
            },
        ),
    ]
