# Generated by Django 6.0.8 on 2026-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0273_mixerticketnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="promotion_notice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("push", "Push only"),
                    ("bell", "In-app only"),
                    ("failed", "Not sent"),
                ],
                default="",
                help_text="What reached the member about that promotion. Blank with a promotion time means the notice never recorded an outcome.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="waitlist_promoted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an automatic waitlist promotion gave this member a seat.",
                null=True,
            ),
        ),
    ]
