# Generated by Django 6.0.6 on 2026-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_type', models.CharField(default='text', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['is_read', '-received_at'], name='hub_whatsap_is_read_e78bd3_idx')],
            },
        ),
    ]
