# Generated by Django 6.0.7 on 2026-07-23 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_whatsappinboundmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("event_recap", "Event Recap"),
                            ("dating_tip", "Dating Tip"),
                            ("milestone", "Milestone"),
                            ("community", "Community"),
                            ("promo", "Promotion"),
                        ],
                        default="event_recap",
                        max_length=32,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                        default="fr",
                        max_length=8,
                    ),
                ),
                ("platforms", models.JSONField(blank=True, default=list)),
                ("buffer_profile_ids", models.JSONField(blank=True, default=list)),
                ("hook", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                ("media_url", models.URLField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("buffer_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "article_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_social_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
