# Generated by Django 6.0.7 on 2026-08-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_socialpost_buffer_delivery_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(default="Luxembourg", max_length=100)),
                ("max_capacity", models.PositiveIntegerField()),
                ("seated_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("has_outdoor_space", models.BooleanField(default=False)),
                ("has_kitchen", models.BooleanField(default=False)),
                ("has_private_room", models.BooleanField(default=False)),
                ("has_sound_system", models.BooleanField(default=False)),
                ("compatible_event_types", models.JSONField(blank=True, default=list)),
                (
                    "partnership_stage",
                    models.CharField(
                        choices=[
                            ("Prospect", "Prospect"),
                            ("Negotiating", "Negotiating"),
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Archived", "Archived"),
                        ],
                        default="Prospect",
                        max_length=20,
                    ),
                ),
                (
                    "account_manager",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("commercial_terms", models.TextField(blank=True, default="")),
                ("partner_since", models.DateField(blank=True, null=True)),
                ("last_contact_date", models.DateField(blank=True, null=True)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_capacity__gte", 1)),
                        name="hub_location_max_capacity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seated_capacity__isnull", True),
                            models.Q(
                                ("seated_capacity__gte", 1),
                                ("seated_capacity__lte", models.F("max_capacity")),
                            ),
                            _connector="OR",
                        ),
                        name="hub_location_valid_seated_capacity",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_contact",
                        to="hub.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
