# Generated by Django 6.0.7 on 2026-08-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_location_locationcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(max_length=255)),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Overdue", "Overdue"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Card", "Card"),
                            ("Transfer", "Transfer"),
                            ("Cash", "Cash"),
                            ("Payconiq", "Payconiq"),
                        ],
                        default="Transfer",
                        max_length=20,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="hub_paymentin_amount_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employer_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Salary", "Salary"),
                            ("Expense", "Expense"),
                            ("Bonus", "Bonus"),
                        ],
                        default="Salary",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Overdue", "Overdue"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Card", "Card"),
                            ("Transfer", "Transfer"),
                            ("Cash", "Cash"),
                            ("Payconiq", "Payconiq"),
                        ],
                        default="Transfer",
                        max_length=20,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__gte", 0),
                            ("gross_salary__gte", 0),
                            ("employer_charges__gte", 0),
                        ),
                        name="hub_payroll_amounts_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("participant_name", models.CharField(max_length=255)),
                (
                    "event_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Overdue", "Overdue"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="hub_refund_amount_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payee", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Overdue", "Overdue"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Card", "Card"),
                            ("Transfer", "Transfer"),
                            ("Cash", "Cash"),
                            ("Payconiq", "Payconiq"),
                        ],
                        default="Transfer",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Lieu", "Lieu"),
                            ("Marketing", "Marketing"),
                            ("Tech", "Tech"),
                            ("Fournitures", "Fournitures"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=20,
                    ),
                ),
                (
                    "deposit_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Balance"),
                            ("full", "Full"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_out",
                        to="hub.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="hub_paymentout_amount_non_negative",
                    )
                ],
            },
        ),
    ]
