# Generated by Django 6.0.8 on 2026-10-01 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def flag_existing_contacts_primary(apps, schema_editor):
    apps.get_model("hub", "LocationContact").objects.update(is_primary=True)


def collapse_contacts_to_one(apps, schema_editor):
    """Reverse: the old schema allows one contact per location.

    Keeps the primary (else the oldest) contact and appends each dropped
    contact's details to the location's notes, so a rollback after the
    multi-contact feature was used loses no information.
    """
    Location = apps.get_model("hub", "Location")
    Contact = apps.get_model("hub", "LocationContact")
    for location in Location.objects.filter(contacts__isnull=False).distinct():
        contacts = list(location.contacts.order_by("-is_primary", "id"))
        for dropped in contacts[1:]:
            details = ", ".join(
                part
                for part in (dropped.name, dropped.role, dropped.email, dropped.phone)
                if part
            )
            note = f"Contact removed on rollback: {details}"
            location.notes = f"{location.notes}\n{note}".strip()
        if len(contacts) > 1:
            location.save(update_fields=["notes"])
            Contact.objects.filter(id__in=[c.id for c in contacts[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0258_eventconnection_shares_phone_opt_in"),
        ("hub", "0009_paymentin_payroll_refund_paymentout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("speed_dating", "Speed Dating"),
                            ("mixer", "Social Mixer"),
                            ("activity", "Activity Meetup"),
                            ("themed", "Themed Event"),
                            ("quiz_night", "Quiz Night"),
                            ("crush_cache", "Crush Cache Hunt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Weekdays, 0 = Monday … 6 = Sunday.",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                ("max_participants", models.PositiveIntegerField(default=20)),
                (
                    "max_participants_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_participants_f",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_participants_nb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("min_age", models.PositiveIntegerField(default=18)),
                ("max_age", models.PositiveIntegerField(default=99)),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Event fee in EUR.",
                        max_digits=6,
                    ),
                ),
                ("partner_cost_notes", models.TextField(blank=True, default="")),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_de", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_de", models.TextField(blank=True, default="", null=True)),
                ("description_fr", models.TextField(blank=True, default="", null=True)),
                ("has_food_component", models.BooleanField(default=False)),
                ("allow_plus_ones", models.BooleanField(default=False)),
                (
                    "space_used",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("setup_notes", models.TextField(blank=True, default="")),
                ("languages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["location__name", "event_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerOnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("contact_made", "First contact made"),
                            ("terms_agreed", "Terms agreed"),
                            ("venue_visit", "Venue visit done"),
                            ("photos", "Photos collected"),
                            ("house_rules", "House rules recorded"),
                            ("test_event", "Test event held"),
                            ("echo_venue_registered", "echo.lu venue registered"),
                            ("active", "Partner active"),
                        ],
                        max_length=30,
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AlterModelOptions(
            name="locationcontact",
            options={"ordering": ["-is_primary", "name"]},
        ),
        migrations.AddField(
            model_name="location",
            name="address_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="address_postcode",
            field=models.CharField(
                blank=True,
                default="",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Luxembourg postcodes are exactly four digits.",
                        regex="^[0-9]{4}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="address_street",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="address_town",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="blackout_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="location",
            name="canton",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="echo_venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="crush_lu.echovenue",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="house_rules",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="minimum_spend",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="opening_hours",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="location",
            name="revenue_share_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="locationcontact",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="locationcontact",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="hub.location",
            ),
        ),
        # The contact was a OneToOne, so every existing row is its location's only
        # contact: flag it primary before the one-primary constraint exists.
        migrations.RunPython(flag_existing_contacts_primary, collapse_contacts_to_one),
        migrations.AddConstraint(
            model_name="locationcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("location",),
                name="hub_locationcontact_one_primary_per_location",
            ),
        ),
        migrations.AddField(
            model_name="partneroffer",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="hub.location",
            ),
        ),
        migrations.AddField(
            model_name="partneronboardingstep",
            name="done_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partneronboardingstep",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_steps",
                to="hub.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="partneroffer",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_participants__gte", 1)),
                name="hub_partneroffer_max_participants_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="partneroffer",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_age__lte", models.F("max_age"))),
                name="hub_partneroffer_valid_age_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="partneronboardingstep",
            constraint=models.UniqueConstraint(
                fields=("location", "key"), name="hub_partneronboardingstep_unique_key"
            ),
        ),
    ]
