# Generated by Django 6.0.8 on 2026-10-06 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crush_lu", "0264_oauthstate_auth_recovery_hash"),
        ("hub", "0012_partner_and_offers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCoachAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coach_name", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Animation", "Animation"),
                            ("Accueil", "Accueil"),
                            ("Photo/Vidéo", "Photo/Vidéo"),
                            ("Support", "Support"),
                        ],
                        default="Animation",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("assigned", "Assigné"),
                            ("declined", "Écarté"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_availabilities",
                        to="crush_lu.meetupevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_coach_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-declared_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"),
                        name="unique_hub_event_user_availability",
                    )
                ],
            },
        ),
    ]
