# Generated by Django 6.0.8 on 2026-10-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_socialpost_media_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErasedPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
