# Generated by Django 5.1.15 on 2026-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_date', models.DateField(db_index=True)),
                ('anomaly_type', models.CharField(choices=[('spike', 'Cost Spike'), ('sudden_service', 'New Service Detected'), ('unusual_resource', 'Unusual Resource Cost'), ('sustained_increase', 'Sustained Cost Increase')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('dimension_type', models.CharField(max_length=50)),
                ('dimension_value', models.CharField(max_length=300)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deviation_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finops_hub_costanomaly',
                'ordering': ['-detected_date', '-severity'],
                'indexes': [models.Index(fields=['detected_date', 'severity'], name='finops_hub__detecte_27b2d0_idx'), models.Index(fields=['dimension_type', 'dimension_value'], name='finops_hub__dimensi_b9e937_idx'), models.Index(fields=['is_acknowledged', 'detected_date'], name='finops_hub__is_ackn_2053bf_idx')],
            },
        ),
    ]
