# Generated by Django 5.1.15 on 2026-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finops', '0003_add_cost_anomaly_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('dimension_type', models.CharField(max_length=50)),
                ('dimension_value', models.CharField(max_length=300)),
                ('forecast_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('model_type', models.CharField(default='linear_regression', max_length=50)),
                ('training_period_start', models.DateField()),
                ('training_period_end', models.DateField()),
                ('training_days', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'finops_hub_costforecast',
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['forecast_date', 'dimension_type'], name='finops_hub__forecas_7d36c3_idx'), models.Index(fields=['generated_at', 'dimension_type'], name='finops_hub__generat_cb428a_idx')],
                'unique_together': {('forecast_date', 'dimension_type', 'dimension_value')},
            },
        ),
    ]
