# Generated by Django 5.1.15 on 2026-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finops', '0004_add_cost_forecast_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reservation_order_id', models.CharField(db_index=True, max_length=100)),
                ('reservation_name', models.CharField(max_length=200)),
                ('sku_name', models.CharField(max_length=200)),
                ('sku_description', models.TextField(blank=True)),
                ('service_name', models.CharField(db_index=True, max_length=200)),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('purchase_date', models.DateField(db_index=True)),
                ('expiry_date', models.DateField()),
                ('term_months', models.IntegerField()),
                ('billing_plan', models.CharField(default='Monthly', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_amortization', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('is_estimate', models.BooleanField(db_index=True, default=True)),
                ('pricing_source', models.CharField(default='Azure Retail Prices API', max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finops_hub_reservationcost',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['reservation_id', 'is_estimate'], name='finops_hub__reserva_c5dfc3_idx'), models.Index(fields=['service_name', 'region'], name='finops_hub__service_2bf5ce_idx'), models.Index(fields=['purchase_date', 'expiry_date'], name='finops_hub__purchas_274088_idx')],
            },
        ),
    ]
