# Generated by Django 6.0.7 on 2026-08-20 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finops", "0007_costbudget"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailPriceSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=50)),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(db_index=True, default="EUR", max_length=3),
                ),
                ("regions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("connector_name", models.CharField(max_length=100)),
                ("source_endpoint", models.URLField(max_length=500)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("raw_item_count", models.PositiveIntegerField(default=0)),
                ("normalized_item_count", models.PositiveIntegerField(default=0)),
                ("invalid_item_count", models.PositiveIntegerField(default=0)),
                ("duplicate_item_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "finops_hub_retailpricesyncrun",
                "ordering": ["-snapshot_date", "-started_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "snapshot_date", "status"],
                        name="finops_hub__provide_61588d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "completed")),
                        fields=("provider", "snapshot_date", "currency"),
                        name="finops_one_completed_price_sync_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailPriceRawPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("source_url", models.URLField(max_length=2000)),
                ("next_page_url", models.URLField(blank=True, max_length=2000)),
                ("response_sha256", models.CharField(db_index=True, max_length=64)),
                ("payload_gzip", models.BinaryField()),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_pages",
                        to="finops.retailpricesyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "finops_hub_retailpricerawpage",
                "ordering": ["sync_run", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="RetailPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=50)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("source_item_index", models.PositiveIntegerField()),
                (
                    "service_category",
                    models.CharField(default="compute", max_length=50),
                ),
                (
                    "resource_type",
                    models.CharField(default="virtual_machine", max_length=50),
                ),
                ("provider_sku", models.CharField(db_index=True, max_length=200)),
                ("sku_name", models.CharField(blank=True, max_length=200)),
                ("instance_family", models.CharField(blank=True, max_length=200)),
                ("product_name", models.CharField(db_index=True, max_length=300)),
                ("meter_name", models.CharField(max_length=300)),
                (
                    "operating_system",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vcpu_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "memory_gib",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("gpu_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("architecture", models.CharField(blank=True, max_length=50)),
                ("region_code", models.CharField(db_index=True, max_length=100)),
                ("location_name", models.CharField(blank=True, max_length=200)),
                (
                    "data_residency_scope",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("currency", models.CharField(db_index=True, max_length=3)),
                ("price_type", models.CharField(db_index=True, max_length=50)),
                ("purchase_model", models.CharField(db_index=True, max_length=50)),
                ("term", models.CharField(blank=True, max_length=50)),
                ("unit_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("unit_of_measure", models.CharField(max_length=100)),
                ("effective_start_date", models.DateTimeField(blank=True, null=True)),
                ("provider_item_id", models.CharField(blank=True, max_length=200)),
                ("provider_product_id", models.CharField(blank=True, max_length=200)),
                ("provider_meter_id", models.CharField(blank=True, max_length=200)),
                ("is_primary_meter", models.BooleanField(blank=True, null=True)),
                ("price_key", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="finops.retailpricerawpage",
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="finops.retailpricesyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "finops_hub_retailpricesnapshot",
                "ordering": ["-snapshot_date", "provider_sku", "region_code"],
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_sku", "snapshot_date"],
                        name="finops_price_sku_date_idx",
                    ),
                    models.Index(
                        fields=["provider", "region_code", "snapshot_date"],
                        name="finops_price_region_date_idx",
                    ),
                    models.Index(
                        fields=["currency", "purchase_model", "snapshot_date"],
                        name="finops_price_offer_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "snapshot_date", "price_key"),
                        name="finops_unique_daily_provider_price",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="retailpricerawpage",
            constraint=models.UniqueConstraint(
                fields=("sync_run", "page_number"),
                name="finops_unique_raw_page_per_sync",
            ),
        ),
    ]
