# Generated by Django 6.0.7 on 2026-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finops", "0008_retailpricesyncrun_retailpricerawpage_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="retailpricesyncrun",
            name="finops_one_completed_price_sync_per_day",
        ),
        migrations.AddField(
            model_name="retailpricesyncrun",
            name="region",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="retailpricesyncrun",
            index=models.Index(
                fields=["provider", "snapshot_date", "region"],
                name="finops_hub__provide_f4948a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="retailpricesyncrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "completed")),
                fields=("provider", "snapshot_date", "currency", "region"),
                name="finops_one_completed_price_sync_per_region_day",
            ),
        ),
    ]
