# Generated by Django 6.0.7 on 2026-08-22 08:31

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError
from django.db.models import Count


def _noop(apps, schema_editor):
    """Nothing to do going forward; this step exists for its reverse guard."""


def _refuse_reverse_once_regions_exist(apps, schema_editor):
    """Stop a reverse that the restored constraint would abort on anyway.

    Reversing re-creates ``finops_one_completed_price_sync_per_day``, which
    permits a single completed run per provider/date/currency. Once a day has
    been captured region by region there are nineteen of them, so the database
    rejects the constraint and the migration dies half-applied. Fail up front
    with something actionable instead of at the last operation.

    Rolling the *code* back needs none of this: old code writes ``region=""``,
    which is still unique under the current constraint, so a slot swap is
    unaffected. This guards `migrate finops 0008`, not a redeploy.
    """
    sync_run = apps.get_model("finops", "RetailPriceSyncRun")
    clashes = list(
        sync_run.objects.filter(status="completed")
        .values("provider", "snapshot_date", "currency")
        .annotate(run_count=Count("id"))
        .filter(run_count__gt=1)
        .order_by("-snapshot_date")[:5]
    )
    if clashes:
        detail = ", ".join(
            f"{row['provider']}/{row['snapshot_date']}/{row['currency']}"
            f" ({row['run_count']} runs)"
            for row in clashes
        )
        raise IrreversibleError(
            "Cannot reverse finops.0009: per-region snapshots already exist and "
            "the old one-completed-run-per-day constraint would reject them - "
            f"e.g. {detail}. Reduce each day to a single completed run, or mark "
            "the extras failed, before reversing. Rolling the application code "
            "back does not require this: old code writes region='' and stays "
            "unique under the current constraint."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("finops", "0008_retailpricesyncrun_retailpricerawpage_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="retailpricesyncrun",
            name="finops_one_completed_price_sync_per_day",
        ),
        migrations.AddField(
            model_name="retailpricesyncrun",
            name="region",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="retailpricesyncrun",
            index=models.Index(
                fields=["provider", "snapshot_date", "region"],
                name="finops_hub__provide_f4948a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="retailpricesyncrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "completed")),
                fields=("provider", "snapshot_date", "currency", "region"),
                name="finops_one_completed_price_sync_per_region_day",
            ),
        ),
        # Last, so that on a reverse — which runs operations backwards — this
        # is the first thing evaluated and nothing is touched before it decides.
        migrations.RunPython(_noop, _refuse_reverse_once_regions_exist),
    ]
