# Generated by Django 4.2.23 on 2025-12-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('email_domains', models.JSONField(blank=True, default=list, help_text="Email domains for auto-matching users, e.g., ['company.lu', 'company.com']")),
                ('microsoft_tenant_id', models.CharField(blank=True, help_text='Microsoft Entra ID tenant ID for precise user matching', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_workers', models.BooleanField(default=False, help_text="Automatically approve users from this company's domain")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DelegationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_id', models.CharField(blank=True, help_text='Microsoft account object ID', max_length=255, null=True, unique=True)),
                ('microsoft_tenant_id', models.CharField(blank=True, help_text="User's Microsoft tenant ID", max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='delegation_profiles/')),
                ('role', models.CharField(choices=[('pending', 'Pending Verification'), ('worker', 'Worker'), ('staff_delegate', 'Staff Delegate'), ('delegate_admin', 'Delegate Admin')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('no_company', 'No Company Match')], default='pending', max_length=20)),
                ('manually_approved', models.BooleanField(default=False, help_text='Admin manually approved this user')),
                ('manually_blocked', models.BooleanField(default=False, help_text='Admin manually blocked this user')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='delegations.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegation Profile',
                'verbose_name_plural': 'Delegation Profiles',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Successful'), ('login_blocked', 'Login Blocked'), ('login_pending', 'Login - Pending Approval'), ('auto_approved', 'Auto-Approved'), ('auto_rejected', 'Auto-Rejected'), ('manual_approved', 'Manually Approved'), ('manual_rejected', 'Manually Rejected'), ('no_company_match', 'No Company Match')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='delegations.delegationprofile')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
