# Generated by Django 5.1.4 on 2025-12-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='delegationprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='delegationprofile',
            name='office_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
