# Generated by Django 5.1.4 on 2026-01-02 23:26

import crush_lu.storage
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crush_delegation', '0002_add_default_to_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('powerup', 'delegation/companies'), **{})),
        ),
        migrations.AlterField(
            model_name='delegationprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(crush_lu.storage._domain_upload_path, *('powerup', 'delegation/profiles'), **{})),
        ),
    ]
