# Generated by Django 5.1.15 on 2026-01-30 13:29

import functools
import power_up.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0003_update_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=power_up.storage.get_powerup_media_storage, upload_to=functools.partial(power_up.storage._powerup_upload_path, *('delegation/companies',), **{})),
        ),
        migrations.AlterField(
            model_name='delegationprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=power_up.storage.get_powerup_media_storage, upload_to=functools.partial(power_up.storage._powerup_upload_path, *('delegation/profiles',), **{})),
        ),
    ]
