# Generated by renaming crush_delegation app to delegations

from django.db import migrations


class Migration(migrations.Migration):
    """
    Rename database tables from crush_delegation_* to delegations_*.

    IMPORTANT: Before running this migration, you must update the django_migrations table:

    For SQLite (development):
        UPDATE django_migrations SET app = 'delegations' WHERE app = 'crush_delegation';

    For PostgreSQL (production):
        UPDATE django_migrations SET app = 'delegations' WHERE app = 'crush_delegation';

    This migration renames the tables to match the new app name.
    """

    dependencies = [
        ('delegations', '0003_update_upload_paths'),
    ]

    operations = [
        # Rename Company table
        migrations.RunSQL(
            sql="ALTER TABLE crush_delegation_company RENAME TO delegations_company;",
            reverse_sql="ALTER TABLE delegations_company RENAME TO crush_delegation_company;",
        ),
        # Rename DelegationProfile table
        migrations.RunSQL(
            sql="ALTER TABLE crush_delegation_delegationprofile RENAME TO delegations_delegationprofile;",
            reverse_sql="ALTER TABLE delegations_delegationprofile RENAME TO crush_delegation_delegationprofile;",
        ),
        # Rename AccessLog table
        migrations.RunSQL(
            sql="ALTER TABLE crush_delegation_accesslog RENAME TO delegations_accesslog;",
            reverse_sql="ALTER TABLE delegations_accesslog RENAME TO crush_delegation_accesslog;",
        ),
    ]
