# Generated by Django 6.0.4 on 2026-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegations", "0004_alter_company_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
